feat: 약속잡기 컨트롤러 테스트 및 RestDocs 문서 작성
woowacourse-teams/2022-mo-rak pull request #116
Opened 2022-07-27 07:06 UTC by RIANAEH

## 상세 내용
약속잡기 컨트롤러 테스트를 추가하고, RestDocs 문서를 작성했어요. 

🟡 나중에 해야하는 부분은 todo로 명시해놨어요. 

Close #112

2022-07-27 07:22 UTC, seong-wooo approved these changes

2022-07-27 07:38 UTC, cjlee38 requested changes
👍👍👍 사소한 컨벤션 몇가지만 수정해주시면 될 것 같습니다

2022-07-27 07:38 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentStatusTest.java
> +    public void 약속잡기가_종료된_경우_true를_반환한다() {
컨벤션 에러 ! public을 떼주세요 ~~

2022-07-27 07:38 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/ui/dto/RecommendationResponse.java
> +    private final List<MemberResponse> unavailableMembers;
이 부분은 인수테스트에서 역직렬화할 때 오류가 날 수도 있을 것 같네요~

2022-07-27 13:46 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentStatusTest.java
> +    public void 약속잡기가_종료된_경우_true를_반환한다() {
live tempalte에 public으로 설정해놨었네요😅
전체적으로 변경했슴다~~~~~~

2022-07-27 13:50 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/ui/dto/RecommendationResponse.java
> +    private final List<MemberResponse> unavailableMembers;
NoArgsConstructor를 적용하면 final을 제거해야해서 
이부분은 일단 인수테스트 작성할 때 같이 변경할게요~~~~~😂

2022-07-27 13:51 UTC, RIANAEH commented
리차~ 코멘트 확인 후 반영했슴다!!
확인 부탁드려요🥕

2022-07-28 04:15 UTC, cjlee38 approved these changes
👍👍👍👍👍

2022-07-28 04:20 UTC, merged

2022-07-28 04:20 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        this.durationMinutes = durationMinutes;
`durationMinute`를 임베디드로 만들어서 `MINUTES_OF_HOUR` 변수, `parseHours()` 메서드, `parseMinutes()` 메서드를 갖게 하면 좋을 것 같아요 !