feat: 슬랙 API를 연동한다.
woowacourse-teams/2022-mo-rak pull request #168
Opened 2022-08-03 06:00 UTC by cjlee38

## 상세 내용
맘이 급해서 빨리 PR 날립니당
누락된 부분 마니마니 찾아주세요

Close #137

2022-08-03 06:30 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/domain/slack/SlackWebhook.java
> +    private Team team;
도메인 로직 상 @OneToOne이나 @OneToMany가 좋을 것 같아요👍

2022-08-03 06:31 UTC, RIANAEH commented on backend/src/main/resources/schema-local.sql
> +    `url`        VARCHAR(255) NOT NULL,
unique를 걸면 어떨까요?

2022-08-03 06:33 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +        Team team = teamRepository.findByCode(teamCode).orElseThrow(() -> new TeamNotFoundException(teamCode));
member가 team에 속하는지 검사하는 로직을 추가해야할 것 같아요!!👀

2022-08-03 06:36 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/domain/Menu.java
> +}
이 Menu는 알림과 관련된 기능들만 구현체가 될 수 있는 거겠죠?

2022-08-03 06:41 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/exception/WebhookNotFoundException.java
> +    public WebhookNotFoundException(Long teamId) {
개행 헤헷😜

2022-08-03 06:44 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/ui/NotificationControllerAdvice.java
> +            .body(new ExceptionResponse("API 요청을 실패했습니다."));
에러 메시지를 친절하게 바꾸면 좋을 것 같은데 뭐가 좋을지 잘 모르겠네요..🥶 
(외부 API 사용 과정에서 에러가 발생했습니다..?)ㅋㅋ

2022-08-03 06:47 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
> +        slackClient.notifyClosed(webhook, MessageFormatter.format(poll));
good~~ 사용자 입장에서 너무 편하겠네요👍

2022-08-03 06:51 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> +                                 @Param("endDateTime") LocalDateTime endDateTime);
@Param의 속성 설정에 대해 학습해봐야겠네요(혼잣말)

2022-08-03 06:53 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/MorakBackApplication.java
> +@EnableScheduling
Spring에서 제공하는 Scheduling에 대해 학습해봐야겠네요(혼잣말2)

2022-08-03 06:58 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        doNothing().when(slackWebhookRepository).deleteByTeamId(anyLong());
```suggestion
        given(teamRepository.findByCode(anyString())).willReturn(Optional.of(team));
        willDoNothing().given(slackWebhookRepository).deleteByTeamId(anyLong());
```
다른 메서드와 통일감있게 BDDMockito의 willDoNothing()을 사용하는게 어떨까요? (doNothing()은 Mockito꺼라서용👀)

2022-08-03 06:59 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        verify(slackClient, times(2)).notifyClosed(any(SlackWebhook.class), anyString());
개행 너무 불변해요👹

2022-08-03 07:42 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/core/domain/slack/FakeSlackClient.java
> +}
어디서 사용하려고 만든 객체인가요??(몰라성)

2022-08-03 09:50 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/domain/slack/SlackWebhook.java
> +    private Team team;
잘못 만들었네요 ㅎㅎ;; OneToOne으로 수정하겠습니다 ~

2022-08-03 09:51 UTC, cjlee38 commented on backend/src/main/resources/schema-local.sql
> +    `url`        VARCHAR(255) NOT NULL,
OneToOne 으로 수정하면서 반영하겠습니다 ~

2022-08-03 09:51 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +        Team team = teamRepository.findByCode(teamCode).orElseThrow(() -> new TeamNotFoundException(teamCode));
그 부분을 깜빡했네요~ 추가할께요

2022-08-03 09:51 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/domain/Menu.java
> +}
우선 알림을 주는 기능들에 대해서 만들었는데, 인터페이스의 상속관계를 가지는 것도 생각했었습니다 :)

2022-08-03 09:51 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/exception/WebhookNotFoundException.java
> +    public WebhookNotFoundException(Long teamId) {
😂

2022-08-03 09:52 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/ui/NotificationControllerAdvice.java
> +            .body(new ExceptionResponse("API 요청을 실패했습니다."));
그렇네요 ㅎㅎ 메세지를 추상화하려다보니..

2022-08-03 09:52 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
> +        slackClient.notifyClosed(webhook, MessageFormatter.format(poll));
☺️

2022-08-03 09:52 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> +                                 @Param("endDateTime") LocalDateTime endDateTime);
☺️

2022-08-03 09:52 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/MorakBackApplication.java
> +@EnableScheduling
☺️

2022-08-03 09:52 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        doNothing().when(slackWebhookRepository).deleteByTeamId(anyLong());
존재를 몰랐네요 ~ 알려주셔서 감사합니다 👍

2022-08-03 09:52 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        verify(slackClient, times(2)).notifyClosed(any(SlackWebhook.class), anyString());
😂

2022-08-03 09:57 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/domain/Menu.java
> +}
wow 역시 차리를 다 계획이 있었군요~👮‍♀️

2022-08-03 09:58 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/core/domain/slack/FakeSlackClient.java
> +}
쏘굿~ 나중에 OAuth 쪽에도 적용해봐야겠네요👩‍🌾

2022-08-04 04:43 UTC, leo0842 approved these changes
리뷰에 대한 답변은 실제 목소리로 듣겠습니다~!

2022-08-04 04:58 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +                poll -> slackWebhookRepository.findByTeamId(poll.getTeam().getId()).orElseThrow()
👍👍👍👍👍👍👍👍👍👍👍

2022-08-15 13:16 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/domain/slack/RestSlackClient.java
> +            System.out.println("e.getMessage() = " + e.getMessage());
11일만에 수정완료

2022-08-15 15:58 UTC, leo0842 approved these changes
수고 많으셨어요 차리!!
이것도 세미나 한번 열어야겠는데요 😙

2022-08-15 15:58 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +    private final SlackWebhookRepository slackWebhookRepository;
C: Appointment Service 와 Notification Service 두 군데에서 다 의존을 하고 있군요 
이게 그때 차리가 말씀해주셨던 서비스에서 서비스 의존 허용의 필요성이었나용??

2022-08-15 15:58 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +    private ExternalException closeAndNotify(Menu menu, SlackWebhook webhook) {
C: Exception 을 반환하는 건 보기 드무네요!! 이를 Propagation 으로 해결할 방법을 모색해봅시다!!

2022-08-15 15:58 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/ui/GlobalControllerAdvice.java
> +                .body(new ExceptionResponse(e.getCode().getNumber(), "스케줄링 실행 중 실패가 있습니다."));
C: 혹시 스케줄링 실행 중 실패가 있는 경우는 어떤 것들이 있는지 여쭤봐도 될까요??

2022-08-15 15:58 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/util/MessageFormatter.java
> +    public static String format(Menu menu) {
C: LogFormatter 와 성격이 유사한 느낌이 들긴 하네용 ㅠㅡㅠ

2022-08-15 15:58 UTC, leo0842 commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
> +                .orElseThrow(() -> MemberNotFoundException.of(CustomErrorCode.MEMBER_NOT_FOUND_ERROR, memberId));
C: 흐음,,?!!

2022-08-15 23:59 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +    private final SlackWebhookRepository slackWebhookRepository;
넵 맞습니다. 의존성하는 계층이 service가 추가되기도 하고, 또 너무 많은 repository를 받아오다보니 조금 못생겨졌네요 ㅠ

현재는 이렇게 가져가는데, 저번에 이야기했던 AOP, 혹은 provider, 혹은 service 의존 등에 대해서 한번 이야기해보면 좋을 것 같아요 ~

2022-08-16 00:10 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +    private ExternalException closeAndNotify(Menu menu, SlackWebhook webhook) {
이 부분에 대해서 많은 고민을 해봤는데요.. Propagation을 최종적으로 사용하지 않은 이유는 다음과 같습니다.

우선, 트랜잭션 전파를 가져가게 되면 실패한 케이스에, 메소드에서 직접 throw를 날려줘야 하는데요. (그래야 해당 inner transaction이 rollback 처리됩니다). 그렇다면 호출한쪽에서 이를 catch 해서 예외를 처리해주어야합니다.

그러면 아마 다음과 같이 생길 것 같아요
```java
// 호출하는 메소드
public void closeAndNotifyMenus(Map<Menu, SlackWebhook> menuWebhooks) {
    List<ExternalException> failedExceptions = new ArrayList<>();
    for (Entry<Menu, SlackWebhook> entry : menuWebhooks.entrySet()) {
        try {
            closeAndNotify(entry.getKey(), entry.getValue()); // API 예외시 throw
        } catch (ExternalException e) {
            failedExceptions.add(e);
        }
    }
    throwsIfAnyWebhookFailed(failedExceptions);
}
```
이렇게 가져가게되면 일단 못생겼고(ㅋㅋ), iteration 안에서 try catch를 하는 형태 자체가 괜찮은지에 대한 확신이 없어요.(stackoverflow피셜 성능상 이슈는 없다고 하네요). 게다가, 여러 요청에 대한 transactional이 과연 성능상 얼마나 이슈가 될까에 대한 의문도 있구요. 

그래서 조금 불편함을 감수하더라도 null 또는 exception을 반환하도록 했는데요. 사실 이 부분도 그렇게 마음에 들진 않아서, 다른 좋은 방법을 찾아봐야할 것 같아요 ㅠ

2022-08-16 00:12 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/ui/GlobalControllerAdvice.java
> +                .body(new ExceptionResponse(e.getCode().getNumber(), "스케줄링 실행 중 실패가 있습니다."));
ExternalException이랑 엮여있는데, 이 ExternalExceptio은 현재까지 두 가지 케이스가 있습니다!

하나는 URL 자체가 잘못된 경우, 다른 하나는 요청 결과가 200이 아닌 경우입니다. 스케줄링을 할 떄는 여러 개의 요청에 대해서 처리를 해야 하고, 중간에 오류(ExternalException)가 발생하더라도 계속 진행되어야 하기 때문에, 리스트로 모아놓은 뒤, 하나라도 예외가 있다면 SchedulingException 을 터트리고, 모락 슬랙의 error-log로 찍히도록 `logger.error` 로 처리하였습니다~

2022-08-16 00:13 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/util/MessageFormatter.java
> +    public static String format(Menu menu) {
그렇네요.. 이 부분은 필요하다면 Format 양식과 Formatter를 구분하는 방식으로 바꿀수도 있겠어요.

2022-08-16 00:14 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
> +                .orElseThrow(() -> MemberNotFoundException.of(CustomErrorCode.MEMBER_NOT_FOUND_ERROR, memberId));
이전에 continuation indent가 4로 맞춰져 있다가, 다시 8로 바뀌어서 그런 것 같아요 !

![image](https://user-images.githubusercontent.com/52564093/184757216-ab26dc34-3690-4fc7-b2c1-0b085315a174.png)

2022-08-16 05:15 UTC, RIANAEH approved these changes
슬랙 API 로직 이해하기 벅차네요🥲
일단 리뷰 남겼지만 더 살펴보겠습니다!!

2022-08-16 05:15 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/domain/slack/SlackWebhook.java
> +    @URL(regexp = "https://hooks.slack.com/services/.*", message = "웹훅 URL 은 http로 시작해야 합니다.")
C: `NotBlank`에도 메시지가 있어야하지 않나요?

2022-08-16 05:15 UTC, RIANAEH commented on backend/src/test/java/com/morak/external/RestSlackClientTest.java
> +        assertThatNoException().isThrownBy(() -> client.notifyClosed(webhook, "test-in-backend-test-code"));
R: 개행!!

2022-08-16 08:52 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +                .ifPresent(webhook -> slackClient.notifyClosed(webhook, MessageFormatter.format(appointment)));
good idea. 반영했습니다.

2022-08-16 08:53 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +                        appointment -> slackWebhookRepository.findByTeamId(appointment.getTeam().getId()).orElseThrow()
생각해보니까 예외를 던지면 안될 것 같아요! 슬랙 URL은 없을수도 있으니까요.
그래서 Optional로 감쌌는데, collection에 optional을 담는건 금기사항인데 ㅠ.ㅠ ... 눈물을 머금고 일단 작성했습니다.

2022-08-16 08:53 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +    }
private으로 하면 에러가나용 ㅠ. 아마 상속가능하도록 만들어야 하나봐요 (리플렉션이 아닌것같아요)

2022-08-16 08:54 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
> +                                        @Param("endDateTime") LocalDateTime endDateTime);
그래서 지금 테스트는 data.sql을 기반으로 돌아갑니다! 그런데 저렇게 모두 적어주는게 괜찮을지는 모르겠네요. 엘리는 저렇게 적는게 더 좋으신가요 ?

2022-08-16 08:54 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +        SlackWebhook savedWebhook = slackWebhookRepository.save(
넵 맞습니다 !

2022-08-16 08:55 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/domain/slack/SlackWebhook.java
> +    @URL(regexp = "https://hooks.slack.com/services/.*", message = "웹훅 URL 은 http로 시작해야 합니다.")
넵 수정했습니다 ~

2022-08-16 08:55 UTC, cjlee38 commented on backend/src/test/java/com/morak/external/RestSlackClientTest.java
> +        assertThatNoException().isThrownBy(() -> client.notifyClosed(webhook, "test-in-backend-test-code"));
확인했습니다 감사합니당

2022-08-16 09:17 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +    }
스케줄링에 대한 학습📚이 필요하군요! (혼잣말)

2022-08-16 10:53 UTC, RIANAEH requested changes
몇가지 리뷰 남겨봤어요~

2022-08-16 10:53 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
> +    private final SlackClient slackClient;
R: 둘 다 안쓰고 있는것 같아요!!

2022-08-16 10:53 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
>      public String createPoll(String teamCode, Long memberId, PollCreateRequest request) {
R: 투표에도 생성 시 알림 기능을 추가해야할 것 같네요!!

```java
Poll savedPoll = pollRepository.save(poll);
notificationService.notifyMenuStatus(team, savedPoll, MessageFormatter::formatOpen);
return savedPoll.getCode();
```

2022-08-17 02:51 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +                new NotificationService(slackClient, teamRepository, teamMemberRepository, slackWebhookRepository);
👍

2022-08-17 02:52 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        ).getMember();
👍

2022-08-17 02:52 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
> +    private final SlackClient slackClient;
👍

2022-08-17 02:55 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
>      public String createPoll(String teamCode, Long memberId, PollCreateRequest request) {
👍

2022-08-17 02:56 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
> +                                        @Param("endDateTime") LocalDateTime endDateTime);
좋은 생각이네요 ~ 하지만 OPEN 이라는 문자열이 DB에 저장된다는 점을 감안하면 이대로 가도 괜찮지 않을까 싶어요! 만약 enum이 OPEN이 아닌 다른 이름으로 변경된다면 DB 자체에 저장되어있던 OPEN이라는 모든 값을 수정해줘야 하는 상황이니까요~

2022-08-17 07:16 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentScheduler.java
> +    @Scheduled(cron = "0 0/1 * * * ?")
https://zamezzz.tistory.com/197

부가설명이 필요하면 말씀해주세요

2022-08-17 07:16 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +    private Map<Menu, Optional<SlackWebhook>> joinAppointmentsWithWebHooks(List<Appointment> appointmentsToBeClosed) {
로직변경 후 삭제되었습니다~

2022-08-17 07:16 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +    public void closeAndNotifyMenusByScheduled(Map<Menu, Optional<SlackWebhook>> menuWebhooks) {
로직변경 후 삭제되었습니다~

2022-08-17 07:16 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/util/MessageFormatter.java
> +                "투표하러 가기 ! -> https://mo-rak.com/groups/%s/poll/%s/progress",
매의눈 👀 수정했습니다~

2022-08-17 07:20 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/util/MessageFormatter.java
> +                "투표결과 확인하러 가기 ! -> https://mo-rak.com/groups/%s/poll/%s/result",
👍

2022-08-17 07:20 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/domain/slack/SlackClient.java
> +    void notifyClosed(SlackWebhook webhook, String message);
매의눈 👀 수정했습니다~

2022-08-17 07:20 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        Map<Menu, Optional<SlackWebhook>> appointmentWebHooks = joinAppointmentsWithWebHooks(appointmentsToBeClosed);
로직변경 후 삭제되었습니다~

2022-08-17 07:20 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +                .filter(Optional::isPresent)
로직변경 후 삭제되었습니다~

2022-08-17 07:44 UTC, seong-wooo approved these changes
훨씬 깔끔해졌네요 ~

2022-08-17 07:44 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        System.out.println("message = " + message); // remained to debug
지워도 될 듯 합니다 ~

2022-08-17 07:47 UTC, RIANAEH approved these changes
ㅎㅎ 이제 슬랙 알림을 제공할 수 있겠네요!! 너무 좋아요😄

2022-08-17 07:47 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        }
A: ㅋㅋㅋㅋㅋ DB로 바로 쏘니 깔끔해졌네요🤣

2022-08-17 07:47 UTC, RIANAEH commented on backend/src/main/resources/application.yml
> +        transaction.interceptor: TRACE
C: 모든 환경 local, dev, prd에서 transaction 관련 정보를 모두 로깅하나요..?

2022-08-17 07:47 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        System.out.println("message = " + message); // remained to debug
C: 남겨놓는건가요?

2022-08-17 07:47 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
> +    void closeById(@Param("id") Long id);
C: `Transactional`, `Modifying`을 빼고 돌려도 테스트는 모두 통과하더라구요. 넣어준 이유가 궁금해요!!

2022-08-17 08:36 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        System.out.println("message = " + message); // remained to debug
남기면 안될까요 ㅎㅎ;

2022-08-17 08:36 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        }
👍

2022-08-17 08:39 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
> +    void closeById(@Param("id") Long id);
테스트에서는 `@DataJpaTest` 안에 `@Transactional` 어노테이션이 들어있기 때문에 트랜잭션 내부에서 동작합니다. Scheduled 는 별도 스레드에서 동작하기 때문에 `@Transactional`이 없고, 따라서 트랜잭션이 없기 때문에 트랜잭션을 만들어줘야 데이터를 변경할 수 있습니다.

2022-08-17 08:39 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        System.out.println("message = " + message); // remained to debug
넹. 남기면 안될까요 ㅎㅎ;

2022-08-17 08:42 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
> +        System.out.println("message = " + message); // remained to debug
찰이 원하는대로~

2022-08-17 08:42 UTC, cjlee38 commented on backend/src/main/resources/application.yml
> +        transaction.interceptor: TRACE
local에서만 찍힙니당

2022-08-18 02:10 UTC, RIANAEH approved these changes
굿!! 빠르게 잘 구현해주셨네요👍 역시 리차~

2022-08-18 02:10 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        notificationService.notifyMenuStatus(team, MessageFormatter.formatOpen(FormattableData.from(appointment)));
C: 메서드 명을 바꿔보면 좋을 것 같아요!! (좀 더 범용적으로)

2022-08-18 02:10 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/util/MessageFormatter.java
>      }
C: 통일성을 위해 lombok으로 바꾸면 좋을 것 같아요!!

2022-08-18 02:32 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/MorakBackApplication.java
> -
👍

2022-08-18 02:32 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        notificationService.notifyMenuStatus(team, MessageFormatter.formatOpen(FormattableData.from(appointment)));
👍

2022-08-18 02:32 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/util/MessageFormatter.java
>      }
👍

2022-08-18 02:32 UTC, merged