feat: jacoco 설정
woowacourse-teams/2022-mo-rak pull request #224
Opened 2022-08-11 10:02 UTC by leo0842

## 상세 내용

jacoco 설정을 추가했습니다.

Close #223

2022-08-11 10:05 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-13 16:15 UTC, cjlee38 approved these changes
build.gradle이랑 lombok.config에 알수없는 코드들이 많이 생겼네요.. 고생하셨겠어요 😂

2022-08-13 16:15 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/Generated.java
> +}
c: Generated가 어떤 역할인지 설명해주세요! `@Documeted` 어노테이션은 관련해서 이런 내용밖에 안보이네요 ㅠ 
https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/Documented.html

2022-08-13 19:23 UTC, RIANAEH requested changes
덴에~ 자코코 적용해주시느라 고생 많았습니다👍

build.gradle에 주석이 많은데 이에 대한 설명이나 주석은 개발 일지로 이동시키면 좋을 것 같아요👀
세부적인 설정은 다 같이 이야기해봅시다!!

2022-08-13 19:23 UTC, RIANAEH commented on backend/build.gradle
> +            }
R: 오 이렇게 세부적으로 설정할 수 있었군요!! 커버리지 기준을 어떻게 가져갈지 다 같이 이야기해보면 좋겠네요👍

2022-08-13 19:23 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/support/Generated.java
> +import java.lang.annotation.ElementType;
R: 불필요한 import 쓱싹!

2022-08-13 19:23 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/support/Generated.java
> +}
C: 이와 관련해서 롬복에 `lombok.addLombokGeneratedAnnotation = true` 설정을 추가해주셨는데 Jacoco와 어떤 관련이 있는건가요?? 설명이 필요합니다!!

2022-08-14 13:55 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/support/Generated.java
> +}
모두 개발 일지에 적어놓겠습니다!!!!

2022-08-14 13:55 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/support/Generated.java
> +import java.lang.annotation.ElementType;
sorry very sorry

2022-08-14 13:56 UTC, leo0842 commented on backend/build.gradle
> +                minimum = 0.40
지당합니다

2022-08-15 01:29 UTC, seong-wooo approved these changes
jacoco 설정 및 테스트 추가까지 하셨네요.
덕분에 더 좋은 서비스가 될 것 같아요 ~

2022-08-15 06:08 UTC, RIANAEH approved these changes
고생많으셨어요💯
경로에 docs만 넣어서 머지 가시죠~

2022-08-15 06:08 UTC, RIANAEH commented on backend/build.gradle
> +    into file("src/main/resources/static")
R: 헤이~

2022-08-15 06:08 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTime.java
>      public boolean equals(Object o) {
C: 나중에 어떻게 없앨지 고민해봅시당

2022-08-15 06:11 UTC, merged