refactor: 약속잡기의 버그를 수정하고 테스트를 추가한다.
woowacourse-teams/2022-mo-rak pull request #230
Opened 2022-08-11 11:01 UTC by cjlee38

## 상세 내용

#204 PR이 아직 머지되지 않아서 우선적으로 PR 보냅니다.

[refactor(appointment): closedAt 임시 로직을 DTO로 이동](https://github.com/woowacourse-teams/2022-mo-rak/commit/1391ad2f15a70c633092f0183c46705c69ee133f)

여기서부터 보시면 됩니다.

Close #215

2022-08-11 11:05 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-12 03:05 UTC, leo0842 commented on backend/src/main/java/com/morak/back/appointment/domain/DateTimePeriod.java
> +                    "약속잡기 가능 시간(%s~%s)은 " + minutesUnit + "분이어야 합니다.",
R: String format 으로 하셨는데 concat 도 하시네용!! ㅎ-ㅎ

2022-08-12 03:07 UTC, RIANAEH requested changes
리차~ 고생이 많아용ㅠㅠ
몇가지 코멘트 남겼으니 확인해주세요🐨

2022-08-12 03:07 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/exception/CustomErrorCode.java
> +    EMPTY_AUTHORIZATION_ERROR("0203", "사용자 인증에 실패했습니다."),
C: 다른 곳은 에러 메시지가 서로 다른데 여기만 통일하신 이유가 있나요?

2022-08-12 08:11 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/DateTimePeriod.java
> +                    "약속잡기 가능 시간(%s~%s)은 " + minutesUnit + "분이어야 합니다.",
띠용; 수정했습니다.

2022-08-12 08:18 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +
혹시 getter 메소드 & 로직 메소드의 순서때문에 말씀하신걸까요 ? `getFirstStartDateTime` 과 `getLastEndDateTime` 는 로직 메소드라고 생각해서 위쪽으로 두었던 것 같아요. 그런데 property 관점에서 보면 단순 getter로도 볼 수도 있어서 밑으로 내렸습니다~

2022-08-12 08:18 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentTest.java
> +    void durationMinutes객체의_시간의_시을_얻어온다() {
😅

2022-08-12 08:19 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/TimePeriod.java
>  public class TimePeriod {
로깅 목적입니다~

2022-08-12 08:19 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +                null);
수정했습니다 ㅎㅎ;

2022-08-12 08:32 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/AvailableTimeRepositoryTest.java
>  class AvailableTimeRepositoryTest {
롤백은 수행되지만 auto_increment는 롤백되지 않아서요~ 

현재 data.sql에 의존하는 부분이 꽤 있어서 id 값을 직접 확인하는 경우도 종종 있어요.
(`@ServiceTest`와 `@RepositoryTest` 에서 `Sql` 어노테이션을 떼면 모두 통과하긴 합니다.)

해당 부분을 안정적으로 수행하려면 특정 ID값에 의존하지 않도록 전반적으로 수정하는(e.g. data.sql 제거) 과정이 필요할 것 같습니다.

2022-08-12 08:36 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/RecommendationCellsTest.java
> +    private Member memberB;
계속 수정하면서 하다보니 많이 놓쳤네요.. 수정했습니다 !

2022-08-12 09:24 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/exception/CustomErrorCode.java
> +    EMPTY_AUTHORIZATION_ERROR("0203", "사용자 인증에 실패했습니다."),
실수입니다 :)

2022-08-13 10:32 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> +        //given(teamRepository.findIdByCode(anyString())).willReturn(Optional.of(모락.getId()));
R. 주석 지워주세욥

2022-08-13 10:32 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> +    private static AppointmentBuilder DEFAULT_BUILDER;
A. static 변수여야하는 이유가 뭘까요?

2022-08-13 10:32 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentTest.java
> +    // TODO: 2022/07/28 AvailableTime 추가 후 테스트 필요!!
R. 주석 지워주세요

2022-08-13 10:32 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/domain/AvailableTimeTest.java
> +                .closedAt(LocalDateTime.now().plusDays(1))
R. 똑같은 것이 2줄이네요 지워주세요~

2022-08-13 13:22 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    private void validateClosedAtBeforeEndDate(LocalDateTime closedAt, DatePeriod datePeriod) {
굿!

2022-08-13 13:23 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        validateLastDatetime(endDate, endTime);
그렇네요 ! 놓친 부분 지적 감사합니다 :)

2022-08-13 13:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTime.java
> +        LocalTime localTime = createDataTimePeriod.getEndDateTime().toLocalTime().withSecond(0).withNano(0);
처음에는 요청데이터가 분 하위 단위의 요청이 들어올수도 있을 것 같다고 생각해서(e.g. POSTMAN) 이렇게 만들었는데, 타고 들어가다보니 `JsonFormat` 에서 분단위까지 걸러주고 있네요 ! 없애는 게 좋을 것 같습니다 ~

2022-08-13 13:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTime.java
> +    private void validateDateRange(Appointment appointment, DateTimePeriod createDataTimePeriod) {
매의눈이시군요 ㅎㅎ

create는 의식의 흐름대로 구분하는 느낌을 주려고 썼었던건데, 깜빡하고 새로 추가한 부분만 썼네요. 다른 부분도 추가하겠습니다 👍

2022-08-13 13:36 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/DatePeriod.java
> +    public boolean isInRange(LocalDate otherDate) {
그렇네요 ~그런데 읽어보니 `isInRange` 는 '기간' 중 '특정 날짜'가 포함되는지를 물어보는데, `DateTimePeriod`의 `contains`는 '기간' 내에 다른 '기간' 이 포함되는지를 물어보는 메소드네요. 대신 DatePeriod의 `isAvailableRange` 가 이와 대응해서 '기간' 내에 다른 '기간'이 포함되는지 물어보구요..

즉, DatePeriod `isInRange` vs DateTimePeriod `contains` 가 아닌, DatePeriod `isAvailableRange` vs DateTimePeriod `contains` 가 될 것 같아요 ~

`contains`는 `JCF` 에서 통용적으로 사용되는 메소드명이다보니, `isAvailableRange`가 나을 것 같다고 생각해서 수정했습니다~

2022-08-13 13:38 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/TimePeriod.java
>      // TODO : minutesUnit. 상수인가, 변수인가
저도 동의하는 입장입니다~ 다만, 지금 MINUTES_UNIT이 Appointment 내에서 전역적으로 사용되며 의존하고 있는 상태라, 이 부분은 별도의 이슈로 빼서 팀 회의 후 다시 수정해보는 방향으로 가면 좋을 것 같아요 !

2022-08-13 14:11 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/AvailableTimeRepositoryTest.java
>  class AvailableTimeRepositoryTest {
아하 auto_increment 때문이었군요!! (까먹고 있었네요ㅎㅎ)

2022-08-13 15:03 UTC, RIANAEH requested changes
리차 리뷰 많이 반영해주셨네요!!👍
아직 남아있는 주석이 몇개 있어서 이 부분 수정해주세요~

2022-08-13 15:03 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        entityManager.refresh(appointment);
C: 왜 refresh()를 해야하는지 설명해주실 수 있나요? 
R: 위에 주석 쓱싹!!

2022-08-13 15:03 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>      private Integer count;
C: 지연 로딩이 걸리나요? 저도 이전에 적용해보고 싶었는데 실패했었어서요!!🥲

2022-08-13 15:13 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        validateClosedAtBeforeEndDate(closedAt, datePeriod);
그렇네요.. 반영했습니다 !

근데 보다보니까 검증로직이 너무 길어서 갈아엎고 싶은 마음이 굴뚝같은데 🌋 어떻게 바꿔야할지 모르겠네요.. ㅠ

2022-08-13 15:19 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>      }
오, 그렇네요 ! DatePeriod에서 이와 관련한 로직을 이미 검증하고 있긴 하지만, 지금 이렇게 해버리면 해당 로직에 의존하는 셈이 되버리니, 고치는게 더 나을 것 같네요 ! 좋은 지적 감사합니다 👍

2022-08-13 15:25 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>      }
맞습니다 ! 그래서 `AvailableTime` 의 검증 로직을 보면 다음과 같은데요.

```java
if (!appointment.isAvailableDateRange(createDateTimePeriod.toDatePeriod(createLocalTime))) {
 ...
}
```

여기서 `createDateTimePeriod.toDatePeriod(createLocalTime)` 를 보면 local time을 넣어주고 있는데요. 
해당 메소드를 살펴보면

```java
public DatePeriod toDatePeriod(LocalTime localTime) {
      LocalDate endDate = endDateTime.toLocalDate();
      if (localTime.equals(LocalTime.MIDNIGHT)) {
          endDate = endDate.minusDays(1);
      }
      return new DatePeriod(startDateTime.toLocalDate(), endDate);
  }
```

이렇게 AvailableTime이 midnight라면 하루 빼주는 연산을 해주고 있습니다. 
그래서 말씀해주신 예시인 `2022.08.09 23:30-2022.08.10 00:00` 가 들어오면, endDate가 9일과 9일로 비교하게 됩니다.

"어 그렇다면 둘다 안빼주면 안되나요?" 라고 할 수도 있는데, 그렇게 된다면
`2022.08.10 00:00 ~ 2022.08.10 00:30` 과 같은 요청이 통과하기 때문에 (날짜상으로는 10일과 10일을 비교하는 셈이니, OK로 쳐주니까요) 위와 같이 구성되었습니다. :)

2022-08-13 15:26 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/RecommendationCell.java
> +        if (this.dateTimePeriod.isAvailableRange(availableTime.getDateTimePeriod())) {
이런 녀석이 있었군요; 감사합니다.

2022-08-13 15:36 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +    }
넵. methodsource는 순서가 `BeforeEach`보다 우선입니다. (sout으로 확인)

따라서 DEFAULT_BUILDER를 선언할 때 초기화를 하더라도, MethodSource를 가져올때 null이 되어버리니 다른 테스트에서 깨지는 문제가 발생합니다. (

\+ inline으로 만들려고 했는데, 그러면 컴파일러가 인식을 못하네요 ㅠㅠ

2022-08-13 15:55 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        entityManager.refresh(appointment);
```java
/**
     * Refresh the state of the instance from the database, 
     * overwriting changes made to the entity, if any. 
     * @param entity  entity instance
     * @throws IllegalArgumentException if the instance is not
     *         an entity or the entity is not managed
     * @throws TransactionRequiredException if there is no
     *         transaction when invoked on a container-managed
     *         entity manager of type <code>PersistenceContextType.TRANSACTION</code>
     * @throws EntityNotFoundException if the entity no longer
     *         exists in the database
     */   
```

설명하는 내용은 추측입니다~ entity를 영속성 컨텍스트에 저장하고나서, findByCode를 하면 JPQL 사용으로 인해 flush 까지는 나갑니다. 그리고 나서 보면 findByCode 의 select 쿼리까지는 나가는걸 확인할 수 있는데요. 이 select 쿼리 결과가, 'appointment가 이미 영속성 컨텍스트에 존재하기 때문에' 쿼리 결과를 그냥 버리는 것 같아요 !

그래서 `refresh`를 통해 해당 객체를 다시 쿼리해서 가져오도록 처리했습니다. 말씀주시고나서 다시 살펴보니, select 쿼리가 총 두번이 나가는데요. refresh에서 한번, findByCode에서 한번 이렇게 총 두번을 수행하고 있었습니다. 그런데 생각해보니 "영속성 컨텍스트에 존재"하는게 문제라면 영속성 컨텍스트에서 제거하면 되지 않을까요 ?

그래서 refresh 대신에 detach를 사용해봤더니 쿼리도 한번만 나가고, 테스트 결과도 잘 동작하는 것을 확인할 수 있었습니다. 덕분에 다시 공부했네요. 감사합니다 엘리 !

2022-08-13 15:58 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>      private Integer count;
관련해서 찾아봤는데, hibernate 자체에서는 지원을 해주지만, 이를 컴파일하는 build tool이 연관되어 있는 것 같아요. maven이나 ant같은 경우에는 설정하는 방법이 있고, gradle에서도 이를 지원해주긴 하는데 ([관련 문서](https://docs.jboss.org/hibernate/orm/5.5/userguide/html_single/Hibernate_User_Guide.html#BytecodeEnhancement-enhancement)) , 'Lazy로 과연 걸어야 할까?'에 대한 것도 있고, Lazy로 걸기 위해서 build.gradle을 제 독단으로 수정하면 문제가 될 수 있을 것 같아 우선 해당 어노테이션을 제거하기로 결정했습니다 !

2022-08-13 16:32 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        validateClosedAtBeforeEndDate(closedAt, datePeriod);
`validateDurationMinutesLessThanTimePeriod(this.durationMinutes, this.timePeriod);` 부분 외의 다른 부분은 들어오는 파라미터에 대해서만 검증을 진행하면 돼서 생성자의 상위에 모아놔도 될것같아요.. 
검증로직.. 지금 시간에 대한 검증 로직이 너무 많고 산재해 있어서 저도 엎어버리고 싶은 마음이 한가득입니다🥺

2022-08-13 16:38 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>      }
아하!! endtime이 정각일 경우 Appointment와 AvailableTime 모두의 enddate를 하루씩 빼는 구조였군요!! 
차리의 친절한 설명 덕분에 로직을 이해할 수 있었네요👍 쌩유!!

2022-08-13 16:39 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +    }
덕분에 많이 배워갑니다🙇‍♀️

2022-08-13 16:43 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        entityManager.refresh(appointment);
아하!! 이미 처음에 appointment가 영속성 컨텍스트에 저장 돼 `findByCode` 시 DB에서 데이터를 불러오는게 아니라 영속성 컨텍스트의 appointment를 불러와 formular가 적용되지 않는게 문제였군요!! JPA는 참 까도까도 새로운게 나오네요🧅

2022-08-13 16:46 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>      private Integer count;
맞아요 이전에 적용해보려고 할 때 gradle에 설정을 해줘야해서 "이런 설정까지 해줘서까지 지연 로딩을 걸어야할까?"해서 저도 반영하지는 않았었어요(기억에 설정을 추가해도 지연 로딩이 안 걸렸던 것 같아요)

이 부분은 다같이 이야기해보면 좋을 것 같네요👍

2022-08-13 16:54 UTC, RIANAEH requested changes
차리!! 리뷰 너무 잘 반영해주셨네요👍
약속잡기 마감시간만 한번 더 확인해주세요!! (차리를 너무 귀찮게 하는 것 같아 미안하네요😅)

불필요한 import도 한번 더 확인해주세요~ (소나큐브 은근 쓸모있을지도?)
<img width="884" alt="image" src="https://user-images.githubusercontent.com/45311765/184503577-089bef01-186d-4db9-abab-a506f862df4c.png">

2022-08-13 16:54 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>          }
R: closedAt의 date뿐만아니라 time도 검증해야하지 않을까요? 
`생성하는 날짜 + 시각`보다 이전일 경우와 `약속잡기의 마지막 날짜 + 마지막 시간`보다 이후일 경우에도 예외가 터져야할것같아요!!

2022-08-14 05:11 UTC, RIANAEH approved these changes
차리 고생 많았어요💯

2022-08-14 05:12 UTC, seong-wooo approved these changes

2022-08-14 05:23 UTC, merged