feat: 투표 마감시간 기능 구현
woowacourse-teams/2022-mo-rak pull request #242
Opened 2022-08-13 12:37 UTC by al-bur

## 상세 내용

- [x] 투표 메인페이지에서 마감시간을 보여주도록 구현했습니다.
- [x] 투표 생성페이지에서 마감시간을 입력할 수 있도록 구현했습니다.
- [x] 투표 결과페이지에서 마감시간을 보여주도록 구현했습니다.

Close #239

2022-08-13 12:37 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-13 13:45 UTC, rladpwl0512 requested changes
앨버! 코드 잘 봤습니다~!🐝 
역시 앨버는 코드도 깔쌈하네요~ 보면서 감탄했습니다 ✨ 
몇가지 간단한 리뷰 남겼으니 확인해주세요~

2022-08-13 13:45 UTC, rladpwl0512 commented on frontend/src/components/PollCreate/PollCreateForm/PollCreateForm.tsx
> +  const [closeDate, handleCloseDate] = useInput('');
`close`, `closed` 둘 중 하나로 통일하는게 좋지 않을까요? 혹시 여기서는 close라고 한 이유가 있을까요~🤔

2022-08-13 13:45 UTC, rladpwl0512 commented on frontend/src/components/PollMain/PollMainDetail/PollMainDetail.tsx
> +interface Props extends Pick<PollInterface, 'isAnonymous' | 'allowedPollCount' | 'closedAt'> {}
오...! 배워갑니다~👏👏

2022-08-13 13:45 UTC, rladpwl0512 commented on frontend/src/components/PollMain/PollMainDetail/PollMainDetail.tsx
> +};
오 이코드는 무슨 코드인가요? 😮 궁금 궁금

2022-08-13 13:45 UTC, rladpwl0512 commented on frontend/src/components/PollMain/PollMainDetail/PollMainDetail.tsx
> +        까지
여기도 `ClosedTime`으로 하면 좋지 않을까요? `getFormattedClosedTime`과 맞춰서요~

2022-08-14 03:55 UTC, al-bur commented on frontend/src/components/PollMain/PollMainDetail/PollMainDetail.tsx
> +};
오전 오후를 표현하기위해 date 객체의 메서드를 활용해주었습니다!!
이 방법 좋더라구요~ 프로젝트 전반적으로 date 객체를 잘 활용할 수 있도록 리팩토링 해봐도 좋을 것 같습니다

2022-08-14 03:58 UTC, al-bur commented on frontend/src/components/PollCreate/PollCreateForm/PollCreateForm.tsx
> +  const [closeDate, handleCloseDate] = useInput('');
맞네요 현재 통일이 안되어 있군요

저번에 약속잡기 기능을 구현했을때 저희가 close를 사용했어서 일관성있게 사용을 했었는데,
지금 보니 둘 다 아닌 것 같네요..

closingTime 어떤가요?? 식당 문 닫히는 것 같은 경우를 closingTime이라고 하나봐요

2022-08-14 03:59 UTC, al-bur commented on frontend/src/components/PollMain/PollMainDetail/PollMainDetail.tsx
> +        까지
좋습니다~

2022-08-14 04:36 UTC, rladpwl0512 commented on frontend/src/components/PollCreate/PollCreateForm/PollCreateForm.tsx
> +  const [closeDate, handleCloseDate] = useInput('');
오 `closing` 좋습니다~!! 👍👍

2022-08-14 04:49 UTC, al-bur commented on frontend/src/components/PollCreate/PollCreateForm/PollCreateForm.tsx
> +  const [closeDate, handleCloseDate] = useInput('');
수정하였습니다.

cb4fb0f

2022-08-14 04:53 UTC, rladpwl0512 approved these changes
구현하느라 고생하셨습니다~ 리뷰 반영도 확인했어요! 
approve 하겠습니다!

2022-08-14 06:18 UTC, merged