feat: 약속잡기 마감시간 기능 구현
woowacourse-teams/2022-mo-rak pull request #243
Opened 2022-08-14 06:21 UTC by al-bur

## 상세 내용

- 약속잡기 생성 페이지에서 마감시간을 설정할 수 있도록 구현하였습니다.
- 약속잡기 진행 페이지에서 마감시간을 볼 수 있도록 구현하였습니다.

## 특이사항
- 약속잡기 메인 페이지는 현재 branch에서 구현되어 있지않아 추후에 작업할 예정입니다.

Close #{이슈_번호}

2022-08-14 13:07 UTC, rladpwl0512 requested changes
앨버 리뷰남겼습니다~ 
깔끔하게 작성해주셔서 이해하기 쉬웠고, 딱히 피드백 드릴게 없네요 👍
몇가지 자잘자잘한 커멘트 남겼으니 확인해주셔요 🐝

2022-08-14 13:07 UTC, rladpwl0512 commented on frontend/src/components/AppointmentProgress/AppointmentProgressDetail/AppointmentProgressDetail.tsx
> +  font-size: 1.8rem;
4 단위에 맞춰주면 좋을 것 같아요~!!

2022-08-15 05:56 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-15 05:57 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressDetail/AppointmentProgressDetail.tsx
> +  font-size: 1.8rem;
수정하였습니다

[c14fe6b](https://github.com/woowacourse-teams/2022-mo-rak/pull/243/commits/c14fe6b7fb6289426c665333ca2741d7ce8379b9)

2022-08-15 06:08 UTC, rladpwl0512 approved these changes
수고하셨습니다~ 리뷰 반영 확인했습니다. 
approve 하겠습니다 :)

2022-08-15 08:16 UTC, merged