feat(core): 존재하지 않는 API 요청 시 커스텀 예외 응답
woowacourse-teams/2022-mo-rak pull request #247
Opened 2022-08-14 09:40 UTC by seong-wooo

## 상세 내용
프론트 측에서 존재하지 않는 API에 요청을 보내면 404가 반환되는데,
이때 우리의 CustomErrorCode를 던지도록 하였습니다.
기존에 MemberNotFoundException 등등 404로 응답되는 경우가 많잖아요 ~
이제 이런 것들을 CustomeErrorCode로 구분해봅시다 ~

Close #244

2022-08-14 09:45 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-14 09:51 UTC, leo0842 approved these changes
호다닥 끝내버리셨네요 💯

2022-08-14 09:51 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/config/WebConfig.java
> +                .addResourceLocations("classpath:/static/docs/");
C: 혹시 /docs/index.html 로 API 명세 조회가 안되던게 이거 때문이었나요?? 😭

2022-08-14 09:51 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/exception/CustomErrorCode.java
> -
C: 혹시 왜 지우셨는지 알 수 있을까요?? enum 정의한 객체랑 인스턴스 변수는 분리하는 게 조금 더 가독성이 좋을 것 같아서요!

2022-08-14 12:30 UTC, cjlee38 approved these changes
군더더기 없이 깔끔하네요 👍 관련해서 노션에 적어주면 완벽할듯 🤭

2022-08-14 13:02 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/config/WebConfig.java
> +                .addResourceLocations("classpath:/static/docs/");
아닙니다 ~ 아마 이건 dev 서버에서 index.html이 존재하는 지 확인해봐야할 것 같아요

2022-08-14 13:03 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/exception/CustomErrorCode.java
> -
실수로 지웠네요 ~ 수정하겠습니다

2022-08-15 04:30 UTC, RIANAEH requested changes
빨리 구현해주셨네요💯

공백만 지워주시면 될 것 같아요~

2022-08-15 04:30 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/config/WebConfig.java
> +                .addResourceLocations("classpath:/static/docs/");
C: 까라 로컬에서는 저 설정을 하면 index.html에 접속 가능했나요?

2022-08-15 04:30 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/ui/GlobalControllerAdvice.java
> +
R: 공백 쓱싹!

2022-08-15 06:10 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/ui/GlobalControllerAdvice.java
> +
반영했습니다 ~ 로컬에서 index.html 접속 가능했습니다 !

2022-08-15 06:12 UTC, RIANAEH approved these changes
반영확인했습니다~~

2022-08-15 06:24 UTC, merged