feat: 사이드바 구현
woowacourse-teams/2022-mo-rak pull request #252
Opened 2022-08-14 12:49 UTC by rladpwl0512

사이드바 pr 날리는데 너무 오래걸렸네요... 🤯 
내일까지 달려보겠습니다 🏃🏻‍♀️ 

## 상세 내용
## (필수) 구현할 기능에 명시한다.
- [x] 피그마 작업
- [x] 사이드바 (그룹 참가, 그룹생성, 기능 메뉴, 그룹 삭제 메뉴 추가)
  - [x] UI 구현
  - [x] 도메인 로직 구현 (api와 연결) 
  - [x] (약간의) 애니메이션 
  - [x] 컴포넌트 추상화 

## 논의가 필요한 부분 
- sidebar에 대한 component 폴더를 만드는게 좋을까요? 
현재 Sidebar는 page가 아니라서 폴더로 만들어서 묶어주지 않고, 그냥 component 폴더 내부에 모두 추상화된 컴포넌트들이 나누어져있습니다. 논의가 필요합니다 🤔 
- 그룹 멤버수를 알면 좋을 것 같아서 넣었는데, 목록을 조회 api에서는 그룹 멤버수를 알 수 없어서 그룹 하나씩 그룹멤버조회 api를 호출해야할 것 같은데, 이 방식이 괜찮을까요? 🤔 (현재는 논의 후 구현해야할 것 같아서, 작성한 방식대로 api 연결하지 않았습니다.)
- 그룹 참가, 생성, 삭제에 대한 메뉴는 만들어주었으나 기능은 구현하지 않았습니다. 삭제는 모달창으로, 생성 및 참가는 페이지를 따로 만들어줘야할 것 같아서 따로 pr을 날리는 것이 좋을 것 같습니다. 
- `useOutletContext`에 대해 any타입으로 임시 지정해주었습니다. (일지 참고해주세요 🤯)

Close #222

2022-08-14 12:49 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-14 18:40 UTC, rladpwl0512 commented
슬랙 채널 연동 메뉴도 추가했습니다. 
[feat(sidebar): 슬랙 채널 연동 메뉴 구현](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/a2e782f9f811e983916cf4d9071f7b5e3c63d69e)

2022-08-15 07:05 UTC, al-bur requested changes
너무 고생하셨어요~~~~
일단, 시간이 없으니 필수인 부분(🎉)만 고쳐봐주세요

2022-08-15 07:07 UTC, al-bur commented on frontend/src/components/SidebarLayout/SidebarLayout.tsx
> +  const handleSetClickedMenu = (menu: string) => () => {
🎉

2022-08-15 07:13 UTC, al-bur commented
context도 바꿔주세요

2022-08-15 09:02 UTC, rladpwl0512 commented
추가 구현 기능입니다. 
- 그룹멤버수 보여주는 UI 삭제
- 그룹 나가기 버튼 구현

2022-08-15 12:25 UTC, rladpwl0512 commented on frontend/src/components/SidebarLayout/SidebarLayout.tsx
> +  const handleSetClickedMenu = (menu: string) => () => {
`handleMovetoClickedMenu` 로 변경했는데, 어떻게 생각하시나요? 
내부에는 dispatch를 통해 menu를 변경하고, navigate를 통해 클릭된 메뉴로 이동하는 동작을 합니다. 
이 두개는 하나로 묶어도 될 것 같아서 묶어줬는데, 어떨까요?

2022-08-15 12:26 UTC, rladpwl0512 commented on frontend/src/components/SidebarLayout/SidebarLayout.tsx
> +      <Outlet context={{ setClickedMenu }} />
리뷰 반영했습니다

[feat(sidebar): menu에 대한 상태를 context api로 관리](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/b224e287a0fc442907dc3040cfcac1596495e9b9)

2022-08-15 12:26 UTC, rladpwl0512 commented on frontend/src/components/SidebarLayout/SidebarLayout.tsx
> +        groupCode={groupCode}
리뷰 반영했습니다. 
context api로 변경하면서 함께 반영했습니다 

---
[feat(sidebar): menu에 대한 상태를 context api로 관리](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/b224e287a0fc442907dc3040cfcac1596495e9b9)

2022-08-15 12:30 UTC, rladpwl0512 commented on frontend/src/components/Sidebar/Sidebar.tsx
>    useEffect(() => {
음... 현재 useEffect가 return문 전에 위치해있는데 제가 잘못 이해하고있는걸까요?

2022-08-15 12:30 UTC, rladpwl0512 commented on frontend/src/components/Sidebar/Sidebar.tsx
>    useEffect(() => {
음... 현재 useEffect가 return문 이전에 위치하고있는 것 같은데, 확인해주세요! 제가 놓치고 있는게 있을까요?

2022-08-15 12:31 UTC, rladpwl0512 commented on frontend/src/components/Sidebar/Sidebar.tsx
> +  const navigate = useNavigate();
리뷰 반영했습니다 

---
[refactor(sidebar): useNavigate 위치 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/a7d106358345881fcab5ccd3dc1442318f41d4ab)

2022-08-15 12:33 UTC, rladpwl0512 commented on frontend/src/components/SidebarFeatureMenu/SidebarFeatureMenu.tsx
> +  margin: 2.8rem 0;
오늘 이야기한대로 현재 위치에서는 최상단 컴포넌트가 아니기때문에, 그대로 두도록 하겠습니다. (`SidebarFeatureMenu`를 재사용해서 따로 쓰지는 않을테니까요!)

2022-08-15 12:36 UTC, rladpwl0512 commented on frontend/src/components/SidebarFeatureMenu/SidebarFeatureMenu.tsx
> +margin-bottom: 2rem;
반영했습니다!

---
[refactor(sidebar): css 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/468afd1640ebf1e26e3d1caf5d6bc6f1e3b659fa)

2022-08-15 12:37 UTC, rladpwl0512 commented on frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
> +`;
반영했습니다!

---
[refactor(sidebar): css 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/468afd1640ebf1e26e3d1caf5d6bc6f1e3b659fa)

2022-08-15 12:37 UTC, rladpwl0512 commented on frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
> +  visibility: 'hidden';
반영했습니다!

---
[refactor(sidebar): css 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/468afd1640ebf1e26e3d1caf5d6bc6f1e3b659fa)

2022-08-15 12:37 UTC, rladpwl0512 commented on frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
> +  top: 44px;
반영했습니다!

---
[refactor(sidebar): css 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/468afd1640ebf1e26e3d1caf5d6bc6f1e3b659fa)

2022-08-15 12:37 UTC, rladpwl0512 commented on frontend/src/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.tsx
> +const StyledMenuHeader = styled.div`
반영했습니다!

---
[refactor(sidebar): css 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/468afd1640ebf1e26e3d1caf5d6bc6f1e3b659fa)

2022-08-15 12:40 UTC, rladpwl0512 commented on frontend/src/components/SidebarFeatureMenu/SidebarFeatureMenu.tsx
> +function SidebarFeatureMenu({ handleSetClickedMenu, clickedMenu }: Props) {
컨벤션 잘 지켜야겠네요~ 
현재 `handle`, `on`으로 넘겨주는 것은 없습니다. (context api로 수정하면서)

2022-08-15 12:42 UTC, rladpwl0512 commented on frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
> +const StyledGroupListBox = styled.div<{isClickedShowGroupList: boolean}>(({ theme, isClickedShowGroupList }) => `
반영했습니다

---
[refactor(sidebar): props로 넘어가는 변수명 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/f3618d449b356e7cbf030550d0a87fea169b8a27)

2022-08-15 14:53 UTC, al-bur requested changes
위니 수정 잘했어요~~ 코드 잘 바꿔주셨지만, 약간의 코멘트가 있으니 확인해주세요!!(사실,,많은 것 같기도..) 지금 고치기 힘들다 싶으면 리팩토링때 해도되니까 스케줄 잘 맞춰서 진행해주세요😀

2022-08-15 14:53 UTC, al-bur commented on frontend/src/context/MenuProvider.tsx
> +function menuReducer(state: MenuState, action: MenuAction) {
menuReducer를 만들어준 이유가 있나요?

지금 보면, SET_CLICKED_MENU 밖에 존재하지 않는데, reducer를 만들 필요가 있나 싶어서요!

2022-08-15 14:53 UTC, al-bur commented on frontend/src/components/Sidebar/Sidebar.tsx
>    useEffect(() => {
직전이란 것을 빼먹었군요!! 지금 보시면 navigate와 handleNavigate가 useEffect 뒤에 있어 일관성이 떨어져보여요~
대개 useEffect를 return문 바로 직전에 놓는데, 아마 side Effect를 다 모아놓는 의미가 아닐까해요!

2022-08-15 14:53 UTC, al-bur commented on frontend/src/context/MenuProvider.tsx
> +export function useMenuState() {
지금까지 저희가 이런식으로 export 하지 않았어요!! 갑자기 이렇게 한 이유가 있을까요?

2022-08-15 14:53 UTC, al-bur commented on frontend/src/context/MenuProvider.tsx
> +export function useMenuDispatch() {
여기도요~

2022-08-15 14:53 UTC, al-bur commented on frontend/src/context/MenuProvider.tsx
> +export default MenuProvider;
export default만 보면 MenuProvider 파일에서는 MenuProvider만 export된다라고 생각할 것 같아요~

2022-08-15 14:53 UTC, al-bur commented on frontend/src/pages/MainPage/MainPage.tsx
> +  dispatch({ type: 'SET_CLICKED_MENU', menu: '' });
지금 발견했는데, menu에 빈 string 보다는 명시적으로 Main이 어떨까요?

2022-08-15 14:53 UTC, al-bur commented on frontend/src/components/SidebarLayout/SidebarLayout.tsx
> +  const handleSetClickedMenu = (menu: string) => () => {
handleMovetoClickedMenu 함수명만 보면 저는 Move하는 로직만 있겠구나라는 생각이 들었어요😥
해당 함수를 사용하는 개발자가 set하는 로직을 모른 채 사용한다면, 살짝 놀랄 수도 있지 않을까 싶어요!

사실 전반적으로 저희 프로젝트 코드에 이러한 함수들(여러일을 하는 함수)이 많을 것 같네요!
지금 시간이 많이 없으니, 이 부분은 TODO로 기록하고 리팩토링때 다시 다루도록 할까요?

2022-08-15 14:53 UTC, al-bur commented on frontend/src/components/SidebarFeatureMenu/SidebarFeatureMenu.tsx
> +function SidebarFeatureMenu({ handleSetClickedMenu, clickedMenu }: Props) {
good입니다!

2022-08-15 14:53 UTC, al-bur commented on frontend/src/components/SidebarLayout/SidebarLayout.tsx
> +      <Outlet context={{ setClickedMenu }} />
좋네요~

2022-08-15 14:53 UTC, al-bur commented on frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
> +const StyledGroupListBox = styled.div<{isClickedShowGroupList: boolean}>(({ theme, isClickedShowGroupList }) => `
더 나아졌네요!! 근데 사실상, StyledGroupListBox가 보여지고 숨기는 것을 제어하기 위한 변수이니 isVisible이라는 변수명이 더 명료한 인터페이스이지 않을까 싶어요!

이렇게 아래의 코드를 보면, StyledGroupListBox가 보여지고 숨겨지겠구나~라고 생각이들텐데

```javascript

<StyledGroupListBox isVisible={true | false} />

```

아래 코드를 봤을 때는, GroupList라는 게 또 있는 건가??라고 생각이 들면서 어떻게 코드가 구성되어 있는 지 봐야하는 번거로움이 생길 수도 있을 것 같아요

```javascript

<StyledGroupListBox isShowGroupList={true | false} />

```

위니는 어떻게 생각하나요?

2022-08-15 14:53 UTC, al-bur commented on frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
> +  const [isClickedGroupList, setIsClickedGroupList] = useState(false);
위에 코멘트로 답했어요!

2022-08-16 00:40 UTC, rladpwl0512 commented on frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
> +const StyledGroupListBox = styled.div<{isClickedShowGroupList: boolean}>(({ theme, isClickedShowGroupList }) => `
너무 인정합니다 자주 간과하네요... 
자식 컴포넌트의 입장에서 알 필요가 있는 정보인지 아닌지를 항상 생각해야겠네요 😅

2022-08-16 00:41 UTC, rladpwl0512 commented on frontend/src/components/SidebarLayout/SidebarLayout.tsx
> +  const handleSetClickedMenu = (menu: string) => () => {
좋습니다~! :)

2022-08-16 00:42 UTC, rladpwl0512 commented on frontend/src/context/MenuProvider.tsx
> +export function useMenuState() {
그러게요 제 정신이 날아갔나봅니다 🤔

2022-08-16 00:43 UTC, rladpwl0512 commented on frontend/src/components/Sidebar/Sidebar.tsx
>    useEffect(() => {
리턴문 직전에 useEffect를 모아두는것은 첨 알았어요 ! 모두 이렇게 작성하면 가독성도 좋아지겠네요. 항상 순서가 헷갈려서 어디둘지 고민했는데, 이제 그런 시간이 줄어들 것 같아요~~👏👏
변경해보겠습니다~!!

2022-08-16 05:26 UTC, rladpwl0512 commented on frontend/src/components/Sidebar/Sidebar.tsx
>    useEffect(() => {
[refactor(sidebar): useEffect 위치 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/c32418cc80decacb4becec6c48bce41b54453ccd)

2022-08-16 05:26 UTC, rladpwl0512 commented on frontend/src/context/MenuProvider.tsx
> +function menuReducer(state: MenuState, action: MenuAction) {
이후 더 추가될 수 있을 것 같아서 확장성을 위해서 만들어주었습니다!

2022-08-16 05:31 UTC, rladpwl0512 commented on frontend/src/context/MenuProvider.tsx
> +export function useMenuState() {
[refactor(sidebar): export 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/eca512de97e34d1395d5d58bdc977129b510d40d)

2022-08-16 05:31 UTC, rladpwl0512 commented on frontend/src/context/MenuProvider.tsx
> +export function useMenuDispatch() {
[refactor(sidebar): export 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/eca512de97e34d1395d5d58bdc977129b510d40d)

2022-08-16 05:31 UTC, rladpwl0512 commented on frontend/src/context/MenuProvider.tsx
> +export default MenuProvider;
[refactor(sidebar): export 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/eca512de97e34d1395d5d58bdc977129b510d40d)

2022-08-16 05:35 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/MainPage.tsx
> +  dispatch({ type: 'SET_CLICKED_MENU', menu: '' });
너무 굿입니다!

---
[refactor(sidebar): dispatch에 넘어가는 데이터값을 명시적으로 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/252/commits/186dacc9091286d31da91d9e4952240f4b9e6208)

2022-08-16 11:48 UTC, al-bur commented on frontend/src/pages/AppointmentMainPage/AppointmentMainPage.tsx
> +  dispatch({ type: 'SET_CLICKED_MENU', menu: 'appointment' });
해당 로직은 컴포넌트가 마운트 됐을 때만 호출되면 되는 거니까, useEffect hook 내부에 위치시켜줘야할듯 합니다~

2022-08-16 11:48 UTC, al-bur commented on frontend/src/context/MenuProvider.tsx
> +function menuReducer(state: MenuState, action: MenuAction) {
오호 혹시 어느 부분이 추가될 수 있을 것 같아서인지 알 수 있을까요? 
사실, menu 관련해서는 선택하는 것밖에 없는 것 같아서요!!

2022-08-16 12:08 UTC, rladpwl0512 commented on frontend/src/context/MenuProvider.tsx
> +function menuReducer(state: MenuState, action: MenuAction) {
그냥 나중엔 추가될수도 있지 않을까? 싶어서 만들어주었는데, 생각해보니 그러네요 
이후 관리자를 생각했을 때 메뉴 리스트를 삭제하거나 추가하거나 하는 것을 생각했는데 
사실 지금 상황에서만 생각해도 될 것 같아요~(이런 것들은 state로 관리해주지 않아도 될 것 같구요!) 

그런데 항상 reducer로만 context api를 사용해왔어서 이런 경우 어떻게 해줘야할지 모르겠네요 
한번 찾아보고 적용해보겠습니다! 😅

2022-08-16 12:28 UTC, al-bur commented on frontend/src/context/MenuProvider.tsx
> +function menuReducer(state: MenuState, action: MenuAction) {
넵  그냥 setState 함수 하나만 선언하면 되지 않을까 싶네요~

2022-08-16 12:28 UTC, al-bur approved these changes
고생했어요~~

2022-08-16 16:04 UTC, merged