feat: slack url 연동하는 모달창 구현
woowacourse-teams/2022-mo-rak pull request #255
Opened 2022-08-14 20:31 UTC by rladpwl0512

## 상세 내용
- 피그마 구현 
- ui 구현 
- 추후 api 연결 예정 

## 이후 하면 좋을 것들 🤔 
- modal을 공통 컴포넌트로 만들어도 좋을 것 같습니다. (width, height 설정하고 나머지 화면 dimmed 처리 되도록) 
- sidebar merge 후, 컴포넌트 추상화하면 좋을 것 같습니다. (modal 따로 빼기)

Close #225

2022-08-14 20:31 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-15 06:58 UTC, al-bur commented on frontend/src/components/Sidebar/Sidebar.tsx
>    z-index: 1;
dimmed의 z-index를 높여주면 될듯~

2022-08-15 07:03 UTC, al-bur requested changes
고쳐주세요~~

2022-08-15 13:21 UTC, rladpwl0512 commented on frontend/src/components/Sidebar/Sidebar.tsx
>    z-index: 1;
추가했습니다 :)

[design(slack): dimmed 처리를 위해, z-index 속성 추가](https://github.com/woowacourse-teams/2022-mo-rak/pull/255/commits/9cacfa167556be1d5e5309a3505d7a0efd72ea14)

2022-08-15 13:22 UTC, rladpwl0512 commented on frontend/src/components/Sidebar/Sidebar.tsx
> +  height: calc(100% / 2);
해결했습니다~

[design(slack): width 속성 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/255/commits/0b2ec2a33787ef67a71848a5b2124afea1de811b)

2022-08-16 05:04 UTC, al-bur approved these changes
good~고생했으

2022-08-16 16:20 UTC, merged