refactor: 약속 시간 잡기 및 투표 정렬되는 순서를 변경한다
woowacourse-teams/2022-mo-rak pull request #259
Opened 2022-08-15 08:55 UTC by seong-wooo

## 상세 내용
### 약속 잡기 및 투표가 정렬되는 순서:
진행 중 / 종료 됨 

상태가 같다면 먼저 생성된 순서로 정렬

Close #256

2022-08-15 09:00 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-15 09:13 UTC, leo0842 approved these changes
수고 많으셨어요 💯

2022-08-15 09:13 UTC, leo0842 commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +        }
C: 꼼꼼한 성격이 여기서 드러나네요~

2022-08-15 09:13 UTC, leo0842 commented on backend/src/test/resources/data.sql
> +        'FEsd23C1', '2022-07-31T23:59:00', now(), now());
R: end of line 자동 설정 확인부탁드려요~

2022-08-15 09:25 UTC, RIANAEH requested changes
빨리 구현해주셨네여💯
점점 성장하는 까라!!

2022-08-15 09:25 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +                .sorted()
C: DTO의 역할이지 않을까요?

2022-08-15 09:25 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +    }
A: 이열~

2022-08-15 09:25 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> +                .containsExactly(appointment5.getCode(), appointment4.getCode(), appointment2.getCode(), "FEsd23C1",
C: "FEsd23C1" 이거는 뭔가요?

2022-08-15 09:25 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +        //when
R: 공백 넣어주세영~

2022-08-15 09:39 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> +                .containsExactly(appointment5.getCode(), appointment4.getCode(), appointment2.getCode(), "FEsd23C1",
data.sql.. 얼른 data.sql 지우고 싶네요 
이런 상황처럼 데이터는 있는데 출처가 어디인지 모르는 경우가 많이 생겨서 data.sql 은 없어져야할 것 같아요.

2022-08-15 09:41 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +                .sorted()
저도 그렇게 생각합니다만,, 저희 로직 상 다른 방법을 찾을 수가 없네요. 
추후에 List<PollResponse>를 일급 컬렉션으로 생성하게 되면 DTO의 역할로 바꿀 수 있겠네요!

2022-08-15 09:51 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> +                .containsExactly(appointment5.getCode(), appointment4.getCode(), appointment2.getCode(), "FEsd23C1",
아하 새로 생성한 5개의 약속잡기 외에도 data.sql에 이미 저장돼 있는 약속잡기가 있어서 그랬던거였군요! data.sql 좀 꼴보기 싫네여😓

2022-08-15 13:29 UTC, cjlee38 requested changes
well done!

2022-08-15 13:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +public class AppointmentAllResponse implements Comparable<AppointmentAllResponse>{
```suggestion
public class AppointmentAllResponse implements Comparable<AppointmentAllResponse> {
```

r: 매의눈 👀

2022-08-15 13:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +
c: 개인적으로는 개행이 없으면 좋을 것 같아요~ 밑에도 :)

2022-08-15 13:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/ui/dto/PollResponse.java
> +public class PollResponse implements Comparable<PollResponse>{
```suggestion
public class PollResponse implements Comparable<PollResponse> {
```

r: 여기도 매의눈 👀

2022-08-15 13:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/ui/dto/PollResponse.java
> +
c: 여기도 개행 한번만 고려해주세요 ( + 49 line )

2022-08-15 13:29 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> -                .code(Code.generate(length -> "FJn3ND26"))
a: 여기를 지우고 밑에서 하나씩 코드를 생성하도록 설정한 이유가 궁금해요 ~

2022-08-15 13:29 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +                                        true)
a: wow  고생하셨네요 ;

2022-08-15 13:29 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +        );
c: 이쪽을 보다보니 든 생각인데, 모든 필드를 다 비교하지 않고, "order1", "order2"와 같은 타이틀만 보고 비교해도 괜찮지 않았을까 하는 생각이 드네요. 괜찮으시면 반영해주세요 ~

2022-08-16 00:30 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +        );
저는 기본적으로 모든 필드에 대해서 검증하는 것이 좋다고 생각해서 . . ㅎ 
참고만 하겠습니다 ~

2022-08-16 00:31 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +        );
![참고해라](https://user-images.githubusercontent.com/79205414/184758674-c8956e7a-ff82-4084-b1b9-479e5728b4a7.jpeg)

2022-08-16 00:36 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> -                .code(Code.generate(length -> "FJn3ND26"))
DEFAULT_BUILDER를 통해 여러 개의 약속잡기를 생성할 때 다 같은 code가 들어가서 에러가 발생합니다.
따라서 DEFAULT_BUILDER에는 code가 들어가면 안됩니다.
이제까지는 data.sql에 의존해서 DEFAULT_BUILDER를 사용할 수 있었나봐요.

2022-08-16 00:38 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/poll/ui/dto/PollResponse.java
> +public class PollResponse implements Comparable<PollResponse>{
넵 수정할게유 ~

2022-08-16 00:38 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +
네 반영할게요 ~

2022-08-16 00:39 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +public class AppointmentAllResponse implements Comparable<AppointmentAllResponse>{
매~

2022-08-16 00:51 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> -                .code(Code.generate(length -> "FJn3ND26"))
`DEFAULT_BUILDER를 이용해 한 개의 약속잡기만 생성했기 때문에 테스트에 통과할 수 있었나봐요.` 

이부분이 맞을것같아요. 그런데 새로 추가한 테스트 이외에 나머지 테스트는 하나의 약속잡기를 만들고 저장만 했으니 문제가 되지 않았었던 것 같네요. 신경쓰지 않으면 실수할 수 있는 부분이라, 굳이 다시 원래대로 바꿀 필요는 없을 것 같네요 ! 👍

2022-08-16 00:51 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +        );
ㅇㅈ합니다 💯

2022-08-16 02:35 UTC, RIANAEH approved these changes
까라 리뷰 반영한거 확인했습니다!
정말 수고 많으셨어요~~😸

2022-08-16 02:35 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +        }
C: closed가 래퍼타입이기 때문에 `!this.closed` 대신 이렇게 비교하는걸까요?

2022-08-16 02:40 UTC, cjlee38 approved these changes
perfect

2022-08-16 05:17 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
> +        }
네 맞습니다 this.closed가 null일수도있기 때문입니다 !

2022-08-16 05:17 UTC, merged