feat(poll): 재투표시 이전 기록 보여주도록 기능 구현
woowacourse-teams/2022-mo-rak pull request #269
Opened 2022-08-15 17:50 UTC by al-bur

## 상세 내용

- 재투표시 이전 기록 보여주도록 구현하였습니다

Close #256

2022-08-16 00:27 UTC, rladpwl0512 requested changes
앨버 코드 잘 봤습니다~! 
작성해준 코드가 가독성이 좋아서 술술 읽혔던 것 같아요! 굿입니다 🥰
특별한건 없으나 커멘트 남겼으니 확인해주세요:)

2022-08-16 00:27 UTC, rladpwl0512 commented on frontend/src/components/PollProgress/PollProgressForm/PollProgressForm.tsx
> +const getInitialSelectedPollItems = (pollItems: getPollItemsResponse) =>
👍👍

2022-08-16 00:27 UTC, rladpwl0512 commented on frontend/src/components/PollProgress/PollProgressForm/PollProgressForm.tsx
> +      // NOTE: EMPTY_STRING 상수화 어떤가요?
이후 상수화에서 같이 해보면 좋을 것 같네요 :)

2022-08-16 00:27 UTC, rladpwl0512 commented on frontend/src/components/PollProgress/PollProgressForm/PollProgressForm.tsx
> +      const copiedSelectedPollItems: Array<SelectedPollItem> = JSON.parse(
변수명이 명확해서 좋아요~

2022-08-16 00:27 UTC, rladpwl0512 commented on frontend/src/components/PollProgress/PollProgressItemGroup/PollProgressItemGroup.tsx
> +        const isSelectedPollItem = !!selectedPollItem;
느낍표가 두개인것은 뭘 의미하나요?🤔

2022-08-16 00:27 UTC, rladpwl0512 commented on frontend/src/components/PollProgress/PollProgressItemGroup/PollProgressItemGroup.tsx
> +                  fontSize="12px"
이번에 앨버가 작성한건 아니지만 ... 요기 rem도 슬쩍 바꿔주세요 👋

2022-08-16 11:51 UTC, al-bur commented on frontend/src/components/PollProgress/PollProgressForm/PollProgressForm.tsx
> +      const copiedSelectedPollItems: Array<SelectedPollItem> = JSON.parse(
최대한 변수명을 명확하게 지으려고 노력중입니다!

2022-08-16 11:52 UTC, al-bur commented on frontend/src/components/PollProgress/PollProgressItemGroup/PollProgressItemGroup.tsx
> +        const isSelectedPollItem = !!selectedPollItem;
![image](https://user-images.githubusercontent.com/64825713/184873006-d52980b8-7824-475d-8c9d-ec2bd08b543d.png)

여깄습니다~

2022-08-16 11:52 UTC, al-bur commented on frontend/src/components/PollProgress/PollProgressItemGroup/PollProgressItemGroup.tsx
> +                  fontSize="12px"
넵!

2022-08-16 11:55 UTC, cjlee38 commented
Can one of the admins verify this patch?

2022-08-16 11:56 UTC, al-bur commented on frontend/src/components/PollProgress/PollProgressItemGroup/PollProgressItemGroup.tsx
> +                  fontSize="12px"
수정했습니다 ~[64dc5e4](https://github.com/woowacourse-teams/2022-mo-rak/pull/269/commits/64dc5e4dff53b4491cd4e345f6372716dd810c88)

2022-08-17 06:08 UTC, rladpwl0512 approved these changes
굿굿 approve 하겠습니다~

2022-08-17 06:56 UTC, merged