refactor: 약속잡기의 쿼리 성능을 개선한다.
woowacourse-teams/2022-mo-rak pull request #364
Opened 2022-09-06 05:42 UTC by cjlee38

## 상세 내용

인덱스는 아직 안걸었습니다.

Close #358

2022-09-12 10:57 UTC, RIANAEH requested changes
약속잡기에서 쿼리 개수를 줄인 부분 확인했습니다. 굿!!
몇가지 궁금한 점 코멘트로 남겨놨어요~~
그리고 이번에 인덱스를 추가한 컬럼이 있을까요?

2022-09-12 10:57 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        validateMemberInTeam(team, member);
R: 기존에 teamId와 memberId를 사용하는 방식에서 team과 member를 사용하는 방식으로 변경한 이유가 궁금합니다!

2022-09-12 10:57 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +    }
A: 개발 일지를 보고 bulk update를 하기위해 다음과 같이 변경했다는 것을 이해했습니다. 좋네용👍

2022-09-12 10:57 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +    }
R: notifyMenuStatus()에 전파레벨을 REQUIRES_NEW로 설정해 notifyAllMenuStatus()를 호출했을 때 각 메뉴별로 트렌젝션이 다르게 생성되게 한 점 너무 좋을 것 같아요!!
하지만 notifyAllMenuStatus()에도 전파레벨을 REQUIRES_NEW로 설정한 부분은 그 의도가 잘 이해가 안되는 것 같아요. 이에 대해 설명해주실 수 있나요?

2022-09-12 10:57 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentSchedulerTest.java
> +    void 스케줄링에_의해_약속잡기를_종료한다(@Autowired EntityManager entityManager) {
A: 스케줄링 테스트 추가 굿!!

2022-09-12 10:57 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        // then
A: 오! 왜 refresh()를 했나 했는데, 먼저 appointments를 조회해 영속성 컨텍스트에 저장된 상태에서 closeAllByIds()를 했기 때문에 DB의 변경 사항을 영속성 컨텍스트의 appointments에도 반영을 해줘야해서 사용한 것이었군요! 많이 배워갑니다~~

R: then위에 개행을 넣어주면 보기 좋을 것 같아요~

2022-09-12 10:57 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        // then
추가적으로 왜 appointment.close()를 사용하지 않고 repository.close()를 사용하는지 궁금했는데, 

```java
for (Appointment appointment : appointments) {
    appointment.close(appointment.getHost());
}
```
테스트에서 위의 코드처럼 수행 후 flush()를 해보니 update가 appointments의 개수만큼 수행되더라구요. 이해했습니다!!

2022-09-13 05:40 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +    public void notifyClosedBySchedule() {
public이 빠져있던 것을 이제서야 발견하다니 ; 
리뷰 꼼꼼히 하겠습니다 ~

2022-09-13 05:40 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
> +    void closeAllByIds(@Param("ids") Iterable<Long> ids);
여러 개의 약속을 하나의 쿼리로 상태 변경할 수 있게 되었네요. 굳

2022-09-13 05:40 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimeRepository.java
> +    List<AvailableTime> findAllByMemberAndAppointment(Member member, Appointment appointment); // 사용하지 않음
테스트에서만 사용되는 코드네요! 해당 코드를 삭제하고 테스트를 변경해보는 것은 어떨까요 ?

2022-09-13 05:40 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +        deleteOldWebhook(team);
질문)
이 `saveSlackWebHook` 메소드를 실행하기 위한 방법이 두 가지가 있는 것 같아요. 하나는 지금처럼 지금처럼 기존에 있던 webhook을 삭제하고 다시 save하는 경우가 있을 것 같고, 또 다른 방법으로 팀을 통해 slackWebHook을 조회해와서 url만 업데이트 하는 경우와 가 있을 것 같은데 
전 왜 후자가 더 좋은 것 같죠,, ?

2022-09-13 05:40 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +        deleteOldWebhook(team);
ex) 
```
SlackWebhook webhook = slackWebhookRepository.findbyTeam(team).orElseGet(() -> SlackWebhook.builder()
                        .team(team)
                        .url(request.getUrl())
                        .build());

webhook.url(request.getUrl())
```

2022-09-13 05:42 UTC, seong-wooo requested changes
기존의 id만을 이용해서 조회하던 로직들을 entity로 이용해서 조회하도록 변경하셨네요 !
굳

2022-09-13 06:14 UTC, seong-wooo requested changes

2022-09-13 06:14 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
> +        List<PollItem> pollItems = buildPollItems(poll);
`List<PollItem> pollItems =` 지워주세요. 이거때매 헷갈렸네요 :(

2022-09-13 06:14 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
> +    private List<PollItem> buildPollItems(Poll poll) {
````
   private List<PollItem> buildPollItems(Poll poll) {
        PollItemBuilder pollItemBuilder = PollItem.builder().poll(poll);
        return subjects.stream()
                .map(
                        subject -> pollItemBuilder
                                .subject(subject)
                                .build()
                )
                .collect(Collectors.toList());
    }
````
이렇게 바꾸는 것은 어떨까요 ?

2022-09-13 06:32 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        assertThat(appointments).allMatch(appointment -> appointment.getStatus() == AppointmentStatus.CLOSED);
assertThat(appointments).allMatch(appointment -> Appointment::isClosed);

2022-09-13 07:06 UTC, seong-wooo requested changes

2022-09-13 07:06 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        assertThat(appointments).allMatch(appointment -> appointment.getStatus() == AppointmentStatus.CLOSED);
이렇게 바꾸는건 어떨까유 물론 테스트 코드라서 중요한건 아닙니다 ~

2022-09-14 22:06 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        validateMemberInTeam(team, member);
https://bcp0109.tistory.com/305

위 글을 참고했습니다.

2022-09-14 22:19 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +    }
이곳저곳 고치다보니 조금 꼬인 것 같네요. 알림 메세지를 보낼때는 일단 전파 레벨을 안거는걸로 설정했는데, 동시성 문제를 고려하면 또 문제가 발생할 수도 있어서 다시 고민해보겠습니다~

2022-09-14 22:20 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimeRepository.java
> +    List<AvailableTime> findAllByMemberAndAppointment(Member member, Appointment appointment); // 사용하지 않음
지난번에 이 코드에 대해서 향후에 사용할 수 있으니 삭제하지 말자는 의견으로 정리됐던걸로 기억합니다 ~

2022-09-14 22:23 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +        deleteOldWebhook(team);
findByTeam에 의해 발견된 webhook 은 영속성 컨텍스트에 존재하는 객체인데, `orElseGet`을 타고 얻은 webhook은 영속성 컨텍스트에 존재하지 않는 객체이니 별도의 save 메소드가 필요하겠네요. 

그렇다면 webhook을 findByTeam 에 의해서 얻었는데, save 메소드를 사용하는데에 의문을 느낄 수 있지 않을까요 ?

2022-09-14 22:24 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/application/NotificationService.java
> +        return slackWebhookRepository.findAllByTeams(teamMessages.keySet());
의도를 드러내려는 의미가 더 큰 것 같습니다

2022-09-14 22:25 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
> +        List<PollItem> pollItems = buildPollItems(poll);
지우면 결과값을 사용하지 않는 것에 의문을 느낄 수 있어서 차라리 ignored 라는 변수명이 더 나을 것 같네용.

2022-09-14 22:30 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
> +    private List<PollItem> buildPollItems(Poll poll) {
👍

지금은 바꾸고나서 테스트는 다 통과하고 로직상 문제도 없어보이긴 해서 말씀하신대로 수정했습니다.  다만, builder를 위와 같이 사용할 때 값이 inplace로 바뀐다는 점은 유의해야 할 것 같네요.

2022-09-14 22:31 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
> +        assertThat(appointments).allMatch(appointment -> appointment.getStatus() == AppointmentStatus.CLOSED);
👍

isClosed 메소드의 존재를 까먹고 있었네요~

2022-09-16 03:22 UTC, seong-wooo requested changes

2022-09-16 03:22 UTC, seong-wooo commented on backend/src/main/resources/schema-dev.sql
> +    INDEX `index_poll` (`closed_at`)
local에도 달아주세요

2022-09-16 03:22 UTC, seong-wooo commented on backend/src/main/resources/schema-dev.sql
> +    INDEX `index_poll` (`closed_at`)
test에 있는 schema도여 ~

2022-09-16 04:11 UTC, seong-wooo requested changes

2022-09-16 04:11 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        List<AvailableTime> availableTimes = availableTimeRepository.findAllByAppointment(appointment);
175번째 줄에 리뷰를 남길 수 없어서 여기다가 남깁니다.
175번 줄에 `findByTeamId`로 되어있는데
`findByTeam`으로 바꿀 수 있지 않을까요?

2022-09-18 13:08 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +        List<AvailableTime> availableTimes = availableTimeRepository.findAllByAppointment(appointment);
이 부분은 poll 과 함께 개선할 예정입니다. 도메인이 Team 쪽이라서요~

2022-09-18 13:10 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
>          Appointment appointment = appointmentRepository.findByCode(appointmentCode)
한번에 진행하면 생각해보니 custom error code를 무엇으로 내려줄지에 대한 판단이 어려울 것 같아요.

2022-09-19 07:20 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
>          Appointment appointment = appointmentRepository.findByCode(appointmentCode)
`APPOINTMENT_NOT_FOUND_ERROR`를 그대로 사용하면 되지 않을까요? ㅎ 
해당하는 Appointment가 존재하지 않는 것이니까요

2022-09-19 07:23 UTC, seong-wooo approved these changes
리뷰 반영해주신 것 잘 보았습니다!
고생하셨어요.
제꺼 리뷰도 해주세요

2022-09-19 10:46 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
>          Appointment appointment = appointmentRepository.findByCode(appointmentCode)
`findByCodeAndTeam`으로 한번에 조회하는 경우, `APPOINTMENT_NOT_FOUND_ERROR`와`APPOINTMENT_TEAM_MISMATCHED_ERROR` 중 어떤 예외인지 정확한 판단을 하기 어려울 것 같아요.

2022-09-19 11:08 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
>          Appointment appointment = appointmentRepository.findByCode(appointmentCode)
그리고 검증 로직에서 `appointment.isBelongedTo(findTeam)`를 사용하기 때문에 같은 team인 경우 1차 캐시의 team을 사용하기 때문에 이런 경우에는 추가적인 쿼리가 날아가지 않는다는 장점이 있을 것 같아요!

2022-09-19 11:13 UTC, RIANAEH approved these changes
차리 인덱스 적용해준 것까지 모두 확인했습니다~
수고 많았어요🙌

2022-09-19 11:13 UTC, RIANAEH commented on backend/src/main/resources/schema-dev.sql
> +    `code`       varchar(255) NOT NULL UNIQUE UNIQUE,
A: unique 제약조건을 추가해 자동으로 index를 생성하도록 했군요! 좋습니다!

2022-09-19 11:13 UTC, RIANAEH commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `index_poll` ON `poll` (`closed_at`);
C: 스키마 선언에서 인덱스를 생성하는 방식에서 CREATE INDEX로 인덱스를 생성하는 방식으로 변경한 이유가 궁금합니다! 가독성을 위한 것인지 다른 이유가 있는 것인지 궁금해요!👀

2022-09-19 14:49 UTC, leo0842 approved these changes
많이 배워갑니다

2022-09-19 14:49 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/domain/slack/SlackWebhookRepository.java
> +    void deleteByTeam(Team team);
앞선 delete 와 통일성 및 flush 효과를 볼 수 있도록 이 메서드도 JPQL 로 사용하면 어떨까요??

2022-09-19 14:49 UTC, leo0842 commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +    protected void addItem(PollItem pollItem) {
protected 로 선언한 부분은 명시적인게 큰 건가요??

2022-09-19 14:49 UTC, leo0842 commented on backend/src/main/java/com/morak/back/team/domain/TeamMemberRepository.java
> +    Optional<TeamMember> findByTeamIdAndMemberId(@Param("teamId") Long teamId, @Param("memberId") Long memberId);
이 부분에 대한 설명을 듣고싶습니다,,,!!!!!!

2022-09-19 23:21 UTC, cjlee38 commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `index_poll` ON `poll` (`closed_at`);
테이블에서 직접 생성하려고 했는데 버전이 안 맞는건지  잘 안되더라구요. 그래서 일단 직접 생성하는 쪽으로 빼놓았습니다.

2022-09-19 23:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
>          availableTimeRepository.flush();
그렇네요. 아마 이전에 flush() 문제를 걱정해서 미리 만들어두었던것 같아요.

2022-09-19 23:34 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/domain/slack/SlackWebhookRepository.java
> +    void deleteByTeam(Team team);
앞서서 deleteAll 을 `@Query` 어노테이션을 붙여서 구현했던 이유는 deleteAll 메소드가 내부적으로 batch 처리를 하지 않기 때문인데요.

![image](https://user-images.githubusercontent.com/52564093/191136804-98ca425c-de7b-4f96-ae02-497bcfdc91af.png)

바로 밑에 `deleteAllInBatch`가 있어서 이걸 활용해보려했는데 (`deleteAllByMemberAndAppointmentInBatch`) cannot resolve 라는 컴파일 에러가 나더라구요. [공식문서](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example.introduction)에서도 batch 로 검색해봤을 때 잡히는게 없었구요.

그런데 deleteByTeam 같은 경우에는 어차피 한 건만 처리되기 때문에 굳이 배치처리를 하지 않아도 될 것 같습니다!
(참고로 `@Query` 어노테이션을 사용하지 않더라도, Data JPA가 method 명을 분석해서 JPQL로 처리합니다)

2022-09-19 23:34 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +    protected void addItem(PollItem pollItem) {
넵 맞습니다 ~

2022-09-19 23:35 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/domain/TeamMemberRepository.java
> +    Optional<TeamMember> findByTeamIdAndMemberId(@Param("teamId") Long teamId, @Param("memberId") Long memberId);
어떤 설명을 말씀하시는걸까요? 만약 Query annotation을 붙인 이유라면, 이 부분은 이후 투표+팀 쪽에서 한번에 개선하려고 임시적으로 이렇게 해놓은거라고 말씀드릴 수 있겠네요.(파라미터를 다 뜯어고쳐야해서요 ㅠ)

2022-09-21 03:15 UTC, merged