refactor(appointment): 약속잡기 진행페이지내 timepicker 리팩토링
woowacourse-teams/2022-mo-rak pull request #372
Opened 2022-09-11 12:54 UTC by al-bur

## 상세 내용
`AppointmentProgressTimePicker.tsx`를 리팩토링 했습니다.

아래는 주요 리팩토링 사항입니다. (이것말고도 추가적으로 있을 것이라서 변경된 코드 보고 리뷰해주시면 감사하겠습니다😀)

1. getTimes 함수 리팩토링 
함수명 변경, 변수명 변경, if문 최대한 줄이기
2. getTimeDetail 함수 생성
period, hour, minute에 대한 정보를 추출하는 로직이 중복되고 있어 하나의 함수로 추출
3. formatHM 함수 => formatHourMinutePeriod 함수로 변경
toLocalString을 활용하여 로직 단순화
4. getPlusOneDate 함수명 => getPlusOneDay로 변경
함수의 동작은 one day를 plus해주는 것이기 때문에, 동작이 더 잘 나타나도록 변경

Close #370

2022-09-12 11:20 UTC, rladpwl0512 requested changes
앨버 코드 잘 봤습니다! 😄
몇가지 궁금한 부분들을 남겼으니 확인해주세요~

2022-09-12 11:20 UTC, rladpwl0512 commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +  const period = time.slice(-2);
AM, PM을 나타내는 변수명이네요! 
사실 바로 이해하기 힘들었던 것 같아요. (period라고해서 뭔가 처음~끝과 같이 범위를 가지고 있어야할 것 같은...?) 
생각해보니 저도 당장은 잘 떠오르지 않네요... 다시 생각해보면 좋을 것 같아서 남겨둡니다!

2022-09-12 11:20 UTC, rladpwl0512 commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +  const [startPeriod, startHour, startMinute] = getTimeDetail(startTime);
여기도 (period!)

2022-09-12 11:20 UTC, rladpwl0512 commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +  const startDate = new Date(0, 0, 0, startHour, startMinute);
년, 월, 일을 0으로 설정해준 이유가 있나요~? 
0으로 설정하면 무슨 값이 되나요?

2022-09-12 11:20 UTC, rladpwl0512 commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +    const startTimeTable = startDate;
왜 `startDate`를 바로 사용하지 않고 `startTimeTable`에 할당해서 사용해야하나요? 🤔

2022-09-12 12:47 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +  const startDate = new Date(0, 0, 0, startHour, startMinute);
시간에 대해서만 비교해서 계산을 해주면 되기 때문에, 년, 월,일을 0, 0, 0으로 고정해서 Date를 생성해주었습니다.


> 0으로 설정하면 무슨 값이 되나요?
Sun Dec 31 1899 00:00:00 GMT+0827 (한국 표준시)가 나옵니다

2022-09-12 12:49 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +    const startTimeTable = startDate;
이는 단순히 아래의 endTimeTable과 변수명을 맞추기 위해서 따로 변수로 선언해주었습니다!

사실상 불필요하게 변수를 하나 더 선언해주는 것이긴 한데, 아래처럼 startDate를 사용해주게 되면 코드를 이해하는 데 어려움을 줄 것 같았습니다. 

```typescript
  timetables.push({
    start: formatHourMinutePeriod(startDate),
    end: formatHourMinutePeriod(endTimeTable)
  });
```

2022-09-12 12:50 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +  const [startPeriod, startHour, startMinute] = getTimeDetail(startTime);
확인했습니다!

2022-09-12 12:50 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +  const period = time.slice(-2);
맞아요...period라고 처음에 정하긴 했었는데, 지금 보니 애매한 변수명인 것 같아요!!
고민해보죠!

TODO추가!

2022-09-12 12:56 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +const formatHourMinutePeriod = (date: Date) =>
> 이 함수가 AM, PM에 따라 시간을 포맷팅해주는 함수인가봐요! 사실 이런 로직은 처음봐서 잘 이해가 안되는데 무엇을 하는 코드인지 간단하게 설명해주실 수 있을까요?

Date 객체의 내장 메서드인 toLocaleString을 사용하면 원하는 대로 Date를 string으로 변환할 수 있습니다. (아래 참고)

```javascript
const event = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));

console.log(event.toLocaleString('en-GB', { timeZone: 'UTC' }));
// expected output: 20/12/2012, 03:00:00

console.log(event.toLocaleString('ko-KR', { timeZone: 'UTC' }));
// expected output: 2012. 12. 20. 오전 3:00:00
```

제 코드를 설명드리겠습니다

```javascript
date.toLocaleString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true
```

hour, minute 속성은 `시`와 `분`을 어떻게 표현해줄 것인지입니다. `2-digit`을 설정해주어, `12:00`나 `08:00`으로 표시해줄 수 있습니다.

hour12 속성은 12시간으로 시간을 계산할 것인지를 정해주는 속성입니다. 현재 저희가 
AM, PM 형식으로 나타내줘야하니 12시간 형식을 사용하도록 해주었습니다.

마지막으로, en-US는 `locales`를 지정해주는 것인데,  AM, PM으로 변환해주기 위해 설정해주었습니다.

2022-09-12 12:57 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +const formatHourMinutePeriod = (date: Date) =>
> 그리고 왜 뒤에 Period를 넣어줬는지 궁금합니다! 🤔

함수의 역할을 잘 나타내기 위해 넣어주었습니다.

이 함수를 사용하면, `08:00AM`이나 `12:00PM` 같은 형식으로 format 할 수 있다라는 것을 나타내기 위해 함수명에 period(AM, PM)까지 넣어주었습니다!

2022-09-12 12:57 UTC, al-bur commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +    .toLocaleString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true })
https://github.com/woowacourse-teams/2022-mo-rak/pull/372#discussion_r968383551 여기에서 대답했습니다!

2022-09-13 06:04 UTC, rladpwl0512 commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +const formatHourMinutePeriod = (date: Date) =>
오 자세한 설명 감사합니다~ 👍 `2-digit`이 이미 존재하는 속성값의 설정이군요 ㅎㅎ

2022-09-13 06:05 UTC, rladpwl0512 commented on frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
> +    const startTimeTable = startDate;
가독성을 생각한 코드였네요 좋습니다!

2022-09-13 06:06 UTC, rladpwl0512 approved these changes
답변해주신 것 모두 확인했습니다~
period는 나중에 함께 고민해보아요!

approve 하겠습니다~

2022-09-14 11:12 UTC, merged