refactor: calendar 컴포넌트 리팩토링
woowacourse-teams/2022-mo-rak pull request #375
Opened 2022-09-12 13:50 UTC by al-bur

## 상세 내용

- [x] 불필요한 주석문 제거
- [x] 반복되는 값 변수로 추출하여 재사용
- [x] formatDate 불필요한 인자 제거 후 내부에서 currentDate 참조하도록 변경
- [x] 변수명 변경
- [x] 함수명 변경
- [x] getPrevMonthDays 함수에서 Date 객체를 위험하게 변경하고 있었기 때문에, 복사본 Date를 만들어서 사용하도록 변경
- [x] handleStartOrEndDate 함수내 불필요한 if문 제거 (?. 사용)
- [x] 배열에 key 설정
- [x] etc..

Close #373

2022-09-14 05:57 UTC, rladpwl0512 requested changes
앨버 복잡한 캘린더 리팩토링 하시느라 수고하셨습니다~ 
코드가 정말 많이 깔끔해진 것 같아요👍 
몇가지 코멘트 남겼으니 확인해주세요 :)

2022-09-14 05:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +  const formatDate = (day: number) =>
매개변수명을 `day` 로 작성해주신 이유가 있을까요? 
date는 2022-09-14 와 같은 것이고, day는 14라고 이해하면 될까요?

2022-09-14 05:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +      .padStart(2, '0')}`;
prettier 기본 설정때문에 이렇게 줄바꿈이 된 것 같은데, 조금 가독성이 떨어져보이네요 😓 앨버는 어떻게 생각하시나요

2022-09-14 05:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +    const copiedCurrentDate = new Date(currentDate.getTime());
저장되어있는 `currentDate` 의 날짜를 `getTime` 메서드로 복사해주는 이유가 따로 있나요? 🤔
그냥 `currentDate`를 할당해주는 것과 무슨 차이가 있나요~?

2022-09-14 05:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +    return Array.from({ length: currentMonthLastDay }, (v, i) => i + 1);
지금 생각해보니, `Array.from({ length: currentMonthLastDay }, (v, i) => i + 1);` 코드가 `currentMonthDays` 임을 알아채기 힘들 것 같다는 생각도 들네요! 
`Array.from({ length: currentMonthLastDay }, (v, i) => i + 1);` 를 `currentMonthDays`  와 같은 변수에 할당하고 return 해주는 방식은 어떻게 생각하시나요? 
(함수명이 명확하니 괜찮을 것 같기도 + 불필요한 변수를 만들어주는 건가 싶기도 하지만...) 앨버의 생각이 궁금합니다~

2022-09-14 05:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +        }월`}</StyledMonthTitle>
여기도 prettier 설정때문인 것 같은데, 가독성이 조금 떨어져보이네요 😅

2022-09-14 05:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +              if (isNotBetweenStartAndEndDate(day)) {
범위에 startDate와  endDate도 포함한다는 것을 어떻게 드러낼 수 있을까요? 
제가 이전에 Between이 아닌 In으로 넣어 준 이유는 시작날짜와 끝날짜를 포함해야하기 때문에 (5~10가 아닌날~) '포함한다'의 의미로 In을 넣어주었습니다. 
Between은 5 ~ 10 '사이' 라는 의미가 강하다 생각이 되어서 6 ~ 9가 아닌날 으로 이해가 되는데, 어떻게 생각하시나요🤔  
물론 between은 포함하거나, 포함하지 않거나 두가지 의미를 모두 가지고 있지만 경계값을 명확히 변수명에 드러내야할 것 같다는 생각이 들어요! 

+) 찾아보니 엄연히 between 영어 단어 자체의 의미로 파악했을 때, 경계값을 포함하지 않는다고 해요. ([참고](https://www.quora.com/English-Grammar-Does-between-two-numbers-a-and-b-include-a-and-b-themselves/answer/Samuel-Trippler?ch=10&oid=6544642&share=e34ff630&target_type=answer))
사실 이 둘을 명확히 구분해서 사용하는 사람들은 많이 없지만, 포함 여부를 명확하게 드러내주는 것이 좋다는 글도 있네요. ([참고](https://qr.ae/pvUXsV))
포함한다는 의미를 드러내기위해서는 `inclusive` 라는게 있는 것 같은데, 변수명은 조금 더 생각해봐야할 것 같습니다. 
암튼 경계값을 변수명에 드러내주는 것이 좋을 것 같아서 커멘트 남깁니다!

2022-09-14 05:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +
공백~! 🤭

2022-09-14 12:01 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +      .padStart(2, '0')}`;
맞아요 printwidth 100 때문에 그런 것 같은데, 특수한 경우에만 늘려주거나 미리 줄 넘김을 해줄 수 있는 방법이 있을까요?

2022-09-14 12:05 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +    const copiedCurrentDate = new Date(currentDate.getTime());
currentDate는 Calendar 컴포넌트 전역적으로 사용되고 있기 때문에, 기존의 currentDate.setHour() 같은 메서드로 currentDate 자체를 바꿔준다면 다른 곳(currentDate를 사용하는 곳)에서 참조하고 있는 currentDate가 실제로 `현재의 날짜`를 나타내지 않을 위험이 있습니다.

실제로, 기존의 코드에서 아래처럼 해주고 있어서, currentDate를 사용하는 다른 곳에서 기능이 깨져버리는 상황이 나오더라구요!

```typescript

currentDate.setDate(1);

```

2022-09-14 12:07 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +  const formatDate = (day: number) =>
year, month, day가 년,월,일을 나타내기 때문에 `일`을 위한 매개변수이기 때문에 `day`를 사용해주었습니다!

2022-09-14 12:12 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +    return Array.from({ length: currentMonthLastDay }, (v, i) => i + 1);
> Array.from({ length: currentMonthLastDay }, (v, i) => i + 1); 를 currentMonthDays 와 같은 변수에 할당하고 return 해주는 방식은 어떻게 생각하시나요?

좋은 발상의 전환인 것 같습니다!

음...근데, 함수명이 `getCurrentMonthDays`이라고 명확하게 나와있기 때문에 `currentMonthDays`를 return 하는 거구나라고 알아볼 수 있을 것 같아요!



```typescript

const currentMonthLastDay = new Date(currentYear, currentMonth + 1, 0).getDate();

```

위에 같이 위치하는 코드 같은 경우는 따로 변수를 만들어주었습니다. 이유는, `new Date(currentYear, currentMonth + 1, 0).getDate()`를 설명해주기 위한 부분이 없어서 입니다.

2022-09-14 12:12 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +        }월`}</StyledMonthTitle>
어 그렇네요...왜 그런걸까요?...이건 길이가 100이 안될 것 같은데 찾아보겠습니다

2022-09-14 12:30 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +        }월`}</StyledMonthTitle>
이건 단순히 잘못 띄어쓰기 한거네요ㅎㅎ 수정했습니다.

[dea4dcb](https://github.com/woowacourse-teams/2022-mo-rak/pull/375/commits/dea4dcbdb2e1f15a68da0efd2a6166f9a8961eac)

2022-09-14 12:31 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +      .padStart(2, '0')}`;
이거는 string literal이라서 강제 줄바꿈으로는 기존의 기능에 버그를 유발시키네요ㅠㅠ

2022-09-14 12:45 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +              if (isNotBetweenStartAndEndDate(day)) {
맞아요! 저도 위니처럼 between은 사이라고 생각합니다. 
왜 between으로 바꿨냐면 함수가 시작 날짜와 끝날짜를 포함하면 안되도록 구현되어있었기 때문이에요

아래는 이전 코드입니다.

```typescript

const isNotInStartAndEndDate = (day: number) =>
    new Date(startDate) > new Date(formatDate(date, day)) ||
    new Date(formatDate(date, day)) > new Date(endDate);

```

그래서, 다시 함수가 사용되는 곳을 봤는데, 시작과 끝을 포함하면 안될 것 같더라고요!!!

![image](https://user-images.githubusercontent.com/64825713/190157063-1929f5d8-137b-46d4-b18f-704b1fb1c9ee.png)


보고 의견 주세요!

2022-09-14 12:47 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +
```typescript

const StyledCalendar = styled.div(
  ({ theme }) => `
  width: 45.2rem;
  height: 60rem;
  border-radius: 2rem;

  background: ${theme.colors.WHITE_100};
`
);

```

이거는 사실 의도한 공백입니다. 매개변수를 사용하는 속성들은 밑에 따로 빼두면 어떨가 싶어서 공백으로 구분을 해보았는데요. 이 부분에 대해서는 내일 이야기 해봐도 좋을 것 같아요~

2022-09-15 00:25 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +      .padStart(2, '0')}`;
오 ... 이런 상황도 생길 수 있군요...! 🤔 앨버가 한대로 두는게 좋겠네요

2022-09-15 00:27 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +    return Array.from({ length: currentMonthLastDay }, (v, i) => i + 1);
함수 명이 명확해서 앨버 말대로 해도 좋을 것 같아요 😄👏👏

2022-09-15 00:31 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +
좋습니다 :)

2022-09-15 00:39 UTC, rladpwl0512 commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +              if (isNotBetweenStartAndEndDate(day)) {
5-10일이라고 가정하면 
-> endpoint 포함: 5-10일이 아니면 글자를 회색처리
-> endpoint 포함x: 6-9일이 아니면 글자를 회색처리 (5, 10일도 회색처리됨😅)

이렇게 되는 것 아닌가요...? "endpoint(시작 및 끝날짜)를 포함한 날짜가 아니면 선택불가하니 회색처리 한다" 가 맞지 않을까요?!

2022-09-15 00:51 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +              if (isNotBetweenStartAndEndDate(day)) {
아아 맞네요!ㅎㅎ 위니 말이 맞습니다! 수정하겠습니다😀😀 감사합니다 ㅎㅎ

2022-09-15 00:53 UTC, al-bur commented on frontend/src/components/@common/Calendar/Calendar.tsx
> +              if (isNotBetweenStartAndEndDate(day)) {
[fb27900](https://github.com/woowacourse-teams/2022-mo-rak/pull/375/commits/fb279004ca8dea3bbf44b801b670df23c339649a)

2022-09-15 06:52 UTC, rladpwl0512 approved these changes
앨벌~ 리뷰 반영하신 것도, 코멘트 달아주신 것도 모두 확인했습니다! 
수고하셨습니다 😎💯 
approve 하겠습니다

2022-09-15 06:53 UTC, merged