refactor: 약속잡기를 제외한 나머지 도메인의 쿼리 성능을 개선한다
woowacourse-teams/2022-mo-rak pull request #402
Opened 2022-09-22 02:57 UTC by cjlee38

## 상세 내용
밥먹고 정리할게요 :) 
Close #395

2022-09-22 07:52 UTC, seong-wooo requested changes

2022-09-22 07:52 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
> +        List<TeamMember> teamMembers = teamMemberRepository.findAllByMember(member);
기존에 있던
`teamMemberRepository.findAllByMemberId(memberId)` 랑
`teamMemberRepository.findAllByMember(member)` 
둘 다 같은 쿼리가 나가더라구요. 굳이 멤버를 조회할 필요가 있을까요??


```
    select
        teammember0_.id as id1_9_0_,
        team1_.id as id1_7_1_,
        teammember0_.created_at as created_2_9_0_,
        teammember0_.updated_at as updated_3_9_0_,
        teammember0_.member_id as member_i4_9_0_,
        teammember0_.team_id as team_id5_9_0_,
        team1_.created_at as created_2_7_1_,
        team1_.updated_at as updated_3_7_1_,
        team1_.code as code4_7_1_,
        team1_.name as name5_7_1_ 
    from
        team_member teammember0_ 
    inner join
        team team1_ 
            on teammember0_.team_id=team1_.id 
    where
        teammember0_.member_id=?
```

2022-09-22 10:56 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/application/PollService.java
> +    private Map<PollItem, String> mapPollItemAndDescription2(List<PollResultRequest> requests) {
👍 제거완료

2022-09-22 10:59 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> +    void closeAllByIds(@Param("ids") List<Long> ids);
👍 적용완료

2022-09-22 10:59 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
> +        List<TeamMember> teamMembers = teamMemberRepository.findAllByMember(member);
👍 반박완료

2022-09-22 11:00 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
>                                  CustomErrorCode.TEAM_MEMBER_MISMATCHED_ERROR,
👍 반박완료

2022-09-22 11:09 UTC, seong-wooo commented
쿼리 튜닝에 관한 것은 아닌데, 짜잘한 코드 수정 질문 남깁니다.

1. 
AppointmentService에서 createAppointment 68번 줄에 appointment 객체를 사용하고있네요. 69번 줄은 savedPoll을 사용하고 있고요.
물론 같은 객체이긴한데 괜히 불편하네요. savedPoll을 생성하지 않거나 savedPoll만 사용하도록 바꾸죠

2. AppointmentService에서 126번줄에 `validateDuplicatedRequest` request 중복은 Controller에서 처리해도되지않을까요? Service 에서 요청에 대한 검증을 진행하는게 이상해서 ? -> 나중에 얘기해보죠

2022-09-22 11:15 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
>          return TeamResponse.from(findFirstTeamMember(memberId, teamMembers).getTeam());
1. 페이징 사용했을 경우

```        
List<TeamMember> teamMembers = teamMemberRepository.findAllByMember(member, Pageable.ofSize(1));
```

```
select
        teammember0_.id as id1_9_0_,
        team1_.id as id1_7_1_,
        teammember0_.created_at as created_2_9_0_,
        teammember0_.updated_at as updated_3_9_0_,
        teammember0_.member_id as member_i4_9_0_,
        teammember0_.team_id as team_id5_9_0_,
        team1_.created_at as created_2_7_1_,
        team1_.updated_at as updated_3_7_1_,
        team1_.code as code4_7_1_,
        team1_.name as name5_7_1_ 
    from
        team_member teammember0_ 
    inner join
        team team1_ 
            on teammember0_.team_id=team1_.id 
    where
        teammember0_.member_id=? limit ?
```

innerJoin이 들어간다.

2022-09-22 11:18 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
>          return TeamResponse.from(findFirstTeamMember(memberId, teamMembers).getTeam());
2. findFirstByMemberOrderById 사용한 경우
```   
final TeamMember teamMember = teamMemberRepository.findFirstByMemberOrderById(member).orElseThrow();
        return TeamResponse.from(teamMember.getTeam());
```
사용된 로직

```
 select
        teammember0_.id as id1_9_,
        teammember0_.created_at as created_2_9_,
        teammember0_.updated_at as updated_3_9_,
        teammember0_.member_id as member_i4_9_,
        teammember0_.team_id as team_id5_9_ 
    from
        team_member teammember0_ 
    where
        teammember0_.member_id=? 
    order by
        teammember0_.id asc limit ?
```
팀멤버 조회

근데 팀 가져올 때

```    select
        team0_.id as id1_7_0_,
        team0_.created_at as created_2_7_0_,
        team0_.updated_at as updated_3_7_0_,
        team0_.code as code4_7_0_,
        team0_.name as name5_7_0_ 
    from
        team team0_ 
    where
        team0_.id=?
``` 
팀 나감

2022-09-22 12:32 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
>          return TeamResponse.from(findFirstTeamMember(memberId, teamMembers).getTeam());
👍 반영 완료

2022-09-28 04:29 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> +    void closeAllByIds(@Param("ids") List<Long> ids);
까라 쫌 치네~

2022-09-28 04:31 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
> +        List<TeamMember> teamMembers = teamMemberRepository.findAllByMember(member);
어떻게 반박했는지도 알려주세요~

2022-09-28 04:31 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
>                                  CustomErrorCode.TEAM_MEMBER_MISMATCHED_ERROR,
어떻게 반박했는지도 알려주세요~

2022-09-28 04:53 UTC, leo0842 approved these changes
고생 많으셨어요~!!

2022-09-28 04:53 UTC, leo0842 commented on backend/src/main/java/com/morak/back/team/domain/TeamMemberRepository.java
> +    Optional<TeamMember> findFirstByMemberOrderByIdAsc(@Param("member") Member member);
C: 이거는 쿼리가 어떻게 나가나요??

2022-09-28 05:02 UTC, RIANAEH requested changes
객체 기반 조회, 배치, 패치 조인 관련해서 모두 잘 적용해주셨네요💯
몇가지 궁금한점 코멘트 남겨봤어요:)

추가적으로 poll도 appointment와 마찬가지로 `closed_at`에만 인덱스를 걸고 있는거죠?
인덱스 이름을 `index_poll_closed_at`과 `index_appointment_closed_at`으로 바꿔보면 좋을 것 같아요. 어떤 컬럼에 대한 인덱스인지 바로 알기 어렵더라구요!

2022-09-28 10:41 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> +    Optional<Poll> findFetchedByCode(@Param("code") String code);
애초에 `findByXXX` 라는 네이밍을 보면 `find` 와 `By` 사이에 대상 객체에 대한 이름이 숨겨져 있는 걸 알 수 있는데요 (e.g. `findPollByCode`) 여기서 숨겨진 객체에다가 `fetched` 라는 수동태를 붙였다고 보시면 될 것 같습니다 (`findPollFetchedByCode`)

2022-09-28 10:41 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/PollItemRepository.java
> +    List<PollItem> findAllByIds(@Param("ids") List<Long> ids);
띠용? 삭제했습니다

2022-09-28 10:41 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
> +        );
반영했습니다 👍

2022-09-28 10:44 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/domain/TeamMemberRepository.java
> +    List<TeamMember> findAllByTeam(@Param("team") Team team);
이 부분은 기존과 좀 다른 케이스인데요. `fetched`를 붙였던 이유는, 두 개의 메소드가 동일한 행위(객체를 찾아오는)를 하지만 하나는 N+1 문제를 해결하기 위해 fetch를 붙여오고, 다른 하나는 사용처에서 N+1 문제가 발생하지 않기 때문에 fetch를 사용하지 않기 때문에 이를 구분하고자 하는 목적이었어요.

하지만 TeamMembeRepository에서 위 메소드들은 모두 N+1 문제가 발생하기 때문에 딱히 구분할 필요가 없었기에 붙이지 않았구요. JPA의 장점이 객체 탐색을 자유롭게 할 수 있다는 점이었는데, 이렇게 N+1문제 때문에 여러 메소드가 나오게 되는 경우 때문에 기존 Dao에서 발생하던 문제(같이 가져오는 객체에 따라 메소드 이름을 다르게 여러개 만들어주어야 하는 것)가 다시 발생하니 마음이 아프네요 ㅠ.

2022-09-28 10:45 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/domain/TeamMemberRepository.java
> +    Optional<TeamMember> findFirstByMemberOrderByIdAsc(@Param("member") Member member);
반영했습니다

2022-09-28 10:45 UTC, cjlee38 commented on backend/src/test/resources/application.yml
> +        default_batch_fetch_size: 1000
100 정도의 작은 숫자로 처리해도 되긴 하지만, 너무 적은 숫자일때는 문제가 될 가능성이 있지만(e.g. Team 하나에 Member가 101명 인 경우?), 큰 숫자일때는 어떤 문제가 발생할지 잘 모르겠네요.

2022-10-09 12:06 UTC, leo0842 approved these changes
댓글만 확인해주시고 머지하면 될 것 같아요~!

2022-10-09 12:06 UTC, leo0842 commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> +    void closeAll(@Param("polls") List<Poll> polls);
여기도 통일성있게 `Iterable<Poll>` 이 좋을 것 같아요!

2022-10-09 12:06 UTC, leo0842 commented on backend/src/test/java/com/morak/back/team/domain/TeamMemberRepositoryTest.java
> +        assertThat(deletedTeamMember).isNull();
entity manager 를 사용한 이유가 궁금합니다!!

2022-10-09 13:24 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/team/domain/TeamMemberRepositoryTest.java
> +        assertThat(deletedTeamMember).isNull();
id 값을 기준으로 조회하려는데 기존에 id 기반으로 조회하는 부분이 없어서 entity manager를 활용했는데, 다시 보니까 team과 member로 조회할 수 있네요. 수정했습니다 :)

2022-10-09 13:24 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> +    void closeAll(@Param("polls") List<Poll> polls);
반영했습니다 :)

2022-10-09 13:26 UTC, seong-wooo approved these changes

2022-10-11 00:58 UTC, RIANAEH approved these changes

2022-10-11 23:23 UTC, merged