feat(auth): 본인 이름 변경 API 구현
woowacourse-teams/2022-mo-rak pull request #422
Opened 2022-10-02 11:20 UTC by RIANAEH

## 상세 내용
본인 이름을 변경할 수 있는 API를 구현했어요. -> ` PATCH /api/auth/me/name`

기존에 본인을 조회할 수 있는 API가 있었는데 API 명세에는 없더라구요. 이 부분 수정했습니다!

Close #420

2022-10-02 11:37 UTC, cjlee38 requested changes
코드가 깔끔해서 특별히 코멘트할 부분이 없네요 :) 수고하셨습니다 ~

2022-10-02 11:37 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/auth/application/OAuthService.java
> +        memberRepository.flush();
c: flush를 추가한 이유는 무엇일까요 ? 만약 validator에 의해 발생하는 문제를 대비한다면, 도메인 재설계를 대비해 검증 메소드를 미리 추가하는 것도 방법일 것 같네요

2022-10-02 11:50 UTC, leo0842 approved these changes
수고하셨습니다~

2022-10-02 11:50 UTC, leo0842 commented on backend/src/main/java/com/morak/back/auth/application/OAuthService.java
> +        memberRepository.flush();
> 

이 부분에 대해서 엘리와 이야기를 해봤습니다~ 

1. valid annotation 을 떼고 setter에 검증 로직을 넣을지, 
  a. 이러면 사실상 생성자와 setter 두 군데에서 중복되는 로직이 발생
2. valid annotation 을 떼고 change 시 new entity 를 생성할지,
3. 현재의 valid annotation 을 가지고 가면서 flush 로 명시할지

위의 방안들을 구상해봤는데요, valid annotation 을 굳이 뗄 필요가 없다고 생각했고, 가장 깊은 곳에서의 valid 이기때문에 검증 시점도 괜찮다고 판단하였습니다.

2022-10-03 08:36 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/auth/application/OAuthService.java
> +        memberRepository.flush();
name이라는 값 객체를 만들어서 값 객체를 통해 수정하도록 하면 검증을 한 곳에서 할 수 있을 것 같아요.
Member 전체에 대한 도메인 수정은 너무 많으니까 일단 name에 대해서만 수정하면 어떨까요?

2022-10-18 11:22 UTC, merged