feat: tooltip 컴포넌트 구현
woowacourse-teams/2022-mo-rak pull request #423
Opened 2022-10-02 11:30 UTC by rladpwl0512

## 상세 내용
### 사용 예제

```tsx
<Tooltip text="오전 12:00 ~ 오전 12:00(다음날)은 하루종일을 의미합니다." width="26" variant="right">
  <StyledHelpIconWrapper>
    <StyledHelpIcon src={Question} alt="help-icon" />
  </StyledHelpIconWrapper>
</Tooltip>
```

### props 설명
```tsx
// children: children을 클릭하면 tooltip 컨텐츠가 나온다. (tooltip 컨텐츠의 트리거)

interface Props extends PropsWithChildren {
  text: string; // tooltip 컨텐츠에 들어가는 내용
  width: string; // tooltip 컨텐츠 넓이 
  variant: 'top' | 'bottom' | 'left' | 'right'; // tooltip 컨텐츠 위치
  fontSize?: string; // tooltip 컨텐츠 내용의 폰트 사이즈 (기본은 1rem)
  fontColor?: string; // tooltip 컨텐츠 내용의 폰트 색상 (기본은 black)
  backgroundColor?: string; // tooltip 컨텐츠 박스의 색상 (기본은 theme.colors.PURPLE_50)
}
```

- `children`: children을 클릭하면 tooltip 컨텐츠가 나온다. (tooltip 컨텐츠의 트리거)
- `variant` (tooltip 컨텐츠 위치)
    - top
![image](https://user-images.githubusercontent.com/52344833/193451466-185462ac-0cbc-49ad-a80a-1abd10500ff6.png)

        
    - bottom
![image](https://user-images.githubusercontent.com/52344833/193451473-d2c3439a-8f88-4da6-9dda-03785bcca986.png)

        
    - right
![image](https://user-images.githubusercontent.com/52344833/193451483-c4b7a922-9a2b-4abd-ac2c-00a74ef5ee00.png)

        
    - left
![image](https://user-images.githubusercontent.com/52344833/193451487-caba6304-5a83-4c48-a5d8-96a4b56d7314.png)

        

### 공유 사항

- 자세한 구현 과정은 일지를 참고해주세요.
- (위 캡처본 참고) 현재 `variant = top | bottom`에 대한 수평정렬은 잘 이루어졌지만, `variant = left | right`에 대한 수직정렬은 이루어지지 않았습니다. 😓 생각보다 시간이 걸려서, 일단 리뷰 요청 보냅니다. 이 부분은 계속해서 수정하면서 해결해보겠습니다!
- 제가 생각했을 때, 툴팁이 필요한 부분은 아래와 같습니다.
    1. [투표하기 결과페이지] 투표자 description에 대한 설명 
    2. [약속잡기 생성 페이지] ‘가능 시간 제한 설정’에 대한 설명
    3. [마감 전 약속잡기 결과페이지] 공동 1등이 나왔을 때 재투표가 가능하다는 것에 대한 설명 
    4. [마감 후 약속잡기 결과페이지] 공동 1등에 대한 재투표 만들기 버튼에 대한 설명 
    5. [슬랙 채널 연동 모달] 연동하는 방법에 대한 설명 
    
    하지만 현재 pr에서는 2, 4번에 대해서만 구현을 했습니다. 리뷰 후 현재 구현한 tooltip 컴포넌트가 괜찮으면 나머지는 따로 이슈를 파서 구현하겠습니다. 위 다섯가지 이외에 tooltip이 필요한 부분이 있다면 함께 이야기해보면 좋을 것 같아요!  
    
    (2, 4번을 구현한 이유는, 어떻게 사용하는지 이해가 잘 안될 수 있을 것 같아서 예시 구현 사례로 넣었놨습니다!)

Close #419

2022-10-02 12:00 UTC, al-bur requested changes
고생했습니다 위니~~

피드백 남겼습니다 확인해주세요 😀😀

2022-10-02 16:25 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +  variant: 'top' | 'bottom' | 'left' | 'right';
맞습니다. 안그래도 이전에 비슷한 코드를 참고하면서 그대로 네이밍을 해주었는데, 적절한 네이밍이 아닌 것 같다고 생각중이였습니다. 정확하게 짚어줘서 감사합니다~!! 
`placement`로 변경했습니다. 

---
[refactor: props명 변경 및 함수명 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/423/commits/828d9d05343ed30014d489602d8e7d8374cb21a2)

2022-10-02 16:29 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +const StyledText = styled.div<CSSProperties>(
오 완전 인정합니다! 
의미가 없는 div, span과 같은 태그는 css 스타일 적용만을 위한 태그 이외에는 쓰지않도록 최대한 지양해야겠네요. 

---
[refactor: 시맨틱 태그를 위한 태그 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/423/commits/f7e3665e0ee16170be4b39228394209a2951d988)

2022-10-02 16:31 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +  width: 1.2rem;
ㅎㅎ😅 height 삭제했습니다 

---
[refactor: 필요없는 css 속성 삭제](https://github.com/woowacourse-teams/2022-mo-rak/pull/423/commits/37a77ad123c929e26d9765835e2f2bc0d142417e)

2022-10-02 16:39 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +      content: " ";
공식문서를 참고하여 구현하면서 작성한 코드인데, 질문주신김에 content 속성값에서의 ""와 " " 의 차이에 대해서 알아보았습니다~
""와 " "로 했을 때, 화면에 차이가 전혀 없더라구요. 공백이 무시되나? 싶어서 찾아보니까 
[stackoverflow 질문](https://stackoverflow.com/questions/5467605/add-a-space-after-an-element-using-after)에 따르면, `content=" "`일 때 공백은 무시된다고 하네요~ 
의미 없는 공백이기때문에 삭제해주었습니다! 
(만약, content로 공백을 넣어주고 싶다면 공백을 의미하는 유니코드를 넣어주거나 추가적인 속성을 설정해준다고 합니다 😄)

---
[refactor: content 속성값 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/423/commits/db6a7fcc0114a51675ee98122873b937fd9b6969)

2022-10-02 16:44 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +    &::after {
`::after` 는 css의 가상 요소입니다. 이미 있는 태그에 대해 css를 통해 가상의 element를 추가해주는 코드입니다. 
예를들어, `div::after`은, 이미 있는 `div` 태그의 뒷부분에 실제 태그가 아닌 가상의 css 스타일이 적용된 element를 추가합니다. 
현재 코드에서는 말풍선 꼬리를 만들어주고있습니다. 
`StyledContentContainer`의 `div` 태그 자체는 텍스트를 담고있는 네모 박스 모양을 만들어주고있고, `::after`를 통해 `div` 끝부분에 말풍선 꼬리 스타일이 적용된 가상의 element를 만들어주고있습니다 :)

2022-10-02 16:46 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +    width: ${width}rem;
<img width="506" alt="스크린샷 2022-10-03 오전 1 46 12" src="https://user-images.githubusercontent.com/52344833/193465899-a9bfb4a9-0a0f-4a02-9bac-f748f1d70be6.png">

슬프게도 위와같이 깨집니다... 원인은 정확히 모르겠지만, 이런 이유로 width를 설정해주었습니다 🥲

2022-10-02 16:54 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +    visibility: ${isVisible? 'visible' : 'hidden'};
일단 둘의 차이는 다음과 같습니다. 
- **display: none** : 요소가 렌더링 되지 않음(DOM에 존재하지 않음), 화면에 공간 차지도 하지 않음
- **visibility: hidden** : 요소가 보이지는 않지만 렌더링 되며 **화면에 공간을 가지고 있음**(DOM에 존재함)
    
즉, 화면에 보이지는 않지만 요소가 화면에 공간 차지는 해야하는 경우에 visibility:hidden을 사용합니다. 
사실 구현 과정에서 공간 차지를 해야하는 일이 있어서 display에서 visibility로 변경해주었던것인데, position을 absolute로 변경해주면서 둘의 ui가 똑같이 보이게 되었습니다 😅 
일단 기존에 display를 사용했던 것 처럼 변경해주었습니다. 

그런데 공부하다 알게된 사실인데, 스크린 리더기에서는 `display: none`, `visibility: hidden`으로 숨긴 요소는 읽어들이지 못한다고 하네요 🥲 이후에 `display: none`으로 적용했던 부분들을 한번에 바꾸는게 좋을 것 같습니다 :) 

---
[refactor: visibility -> display로 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/423/commits/8dee667cc74e194585fbafc595f956917e470dd5)

2022-10-02 16:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +  z-index: 1;
`z-index: 1` 을 설정해주지 않으면, 다른 요소들이 더 위로 올라오게되어서 z-index를 설정해주었습니다~

2022-10-02 16:57 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +  width: string;
https://github.com/woowacourse-teams/2022-mo-rak/pull/423#discussion_r985226661 
참고해주세요 🥲

2022-10-02 17:01 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +  text: string;
그러네요! Tooltip 컴포넌트의 입장에서 생각하면 앨버 말처럼 content가 적절할 것 같아요~
더하여, 지금 코드에서 `StyledContentContainer` 으로 표현해준 것 처럼, `content`로 변경하는 것이 더 좋을 것 같아요~ 

---
[refactor: props명 변경 및 컴포넌트명 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/423/commits/1467c3b9c74d81a88acd63987b7a8073aaf7548a)

2022-10-02 17:03 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +function Tooltip({children, variant, width, backgroundColor, text, fontSize, fontColor}: Props) {
prettier가 계속 적용되지 않아서 생긴 문제였는데, prettier가 되도록 고치면서 수정되었습니다~! 🤣

2022-10-02 17:03 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +        <StyledText fontSize={fontSize} color={fontColor}>{text}</StyledText>
https://github.com/woowacourse-teams/2022-mo-rak/pull/423#discussion_r985227896 
참고해주세요 :)

2022-10-02 17:06 UTC, rladpwl0512 commented
꼼꼼한 리뷰 감사합니다! 리뷰 반영 후 커멘트 남겼는데 의아한 부분 있음 또 남겨주세요 🔥

2022-10-03 08:50 UTC, al-bur commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +      content: " ";
상세한 설명 감사합니다!

2022-10-03 08:51 UTC, al-bur commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +    &::after {
오 css의 가상 요소가 이런거군요ㅎㅎ이해했습니다!

2022-10-03 09:44 UTC, al-bur commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +    visibility: ${isVisible? 'visible' : 'hidden'};
좋습니다~~ display:none을 어떤 것으로 바꿔야할지 궁금해지네요

2022-10-03 09:44 UTC, al-bur commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +    width: ${width}rem;
찾아봐야겠네요!!

2022-10-03 09:46 UTC, al-bur approved these changes
고생하셨습니다 위니~

2022-10-03 09:48 UTC, rladpwl0512 commented on frontend/src/components/@common/Tooltip/Tooltip.tsx
> +    width: ${width}rem;
네 todo로 등록해놓겠습니다~

2022-10-03 09:51 UTC, merged