feat(team): 본인을 member list 에서 가장 앞에서 나오도록 변경
woowacourse-teams/2022-mo-rak pull request #424
Opened 2022-10-02 11:40 UTC by leo0842

## 상세 내용
팀 조회시 팀에 속한 멤버 리스트를 반환하는데, 이 때 본인이 가장 먼저 나오도록 수정했습니다~

Close #421

2022-10-03 05:19 UTC, cjlee38 requested changes
안녕하세요 에덴~ 코멘트 남겼으니 확인해주세요~

사소하지만 member를 정렬하느냐 member response를 정렬하느냐도 한번 생각해볼 수 있었을 것 같은데, 혹시 이유가 있다면 말씀해주세요 ~ (없다면 말씀 안해주셔도 괜찮을 것 같습니다~)

2022-10-03 05:19 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
> +
r: 아마 stream 을 끊지 않고 구현하고자 이러한 형태가 나온 것이라고 추측되는데요 ! sorted()를 사용하는 편이 조금 더 나을 것 같습니다. 왜냐하면, 1. reduce의 사용법 자체가 이러한 의도가 아니고, 2. stream은 자체적으로 생성하는데 비용이 적지 않기 때문입니다.

sorted()를 한번 적용해보면서 겸사겸사 짤막한 성능 테스트도 해보았습니다. 아래 코드를 확인해주세요 ~

```java
@Test
    void test() {
        Member member = new Member(2L, "oauthId-2", "name-2", "profile-url-2");
        List<Member> members = List.of(
                new Member(1L, "oauthId-1", "name-1", "profile-url-1"),
                member,
                new Member(3L, "oauthId-3", "name-3", "profile-url-3"),
                new Member(4L, "oauthId-4", "name-4", "profile-url-4")
        );

        long sum = 0;
        long iter = 10;
        for (int i = 0; i < iter; i++) {
            long start = System.nanoTime();
//            List<MemberResponse> result = wayA(member, members); // 253820
            List<MemberResponse> result = wayB(member, members); // 128412

            long elapsed = System.nanoTime() - start;
            sum += elapsed;
        }

        System.out.println("sum / iter = " + sum / iter);
    }

    private List<MemberResponse> wayB(Member member, List<Member> members) {
        return members.stream()
                .sorted((Member o1, Member o2) -> {
                    if (o1.equals(member)) {
                        return -1;
                    }
                    return 1;
                })
                .map(MemberResponse::from)
                .collect(Collectors.toList());
    }

    private List<MemberResponse> wayA(Member member, List<Member> members) {
        Stream<Member> identity = Stream.of();
        List<MemberResponse> result = members.stream()
                .reduce(identity, (memberStream, m) -> moveMeToFirst(memberStream, m, member), Stream::concat)
                .map(MemberResponse::from)
                .collect(Collectors.toList());
        return result;
    }

    private Stream<Member> moveMeToFirst(Stream<Member> memberStream, final Member member, Member me) {
        if (member.equals(me)) {
            return Stream.concat(Stream.of(member), memberStream);
        }
        return Stream.concat(memberStream, Stream.of(member));
    }
```

2022-10-03 16:20 UTC, leo0842 commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
> +
sorted 를 생각 못하고 어렵게만 생각하다보니 reduce 를 사용하게 되었네요 😢 
차리의 피드백대로 sorted 로 변경하였습니다!

그리고 member 를 정렬할지, memberResponse 를 정렬할지에 대해 생각을 해보았는데, 직관적으로는 view 로직이기때문에 memberResponse 를 정렬하는 것이 더 적절해보이지만, 일반적인 sort 와는 다르게 `본인` 이라는 변수가 추가되어 compare 하는 로직을 memberResponse 객체 내부로 넣을 수가 없었습니다. 따라서 sorted 하는 로직이 member 와 memberResponse 모두 service 에서 동작하여야 하고 `본인` 이라는 로직은 member 와 더 관련이 있기때문에 member 로 sorting 하기로 하였습니다.

이와 관련하여 차리의 의견도 여쭙고 싶습니다~!

2022-10-09 13:05 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/team/application/TeamService.java
> +
저는 response에서 정렬하는 것이 맞다고 생각이 드네요. 
이 `findMembersInTeam` 메소드 자체는 팀에 속한 멤버들의 목록을 전달해주는 것만이 목적인 것 같아요.
사실 정렬할 필요는 없고 원하는 member가 첫 번째에 존재하면 되는거잖아요 ? 
그럼 `Controller`에서 순서만 변경해주는 것은 어떨까요?
Controller에서 member의 id를 알고 있으니까 service에서 나온 결과를 이용해서 순서만 변경해주면 될 것 같은데요?

2022-10-18 12:57 UTC, merged