feat: 메인페이지 UI 개선
woowacourse-teams/2022-mo-rak pull request #430
Opened 2022-10-08 02:23 UTC by rladpwl0512

## 상세 내용
 메인페이지 UI를 개선하고, 메뉴 각각에 대한 컴포넌트도 분리해주었습니다. 

Close #429

2022-10-08 08:15 UTC, RIANAEH commented
UX/UI 천재 김위니😎

2022-10-09 10:23 UTC, al-bur requested changes
![9d07a0d61c46aa5fc59bd25097c35b1cf43ad912ad8dd55b04db6a64cddaf76d](https://user-images.githubusercontent.com/64825713/194751402-a389fc96-29b6-4c58-8286-d9177c11386f.gif)

위니 고생했습니다~~ (베이비 어피치 등장😀)

일단, 개선된 UI 너무 이쁜 것 같아요!!
작성하신 코드에 대해서는 리뷰 남겼고요~

모든 것은 저의 의견이니, 위니의 의견도 마음껏 답글로 달아주세요!

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.style.tsx
> +  height: 10rem;
height도 같이 설정해줘야하나요?

이 부분은 layout shift가 일어나지 않나요?

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
> +        <MainFeatureMenu onClick={() => alert('준비중입니다.')} menu="역할 정하기" menuImg={Role} />
이거는 컨벤션으로 정했는 지는 모르겠는데,

익명 함수보다는 기명함수를 선언해서 사용해주면 좋을 것 같아요~

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +  menu: string;
타입을 좁혀보면 어떨까요?

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +  onClick: () => void;
click에 대한 이벤트 핸들러이니 React에서 제공하는 이벤트 핸들러 타입을 사용해보면 어떨까요?

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +        <StyledFeatureMenuName>{menu}</StyledFeatureMenuName>
menu보다는 name이 더 적절할 것 같은데 어떨까요???

해당 컴포넌트를 사용하는 곳에서 menu를 봤을 때, 이게 menu의 이름으로 사용되는 지는 잘 모를 것 같아요
name으로 해놓으면 `메인 기능 메뉴`에서 이름을 담당하는 prop이구나!라고 이해할 수 있을 것 같아요😀

위니의 생각은 어떨까요?

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +      <StyledImageWrapper>
두 개 이상의 children을 가지고 있는데, wrapper 괜찮을까요?

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +    <StyledFeatureMenuContainer onClick={onClick}>
StyledFeatureMenuContainer라고 다 명시하는 것보다, StyledContainer라고 해도 괜찮을 것 같은데 어떻게 생각하시나요??

이미 MainFeatureMenu라는 컴포넌트라서, FeatureMenu라는 것을 한 번 더 넣어줘야할까라는 생각이 드네요!!
그러한 이유에서, 현재, 대부분의 컴포넌트에서 StyledContainer로 사용하고도 있고요!

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +        <StyledFeatureMenuName>{menu}</StyledFeatureMenuName>
StyledFeatureMenuName,  여기도 FeatureMenu가 없어도 되지 않을까 합니다~

2022-10-09 10:23 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
여기는 일부러 한 칸 띄워주신건가요??

2022-10-10 06:38 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.style.tsx
> +  height: 10rem;
작성 과정에서 height를 지우니 깨지는 부분이 생겨서 넣어주었었는데, height 지워도 잘 되네요 🤔
이 부분에서 layoutshift는 일어나지 않습니다 :) 
height 부분은 지워주었어요. 

---
[refactor: 필요없는 style 속성 삭제](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/d9366f26f07d942777d9f4e2265df0fbb1847de5)

## lighthouse 
![스크린샷 2022-10-10 오후 3 29 41](https://user-images.githubusercontent.com/52344833/194808960-551be5a1-d212-4129-a419-f4c3f6749d2b.png)

(LCP는 h1 제목인데, 큰 문제가 없어보이는데 뭘까요 😵‍💫)
![스크린샷 2022-10-10 오후 3 32 00](https://user-images.githubusercontent.com/52344833/194809232-a66cc721-e1b2-4945-afd2-c1cac9a7b375.png)
찾아보았지만 해결하지 못했네요. 성능이 나쁘지 않기 때문에, 일단 이 부분은 잠시 스킵하겠습니다 😅

2022-10-10 07:05 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
> +        <MainFeatureMenu onClick={() => alert('준비중입니다.')} menu="역할 정하기" menuImg={Role} />
넵 동의합니다~ 이부분은 금방 지워줄거라고 생각되어서, 임의로 넣어주었습니다 😅 
그래도 코드를 깨끗하게 유지해주는 것도 중요할 것 같아서 바~로 변경해주었습니다. 

---
[refactor: 익명함수를 기명함수로 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/e73f6fdf900037232da63ab0d20c48a04c785a1f)

2022-10-10 07:10 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +  menu: string;
너무 넓게 선언했네요! 수정했습니다~ 
---
[refactor: props에 대한 타입 선언 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/db0b76364f9db89df39ec74227f75a05b6349939)

2022-10-10 07:11 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +  onClick: () => void;
react에서 제공해주는 `MouseEventHandler` 를 사용하는 것으로 수정했습니다 :) 

---
[refactor: props에 대한 타입 선언 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/db0b76364f9db89df39ec74227f75a05b6349939)

2022-10-10 07:20 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
네~ 다른 영역임을 명확하게 나타내기 위해 가독성을 위해 띄워주었습니다! 
사실 컴포넌트 내부에서 구분이 필요하다는걸 다시 생각해보니, 현재 컴포넌트 분리가 제대로 이루어지지 않은걸수도 있겠네요...!
투표 메인페이지, 약속잡기 메인페이지처럼 요 페이지도 크게 header (title 부분) / menu 부분으로 나누었어야할까요? 
다른 컴포넌트처럼 title을 외부로 빼주는게 나을까 싶기도 해요. 🤔 
앨버의 의견은 어떠신가요? 

**전**
```jsx
function MainPage() {
  return (
    <StyledContainer>
      <MainFeatureMenuContainer />
    </StyledContainer>
  );
}
```

**후**
```jsx
function MainPage() {
  return (
    <StyledContainer>
      <MainFeatureMenuHeader />
      <MainFeatureMenuContainer />
    </StyledContainer>
  );
}
```

2022-10-10 07:25 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +        <StyledFeatureMenuName>{menu}</StyledFeatureMenuName>
항상 컴포넌트 입장에서 props명을 짓는다는게 어렵네요 😅
앨버 말처럼 `MainFeatureMenu` 컴포넌트의 입장에서 menu를 봤을 때 이게 메뉴 이름인지 알기 힘들겠네요. 
name으로 변경하면 좋을 것 같아요! 
menuImg도 컴포넌트 입장에서 생각해봤을 때, img로 들어오더라도 '메뉴에 대한 이미지구나!' 라고 생각이 들 것 같아서, menuImg -> img로 수정했어요 :)

---
[refactor: props명 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/8934fefc4d40ebea4322ac6971e0fa99b3f9b14a)

2022-10-10 07:30 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +      <StyledImageWrapper>
아고 이전 코드에서 Container, Wrapper였던 것을 컴포넌트 분리해주면서 수정하지 않았네요 😱
수정했습니다. 

---
[refactor: 컴포넌트명 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/887d6f8e83de3d69790670ec35bb1d918ccfd764)

2022-10-10 07:36 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +    <StyledFeatureMenuContainer onClick={onClick}>
완전 동의합니다. 컴포넌트 내부의 컴포넌트니까, 컴포넌트명과 중복되는 부분들은 지워주는게 맞다고 생각해요! 
이 부분은 예전에 이야기했던게 생각나네요 😅 
수정했습니다. 

---
[refactor: 컴포넌트명 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/814c44583cdeafad272f157f85dc026b4afb56dd)

2022-10-10 07:37 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +        <StyledFeatureMenuName>{menu}</StyledFeatureMenuName>
위와 같이 변경했습니다. 

---
[refactor: 컴포넌트명 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/814c44583cdeafad272f157f85dc026b4afb56dd)

2022-10-10 07:40 UTC, rladpwl0512 commented
앨버~🐝 
꼼꼼한 리뷰 고마워요! (어피치도 넘 큐티하네요. 드디어 어피치의 귀여움을 인정한건가요? 🍑 뿌듯)
이번에는 한번 더 검토하는 것을 잊고 pr을 제출했나봐요... 이번에 특히 자잘자잘한 실수가 많았네요 🥲 반성중입니다  
특히 컴포넌트명에 대한 리뷰가 많았는데, 앞으로 더 고민해봐야겠어요! 

리뷰 반영 및 의견이 필요한 부분들을 대댓글로 달았어요. 확인해주세요~

2022-10-10 09:16 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.style.tsx
> +  height: 10rem;
좋습니다~ 확인까지 해주셨네요!!

2022-10-10 09:16 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +  onClick: () => void;
좋습니다~

2022-10-10 09:17 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
> +        <StyledFeatureMenuName>{menu}</StyledFeatureMenuName>
맞아요 사실 이것도 지금은 이게 맞는 것 같은데, 또 다음에 보면 다른 게 좋은 것 같이 느껴질 수도 있을 것 같아요!! 이런 부분이 조금 어려운 것 같습니다ㅎㅎ

2022-10-10 09:19 UTC, al-bur commented on frontend/src/pages/MainPage/components/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
`후` 방법 좋은 것 같아요!!

페이지 컴포넌트는 딱 화면을 봤을 때, 구분되는 것들을 하나의 컴포넌트로 보고 지금까지 해왔다고 생각해서요!! 일관성있게 해줘도 좋을 것 같습니다 😀

2022-10-10 09:29 UTC, rladpwl0512 commented on frontend/src/pages/MainPage/components/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
[refactor: 컴포넌트 분리](https://github.com/woowacourse-teams/2022-mo-rak/pull/430/commits/eaba66dc12ad5171e7c6313359f2f881376f5596) 
반영 완료~🔥🔥
(TODO 주석도 이후 커밋에서 지웠습니다~)

2022-10-10 09:35 UTC, rladpwl0512 commented
추가 리뷰 반영했습니다~ 
https://github.com/woowacourse-teams/2022-mo-rak/pull/430#discussion_r991077954 

확인해주세요 🥳

2022-10-10 09:45 UTC, al-bur approved these changes
고생했습니다 위니~~😀

2022-10-10 09:52 UTC, merged