refactor(appointment): appointment 도메인 재설계
woowacourse-teams/2022-mo-rak pull request #438
Opened 2022-10-11 13:55 UTC by seong-wooo

## 상세 내용

현재는 appointment 패키지만 살펴보시면 될 것 같아요!

Close #379

2022-10-12 16:20 UTC, leo0842 requested changes
일단 간단하게 해봤어요 내일 한번 더 볼게요

2022-10-12 16:20 UTC, leo0842 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    }
```suggestion
this.availableTimes.removeIf(availableTime -> availableTime.getMember().equals(member));
for (LocalDateTime dateTime : localDateTimes) {
    validateSelectTime(now, dateTime);
    AvailableTime availableTime = AvailableTime.builder().member(member).startDateTime(dateTime).build();
    this.availableTimes.add(availableTimes);
}
```

은 어떤가요??

2022-10-12 16:20 UTC, leo0842 commented on backend/src/main/java/com/morak/back/appointment/domain/AppointmentTime.java
> +    private final LocalDateTime startDateTime;
13줄과 14줄 사이 인덴트!

2022-10-12 16:20 UTC, leo0842 commented on backend/src/main/java/com/morak/back/appointment/domain/Date.java
> +    }
둘은 어떤 차이인가요??

2022-10-13 04:04 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +                LocalDateTime.now() // todo : injection
네 맞습니다

2022-10-13 05:25 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/Date.java
> +    }
32번 줄에 `this.date.`을 생략하려는 의도가 있었는데 깜빡했네요.
Date 형식, LocalDate 형식 둘 다 처리하고 싶어서  메서드를 2개 만들었습니다.
로직상의 차이는 없습니다.

2022-10-19 11:37 UTC, closed without merging