refactor(poll): 도메인 재설계를 한다.
woowacourse-teams/2022-mo-rak pull request #439
Opened 2022-10-11 15:12 UTC by leo0842

## 상세 내용

아직 이식은 하지 않았고 해피케이스 테스트만 진행하였습니다.

많은 관심 바랍니다.

Close #416

2022-10-11 16:59 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/brandnew/service/NewPollService.java
> +        return pollRepository.save(poll).getPollInfo().getCode();
```suggestion
        pollRepository.save(poll);
        return poll.getCode();
```

2022-10-11 16:59 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/brandnew/service/NewPollService.java
> +        return pollRepository.save(poll).getPollInfo().getCode();
이게 더 보기 편할 듯 하네요

2022-10-11 16:59 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/brandnew/service/NewPollService.java
> +                .map(pollItem -> PollItemResultResponse.of(pollItem, poll.getPollInfo().getAnonymous()))
여기도 getter 두 번 쓰지말고 한 번만 쓰도록 변경하는 것이 좋을 것 같아요!

2022-10-11 16:59 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/brandnew/domain/NewPollItem.java
> +    }
```suggestion
      @Builder
    private NewPollItem(Long id, String subject, SelectMembers selectMembers) {
        this.id = id;
        this.subject = subject;
        this.selectMembers = selectMembers;
    }
```

생성자를 하나로 만들죠!

2022-10-11 16:59 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/brandnew/domain/PollItems.java
> +    }
```suggestion
        public void doPoll(Member member, Map<NewPollItem, String> data) {
        Set<NewPollItem> newPollItems = data.keySet();
        values.removeAll(newPollItems);
        for (NewPollItem pollItem : values) {
            pollItem.remove(member);
        }
        for (NewPollItem newPollItem : newPollItems) {
            newPollItem.addSelectMember(member, data.get(newPollItem));
        }
        values.addAll(newPollItems);
    }
```

PollItems가 갖고 있는 NewPollItem들의 자료형이 Set으로 바뀐다면 이런 식으로도 가능할 듯 하네요

2022-10-19 07:55 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/SelectMembers.java
> +    @MapKeyJoinColumn(name = "member_id")
### MapKeyJoinColumn vs. MapKeyColumn

MapKeyJoinColumn
> Specifies a mapping to an entity that is a map key. The map key join column is in the collection table, join table, or table of the target entity that is used to represent the map. If no MapKeyJoinColumn annotation is specified, a single join column is assumed and the default values apply.

MapKeyColumn
> Specifies the mapping for the key column of a map whose map key is a basic type. If the name element is not specified, it defaults to the concatenation of the following: the name of the referencing relationship field or property; "_"; "KEY".

key인 Member가 Entity이기 때문에 MapKeyJoinColumn을 사용해야 이름이 적용됩니다. 
역할 도메인에서의 RoleName은 값 객체이기 때문에 MapKeyColumn을 사용했던 것이었습니다.

2022-10-19 14:27 UTC, cjlee38 requested changes
고생하셨습니다~

도메인쪽만 빠르게 피드백 남겨보았습니다. 여유 되면 애플리케이션/테스트 쪽도 살펴볼게요 :)

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +        }
r: 이 검증 로직은 `PollItems` 객체가 맡는게 더 자연스러울 것 같아요

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/SelectMembers.java
> +    private Map<Member, String> values;
c: `PollInfo` 에서는 호스트를 Long 값으로 다루었는데, 여기서는 Member를 직접 들고 있어야 하나요? Member를 찾아서 내려주는 일은 application layer에 맡기는게 낫지 않을까요 ?

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/SelectMembers.java
> +public class SelectMembers {
a: 이 부분은 전에 에덴한테도 한번 했던 이야기인데요. `SelectMembers`가 하는 일이 거의 없는 것 같아요. `PollItem`이 그저 `SelectMembers`에게 메소드를 전달하는 역할만 하고 있기만 하는데, `PollItem`이 직접 처리하면 어떨까요 ?

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/PollInfo.java
> +    }
r: 자기 자신만 사용하는 메소드인데 public으로 열려있네요. 아마 이 부분은 `AllowedCount`가 `PollItems` 쪽으로 이동하면 깔끔하게 해결될 것으로 보여요.

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/PollInfo.java
> +        validateClosedAt(closedAt);
r: `validate`의 주체가 `PollInfo`여야 할까요 ? 종료 시각이 미래인지 과거인지를 검증하는 행위는 `closedAt` 객체가 판단해도 되지 않을까요 ?

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/SystemDateTime.java
> +    private LocalDateTime now;
r: `beforeNow()`와 같은 메소드 때문에 `@Transient`로 들고 있는 것 같은데, `SystemDateTime`이 스스로 판단하게 하면 변수를 할당할 필요가 없을 것 같아요.

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/application/dto/PollResultRequest.java
> +    }
r: toPollItem으로 바꿔줘야할 이유가 없는 것 같아요. 현재 `addOrRemove` 메소드는 다음과 같은데요

```java
private void addOrRemove(PollItem pollItem, Member member, Map<PollItem, String> data) {
        if (data.containsKey(pollItem)) {
            ...
        }
}
```

아래와 같이 바꿨을 때 문제가 될 수 있을까요 ?

```java
private void addOrRemove(PollItem pollItem, Member member, Map<Long, String> data) {
        if (data.containsKey(pollItem.getId())) {
            ...
        }
}
```

2022-10-19 14:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +        return pollItems.countSelectMembers();
c: 생각해보니 만약 프론트에서 `count` 가 필요없어지게 된다면 도메인 로직을 수정해야 하네요. 이 부분은 저희쪽도 고쳐야 할 것 같아요.

2022-10-20 06:49 UTC, RIANAEH requested changes
안녕하세요 까리😎
복잡한 로직이었을 텐데 리팩토링 잘 해주셨네요:)

아직 정확하게 다 파악한 것은 아닌 것 같아 1차 리뷰 남기고
이후에 더 살펴보겠습니다! (sooooo hard)

2022-10-20 06:49 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/DurationMinutes.java
>      private static final int DAY_MINUTES = 1440;
C: 시간과 관련된 상수들을 enum으로 관리해보면 어떨까요?

2022-10-20 06:49 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/domain/RecommendationCellTest.java
> +                .closedAt(now.plusDays(1));
R: 쓰고 있지 않는 것 같네요~

2022-10-20 06:49 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/appointment/ui/AppointmentControllerTest.java
>                  .header("Authorization", "bearer access.token"));
C: todo 왜 지우셨어요~ 하면 좋을 것 같은디!

2022-10-20 09:58 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentCreateRequest.java
> +                .hostId(hostId)
그렇네용. service 쪽에서 처리하도록 수정했습니다

2022-10-20 10:00 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    private Menu menu;
미리 공유하지 못했네요.`@Delegate` 어노테이션으로는 getter만 사용하기로 했습니다.

2022-10-20 10:01 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
> +                }, teamCode, appointmentCode);
넵 반영했습니다!

2022-10-20 11:56 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
>      }
수정하다 머리아파서 일단 잠깐 홀드시켜놓을게요..

2022-10-20 11:57 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/DurationMinutes.java
>      private static final int DAY_MINUTES = 1440;
잘 이해가 안되서 그러는데 어디서 enum을 활용할 수 있을까요 ?

2022-10-20 12:19 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/poll/domain/PollItems.java
> +    private List<PollItem> values;
NPE 조심!

2022-10-20 12:19 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/poll/domain/PollInfo.java
> +        return itemCount >= 1 && isAllowedCountLessThan(itemCount);
`return itemCount >= 1 && isAllowedCountLessThan(itemCount);`
이 한줄을 두 개의 조건으로 나누기 보다는 하나의 메서드에서 둘 다 확인해주는 것이 좋지 않을까요?
`return isAllowedCount(itemCount)` 이런 느낌?

2022-10-25 06:37 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +        validateExistItem(data.keySet());
하핫 status로 변경했습니다!

2022-10-25 06:41 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/AllowedCount.java
> +public class AllowedCount {
동의합니다. 관련 로직도 PollItems로 이동시켰습니다.

2022-10-25 06:50 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +        }
저는 PollItems에게 "선택한 투표 항목이 포함되어있니?"라고 물어보고 그 결과를 이용해 검증을 진행했기 때문에 괜찮다고 생각했어요. 그리고 이 검증을 PollItems에게 넘기면 Poll의 id까지 넘겨야할 것 같아요🥲

2022-10-28 11:51 UTC, seong-wooo approved these changes
다들 진짜 고생했어요

2022-10-28 11:52 UTC, cjlee38 approved these changes
몹 프로그래밍으로 개발 진행하였습니다.

2022-10-28 11:52 UTC, merged