feat: 랜딩페이지 모바일 사이즈 대응
woowacourse-teams/2022-mo-rak pull request #443
Opened 2022-10-13 07:33 UTC by rladpwl0512

## 상세 내용
- 랜딩페이지가 모바일에서 깨지지 않게 대응해주었습니다. 
- 사이즈별로 대응 가능한 미디어 쿼리를 Globalstyle에 작성했습니다. 
- 미디어쿼리 사이즈에 따라 css 적용이 가능하도록, 유틸 함수를 분리해주었습니다. 
- 자세한 내용은 [개발일지](https://www.notion.so/ririhan/FE-59e0e4994dca4e4e833b8bc717e2bd30)를 참고해주세요 :) 

Close #386

2022-10-13 08:01 UTC, al-bur requested changes
위니 고생했습니다!!😀

responsive가 인상깊네요~~ 아쉬운 점은 뭔가 preview로 pr에 대한 내용을 보면 좋을 것 같네요ㅎㅎ

몇 가지 코멘트 남겼습니다!!

2022-10-13 08:53 UTC, rladpwl0512 reviewed
리뷰 감사합니다~ 리뷰 주신 부분에 대한 의견 남겼으니 확인해주세요 😊

2022-10-13 08:53 UTC, rladpwl0512 commented on frontend/src/styles/GlobalStyle.tsx
> +  }
사실 이 부분은 수정하기 애매해서 고치지 않았는데요, 
고치려고 보니 각 미디어 쿼리에 중단점 사이즈에 대한 정의를 해주어야하는데  (tablet, notebook, desktop과같은 정의를 말합니다) 
`1700px`과 같은 경우는 화면에 깨지는 부분을 위해 대응을 해준 것이지, 특정 기기 대응을 위한 사이즈가 아닙니다. 
그렇게 되면 1700px 이외 부분들에 대해서는 대략적인 사이즈 정의가 가능하겠지만(ex. responsive.desktop) 1700px 부분은 미디어 쿼리로 남겨놔야하기 때문에 일관성이 깨지게 됩니다.  
1700px과 같은 경우가 더 추가된다면, 어떤건 유틸을 사용하고 어떤건 사용하지 않고... 일관성이 떨어진다고 생각했습니다. 😅 

여기에 대해 어떻게 생각하시나요? 🤔

2022-10-13 08:53 UTC, rladpwl0512 commented on frontend/src/styles/GlobalStyle.tsx
> +  }
네! 
최대한 기존에 작성되어있는 media-query를 유지했기 때문에 깨지지 않습니다.

2022-10-13 08:53 UTC, rladpwl0512 commented on frontend/src/styles/GlobalStyle.tsx
>    }
오 이 부분은 생각하지 못했는데, 좋은 것 같아요! 수정했습니다. 

---
[refactor: html에 대한 style 위치 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/443/commits/80b627bdcd19a5ae20f49f79979229fb4624447a)

2022-10-14 06:13 UTC, al-bur commented on frontend/src/styles/GlobalStyle.tsx
> +  }
만약, 해당 분기점을 재사용한다고 하면, 하나의 변수로 만들어줘도 좋을 것 같아요!!!

2022-10-15 13:54 UTC, al-bur approved these changes
고생했습니다~
반응형은...역시나 너무 어렵네요

2022-10-16 05:09 UTC, merged