feat: 그룹 생성 및 초대 페이지 모바일 사이즈 대응
woowacourse-teams/2022-mo-rak pull request #453
Opened 2022-10-16 07:11 UTC by rladpwl0512

## 상세 내용
- 그룹 생성 및 초대 페이지 모바일 사이즈 대응했습니다. 
- netlify를 통해 배포완료했으나, env 설정 문제로 인해 api 요청이 제대로 되지 않네요 😱 일단 패스합니다 
- 기존에 rem으로 고정되어있었던 input form 크기를, 모바일 대응을 위해 화면 넓이인 vw를 기준으로 input form의 크기를 조정해주는 것으로 변경했습니다. 
- 다만, 이렇게 해주니 화면이 커졌을 때는 input form이 불필요하게 커졌습니다. 그래서 vw 기준으로 커지다가, 일정 크기가 되면 더 커지지 않도록 max-width 속성을 추가해주었습니다 😄

<img width="395" alt="스크린샷 2022-10-16 오후 4 09 14" src="https://user-images.githubusercontent.com/52344833/196023061-fc65f859-8223-4919-b51f-d04ab92ac753.png">

Close #369

2022-10-16 13:09 UTC, al-bur commented on frontend/src/pages/GroupInitPage/components/GroupCreateFormNameInput/GroupCreateFormNameInput.tsx
> +      maxWidth="83.2rem"
이거는 slack으로 이야기한 부분이라 스킵할게요!

2022-10-16 13:11 UTC, al-bur requested changes
위니 고생했어요!!

저희가 이야기 나눈 css unit에 대해서만 해결하면 될 것 같네요😀😀

2022-10-16 13:11 UTC, al-bur commented on frontend/src/pages/GroupInitPage/components/GroupCreateFormSubmitButton/GroupCreateFormSubmitButton.styles.tsx
> +  max-width: 21.2rem;
이 부분도 동일합니다!!

다시 한 번 언급하자면, 지금까지 저희는 rem을 통해서 width, height를 지정해주고 있었는데, vw를 도입을 하게 되면 어떠한 상황이 생길지 보고 컨벤션을 정해야할 것 같아요

2022-10-16 13:11 UTC, al-bur commented on frontend/src/pages/GroupInitPage/components/GroupPariticipateFormSubmitButton/GroupParticipateFormSubmitButton.styles.tsx
> +  max-width: 21.2rem;
동일합니다

2022-10-18 03:02 UTC, rladpwl0512 commented
앨버~ 어제 정한 컨벤션대로, vw는 거둬내고 %로 변경했습니다.👋
%로도 많은것이 가능하네요! 
다만, 일정 크기가 되면 커지지 않도록 max-height는 유지해주었습니다. 

확인해주세요 :) 

---
[refactor: vw 삭제 및 %로 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/453/commits/f88fb09d35e9e28ed66e6043ab2fdf59ebcd4b57)

2022-10-18 06:12 UTC, al-bur commented on frontend/src/pages/GroupInitPage/components/GroupParticipateForm/GroupParticipateForm.tsx
> +      <StyledContainer>
어떤 컨테이너인지 명시해주는건 어떨까요?
Styledcontainer는 최상위일때만 루트 컴포넌트용으로 사용하면 좋을 것 같아요

2022-10-18 06:13 UTC, al-bur commented on frontend/src/pages/GroupInitPage/components/GroupParticipateForm/GroupParticipateForm.tsx
> +      <StyledContainer>
사실 루트에 styledcontainer도 의미가 없는 네이밍이지만, 이것은 루트에 위치하기때문에 괜찮지않을까해요!

2022-10-18 08:43 UTC, rladpwl0512 commented on frontend/src/pages/GroupInitPage/components/GroupParticipateForm/GroupParticipateForm.tsx
> +      <StyledContainer>
맞습니다
네이밍을 고민하고있는데 
현재 `StyledContainer`가 form 태그 내부에 있어서 확실히 `StyledFormContainer`는 아닌데, input과 button을 감싸는 요 아이의 이름을 어떻게 해줄지 너무 고민되네요 😵‍💫
보통 input과 button은 함께 있으니까 `StyledInputContainer`는 어떤가요? 너무 어렵네요... 더 좋은 의견 있으시면 알려주세요!

2022-10-18 09:01 UTC, al-bur commented on frontend/src/pages/GroupInitPage/components/GroupParticipateForm/GroupParticipateForm.tsx
> +      <StyledContainer>
너무 어렵네요....스타일드 컴포넌트 이름 짓기가 난이도 최상인 것 같아요😥
일단은, 좋습니다~

2022-10-18 13:57 UTC, rladpwl0512 commented on frontend/src/pages/GroupInitPage/components/GroupParticipateForm/GroupParticipateForm.tsx
> +      <StyledContainer>
어렵네요 😅 수정했습니다 

---
[refactor: 컴포넌트명 수정](https://github.com/woowacourse-teams/2022-mo-rak/pull/453/commits/0e8d7de8f75b6c08412cf38dd795c9488b3d4ff0)

2022-10-18 16:40 UTC, al-bur approved these changes
고생했어요 위니~

2022-10-18 16:44 UTC, merged