refactor: 타입 리팩토링
woowacourse-teams/2022-mo-rak pull request #457
Opened 2022-10-16 14:38 UTC by al-bur

## 상세 내용

전반적으로 타입을 리팩토링하였습니다!
interface보다는 type을 사용하도록 변경해주었습니다~

Close #456

2022-10-17 06:49 UTC, rladpwl0512 requested changes
앨버 수고하셨습니다~ 
interface를 type으로 다 잘 바꿔주셨네요 :) 

eol 부분만 확인해주세요 ~ 🔥

2022-10-17 06:49 UTC, rladpwl0512 commented on frontend/.gitignore
>  cypress.env.json
eol 한번 확인해주세요~

2022-10-17 06:49 UTC, rladpwl0512 commented on frontend/src/types/appointment.ts
> +type GetAppointmentResponse = Appointment & {
요청 보내는 것은 ~Request
요청 받는 것은 ~Response로 통일해주었네요! 
대문자로 변경한것도 깔끔해서 보기 좋습니다 👍

2022-10-18 01:31 UTC, al-bur commented on frontend/src/types/appointment.ts
> +type GetAppointmentResponse = Appointment & {
전체적으로 프로젝트에도 적용 어떻게 할 지 컨벤션 정해봐도 좋을 것 같아요

2022-10-18 01:35 UTC, al-bur commented on frontend/.gitignore
>  cypress.env.json
해결했습니다~

2022-10-18 08:49 UTC, rladpwl0512 commented on frontend/src/types/appointment.ts
> +type GetAppointmentResponse = Appointment & {
좋습니다! 🔥

2022-10-18 08:51 UTC, rladpwl0512 approved these changes
리뷰 반영 및 추가적으로 수정해주신 부분들 확인했습니다!  
다음에 타입 스크립트 컨벤션에 대해 이야기해보아요~ 

approve 합니다 :)

2022-10-18 08:59 UTC, merged