feat: 에러페이지 구현
woowacourse-teams/2022-mo-rak pull request #464
Opened 2022-10-18 07:42 UTC by rladpwl0512

## 상세 내용
- 에러 페이지를 구현했습니다. 🔥
- 사용성을 위해 뒤로가기, 홈으로 가기 버튼 두개 모두 넣어주었습니다. 
- 가장 상위인 `StyledContainer`에 `vh` 를 사용했는데요, 
`StyledContainer`에서 height 100%를 주었지만, 화면을 꽉 채우지 않았습니다. 부모인 root가 화면 전체를 채우지 않고있으니 당연한 결과였습니다. 
그래서 부득이하게 화면을 꽉 채울 수 있도록 height를 %가 아닌 vh로 주었습니다. 
화면을 꽉 채워야했던 이유는, 내부 요소를 화면 전체에서 중앙에 정렬하기 위해서입니다. 
컴포넌트에서 가장 상위라서 vh를 사용해도 된다고 판단되는데, 확인해주세요! 

- handleNavigate를 사용하는데 있어 타입 문제가 있었습니다🥲 일지 참고해주세요. 
[일지보기 👀](https://ririhan.notion.site/FE-86ef21b512b6433cad5b96edc0e95766)

## 화면 
<img width="1001" alt="스크린샷 2022-10-18 오후 4 41 45" src="https://user-images.githubusercontent.com/52344833/196367500-c9abb3d2-a99b-4a34-938a-72b4cb412326.png">

Close #179

2022-10-18 13:09 UTC, RIANAEH commented
"모락으로 돌아가기"라고 하면 무슨말인지 잘 모를 수도 있을 것 같아요(는 나)
"메인으로 가기"가 어떨까요?

2022-10-19 14:53 UTC, al-bur requested changes
고생했어요 위니~

귀여운 lottie 찾아주셨네요ㅎㅎ코멘트 남겼습니다!

2022-10-19 14:53 UTC, al-bur commented on frontend/src/pages/ErrorPage/ErrorPage.styles.tsx
> +const StyledGuid = styled.div`
오타입니다!!
근데 Guide보다는 Description은 어떤가요?
그리고, div보다는 p 태그가 더 시맨틱해서 좋을 것 같아요!

2022-10-19 14:53 UTC, al-bur commented on frontend/src/pages/ErrorPage/ErrorPage.tsx
> +  );
page 컴포넌트이니까, 한 번 추상화를 해줘도 되지 않을까 합니다!!

ErrorPageContainer
ErrorPageButtonGroup

처럼요!

2022-10-19 14:57 UTC, al-bur commented on frontend/src/pages/ErrorPage/ErrorPage.tsx
> +  );
![image](https://user-images.githubusercontent.com/64825713/196727437-27b999ad-0070-486b-8365-511f596f26ba.png)

2022-10-19 16:56 UTC, rladpwl0512 commented on frontend/src/pages/ErrorPage/ErrorPage.styles.tsx
> +const StyledGuid = styled.div`
description과 고민했던 부분인데 리뷰주셔서 감사함다~ 
시맨틱 태그를 사용하도록 노력해야겠어요!

---
[refactor: 컴포넌트명 수정 및 태그 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/464/commits/08b6b27e95463cfa91d8af82bf2b40d02557779a)

2022-10-19 17:27 UTC, rladpwl0512 commented on frontend/src/pages/ErrorPage/ErrorPage.tsx
> +  );
맞습니다 page를 추상화해주지 않았네요! 😅
사실 `ErrorPageContainer` 말고 의미를 더 잘드러낼 수 있는 것을 더 고민해보았는데 어렵네요...(`ErrorPageContent`은 Container와 비슷한가? `ErrorPageDescription`으로 하기에는 애니메이션도 있고 😵‍💫) 이미 지금까지 페이지에서 추상화할 때 Container 키워드를 꾸준히 사용해주기도 했기 때문에 일단 `ErrorPageContainer` 로 작성해주었습니다. 이 부분은 다른 페이지 컴포넌트 내부에 Container로 작성되어있는 것도 같이 의미를 더 잘 드러낼 수 있도록 같이 이야기해보고 수정해봐도 좋을 것 같아요! 

---
[refactor: 컴포넌트 추상화](https://github.com/woowacourse-teams/2022-mo-rak/pull/464/commits/4b16f2e17c2d10a1171900d93fc41fd6e759ebae)

2022-10-20 03:30 UTC, al-bur approved these changes
고생하셨습니다!

2022-10-20 11:17 UTC, merged