fix: 사이드바의 멤버목록이 다른 요소와 겹치는 문제 해결
woowacourse-teams/2022-mo-rak pull request #479
Opened 2022-10-19 08:14 UTC by rladpwl0512

## 상세 내용
- 사이드바의 멤버목록이 다른 요소와 겹치는 문제 해결 
- %로 레이아웃을 잡아주었습니다. 

Close #478

2022-10-19 08:24 UTC, RIANAEH commented
잘했습니다🥳

2022-10-19 13:50 UTC, al-bur commented on frontend/src/layouts/SidebarLayout/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.styles.tsx
>  const StyledMemberListContainer = styled.div`
members~

2022-10-19 14:43 UTC, al-bur requested changes
위니 고생하셨어요~~ 몇 가지 코멘트 남겼습니다 확인해주세요!

2022-10-19 14:43 UTC, al-bur commented on frontend/src/layouts/SidebarLayout/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.tsx
> +      <Divider />
이 부분은 고민을 해봅시다!! 현재는 그대로 가보죠 시간이 없으니!

2022-10-19 14:43 UTC, al-bur commented on frontend/src/layouts/SidebarLayout/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.tsx
>        <StyledContainer>
이것도 위에 styledContainer로 변경함에 따라 네이밍을 다시 해줘야할 것 같아요!

어? 근데 이거, 제가 작업한 거에서 수정해준 것 같아서 냅둬도 될 것 같습니다!!

2022-10-19 14:43 UTC, al-bur commented on frontend/src/layouts/SidebarLayout/components/SidebarGroupsMenu/SidebarGroupsMenu.styles.tsx
>    font-family: 'Nanum Gothic', sans-serif;
생각해보니 여기는 왜 폰트가 다른걸까요?

2022-10-20 00:21 UTC, rladpwl0512 commented on frontend/src/layouts/SidebarLayout/components/SidebarGroupsMenu/SidebarGroupsMenu.styles.tsx
>    font-family: 'Nanum Gothic', sans-serif;
그룹의 첫번째 글자를 통해 프로필을 나타내는 부분인데요, 이 부분은 기존의 글자체가 어울리지 않아서 나눔 고딕으로 변경해주었습니다. 
이전에 주아체였을 때 안어울려서 이렇게 해줬던건데, 지금 글씨체로 다시 바꿔서 확인해볼게요

2022-10-20 01:55 UTC, rladpwl0512 reviewed
리뷰 반영완료했슴다 확인해주세요~

2022-10-20 01:55 UTC, rladpwl0512 commented on frontend/src/layouts/SidebarLayout/components/SidebarGroupsMenu/SidebarGroupsMenu.styles.tsx
>    font-family: 'Nanum Gothic', sans-serif;
티머니체가 아주 괜찮네요 ~ 랜딩페이지와 함께 수정했습니다 
그런데 나눔 고딕은 웹에 기본적으로 들어있는 폰트인가보네요 네트워크 요청은 가지 않아요

2022-10-20 03:25 UTC, al-bur approved these changes
고생하셨습니다~

2022-10-20 11:38 UTC, merged