feat: 이름 변경 기능 구현
woowacourse-teams/2022-mo-rak pull request #483
Opened 2022-10-19 13:32 UTC by al-bur

## 상세 내용

- 현재 사용자를 확인하는 api를 연결해주었습니다.
- 이름 변경 모달을 구현하였습니다.
- 이름 수정 api를 연결해주었습니다.
- 

Close #467 #476

2022-10-19 13:36 UTC, al-bur commented on frontend/src/routes/GroupRoute.tsx
> +  }, [activeMenu, authState, groupCode]);
그룹 변경될 때 마다 그룹 멤버들 업데이트 하도록 해주었습니다

2022-10-20 03:33 UTC, rladpwl0512 requested changes
앨버 기능 추가 수고하셨습니다~ 🐝
몇가지 커멘트 남겼는데 확인해주세요 😄

2022-10-20 03:33 UTC, rladpwl0512 commented on frontend/src/layouts/SidebarLayout/components/SidebarEditUsernameModal/SidebarEditUsernameModal.tsx
> +          <SidebarEditUsernameModalUsernameInput
SidebarEditUsernameModalInput 으로 해도 되지 않을까요? 🤔

2022-10-20 03:33 UTC, rladpwl0512 commented on frontend/src/routes/GroupRoute.tsx
> +  }, [activeMenu, authState, groupCode]);
굿입니다~!! 👍🥳

2022-10-20 10:42 UTC, al-bur commented on frontend/src/api/appointment.ts
> +  privateGroupsAxiosInstance.post(`/${groupCode}/appointments`, appointment);
groups는 groups라는 path가 들어간다고 보면됩니다!!!

'auth'와 "groups"는 path입니다. (url 뒤에 들어가는 것)

```typescript

const publicAuthAxiosInstance = axiosInstanceGenerator('auth')(false);
const privateAuthAxiosInstance = axiosInstanceGenerator('auth')(true);
const privateGroupsAxiosInstance = axiosInstanceGenerator('groups')(true);

```

2022-10-20 10:44 UTC, al-bur commented on frontend/src/api/axios.ts
> +const axiosInstanceGenerator = (path: Path) => (isAuthRequired: boolean) => {
네네 처음에는 대부분이 isAuthRequired가 true라서 default로 지정해주었습니다.

하지만, 나중에 코드를 다시 보니, 어떤 것은 false라는 인자를 주고 어떤 것은 아예 인자를 주지 않고 있으니 살짝 헷갈리는 부분이 있었습니다. 그래서, 조금 귀찮겠지만 true, false를 명시적으로 넣어주도록 변경해주었습니다

2022-10-20 10:45 UTC, al-bur commented on frontend/src/components/Avatar/Avatar.tsx
>      <StyledUserProfile width={width}>
넵 바꾸는 게 좋을 것 같네요!! 근데, 현재 이름 변경 기능과는 조금 동 떨어진 작업이라, 추후 리팩토링 해보는 걸로 해요`~

2022-10-20 10:45 UTC, al-bur commented on frontend/src/context/MenuProvider.tsx
> +  // TODO: isGroupsModalVisible이 맞지 않을까?? 모달이 보이냐 vs 보이는 모달이냐의 차이
ㅎㅎㅎㅎㅎ좋습니다

2022-10-20 10:47 UTC, al-bur commented on frontend/src/hooks/useModal.tsx
> +  return [isVisible, open, close, toggle] as const;
as const를 해주지 않으면, 튜플 타입이 적용이 되지 않았습니다.

as const를 사용하지 않으면 (boolean | () => void)[] 와 같은 형태로 타입이 추론이 됩니다. 그래서, useModal을 사용하는 쪽에서 원하는 대로 타입이 잘 설정이 되지 않더라고요!

2022-10-20 10:52 UTC, al-bur commented on frontend/src/layouts/SidebarLayout/components/SidebarEditUsernameModal/SidebarEditUsernameModal.tsx
> +          <SidebarEditUsernameModalUsernameInput
usename을 다루는 Input이라 명확하게 넣어주었습니다!! Input이라고 하면 어떤 Input인지 모를 것 같아서요😀

2022-10-20 10:53 UTC, al-bur commented on frontend/src/layouts/SidebarLayout/components/Sidebar/Sidebar.tsx
> +        {/* NOTE: menu보다는 section이 어떨까? SidebarGroupSection */}
삭제하였습니다!

[140f778](https://github.com/woowacourse-teams/2022-mo-rak/pull/483/commits/140f778b060fd3fe0985eb9641777abadf034635)

2022-10-20 10:53 UTC, al-bur commented on frontend/src/layouts/SidebarLayout/components/Sidebar/Sidebar.tsx
> +      {/* NOTE: SidebarModals로 해도 되지 않을까? */}
삭제하였습니다!

[140f778](https://github.com/woowacourse-teams/2022-mo-rak/pull/483/commits/140f778b060fd3fe0985eb9641777abadf034635)

2022-10-20 10:55 UTC, al-bur commented on frontend/src/components/Avatar/Avatar.tsx
>      <StyledUserProfile width={width}>
[c14fa8b](https://github.com/woowacourse-teams/2022-mo-rak/pull/483/commits/c14fa8b88f7025cf2d3793c86bc330531a514a32)

수정하였습니다!

2022-10-20 11:26 UTC, rladpwl0512 approved these changes
앨버 수고하셨습니다 approve 할게요~ 😎

2022-10-20 15:53 UTC, merged