fix: navigation bar의 메뉴 상태가 업데이트 되도록 수정
woowacourse-teams/2022-mo-rak pull request #524
Opened 2022-10-27 03:06 UTC by rladpwl0512

## 상세 내용
- 기존에는 main 페이지에서 메뉴를 클릭했을 때, navigation bar에 업데이트 되지 않는 문제가 있었습니다. (이슈 참고해주세요.)
원인을 분석해보니 MenuRoute의 useEffect 두번째 인수가 빈배열로 들어가서 생기는 문제였습니다.  
그래서 useEffect의 두번째 인수를 빈배열에서 menu로 변경함으로써, 문제를 해결할 수 있었습니다.

- 위 문제를 해결하면서, `MenuProvider` -> `NavigationBarProvider`으로 변경하는 작업도 함께 진행했습니다. 

Close #523

2022-10-27 15:15 UTC, al-bur requested changes
고생했습니다 위니!!!

근데, 메인 화면일 때는 선택된 메뉴가 없는 거니까 빈 string보다는 명시적으로 null이 좋을 것 같아서 코멘트 남겼어요!

2022-10-27 15:15 UTC, al-bur commented on frontend/src/App.tsx
> -                  <Route element={<MenuRoute menu="main" />}>
빈 string보다 null이라고 하는 건 어떨까요??

2022-10-27 15:15 UTC, al-bur commented on frontend/src/layouts/NavigationLayout/components/GlobalFootbarFootbar/GlobalFootbarFootbar.tsx
> +    if (menu === '') {
여기도요!

2022-10-27 15:15 UTC, al-bur commented on frontend/src/layouts/NavigationLayout/components/GlobalFootbarFootbar/GlobalFootbarFootbar.tsx
> +        <button onClick={handleSetActiveMenu('')}>
여기도요!

2022-10-28 04:25 UTC, rladpwl0512 commented on frontend/src/App.tsx
> -                  <Route element={<MenuRoute menu="main" />}>
맞습니다! 
저희가 이전에 menu는 투표하기, 약속잡기, 역할정하기로 생각했기 때문에 main은 애초에 menu에 부적합했네요 😅 
null으로 수정했습니다 :)

2022-10-28 04:26 UTC, al-bur approved these changes
수고하셨습니다!

2022-10-28 04:29 UTC, merged