refactor(poll): 쿼리 성능 개선
woowacourse-teams/2022-mo-rak pull request #547
Opened 2022-10-30 20:16 UTC by RIANAEH

## 상세 내용

Close #546 

### 투표 쪽 쿼리 성능 개선을 했습니다. (조회 성능 개선에 초점을 맞추었습니다.)

1. BatchSize를 1000으로 설정했습니다. 
2. poll 테이블에 count 컬럼을 추가하는 반정규화를 진행했습니다. 
3. poll 테이블에 code에 대한 인덱스를 생성했습니다. 

- Poll 조회 시 JOIN으로 PollItem과 SelectMember를 한번에 불러오도록 개선하려고 했는데 실패했습니다. 하지만 JOIN을 거는 경우 중복 데이터를 가진 row들이 생겨나기 때문에 성능적으로 이점이 될지는 모르겠습니다. 
- Poll 삭제 시 CascadeType.REMOVE가 적용되어 PollItem과 SelectMember 까지 모두 삭제되는 데 단건으로 쿼리가 나갑니다. 여기에 Batch Delete를 적용하는 방법을 찾아보다 실패했습니다. 

### before/after
<img width="702" alt="image" src="https://user-images.githubusercontent.com/45311765/198899480-dc61749b-bcdb-46ea-89f1-e1c58185c27a.png">

### [개발일지](https://www.notion.so/ririhan/BE-df9cae45dcdd4879a026a79e0a9ddbf3)

2022-10-31 10:13 UTC, cjlee38 requested changes
안녕하세요 엘리~ 고생 많으셨습니다. 레포지토리쪽 쿼리가 변하지 않았는데, 결과를 보니 다음과 같이 결론이 난 것 같네요.

1. 다건 조회시 -> count 컬럼으로 인해 하위객체(poll_item, select_members) 조회하지 않아서 상관없음.
2. 단건 조회시, 하위 객체가 필요한 경우 -> poll_item까지는 1번의 쿼리로 해결되니 상관X, select_members까지 나갈 때 N+1이 발생할 수 있지만, in 절로 처리하므로 총 세 번의 쿼리로 해결

그러면 여기서 의문이 드는 부분은 "과연 조인이 in절보다 좋지 않은가?" 인데요. 이 부분을 자세히 한번 계산할 수 있는 방법을 같이 한번 찾아보죠~

2022-10-31 10:13 UTC, cjlee38 commented on backend/build.gradle
> +//    implementation 'org.projectlombok:lombok:1.18.20'
r: 이거 이래도 괜찮나요 ?

2022-10-31 10:13 UTC, cjlee38 commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `poll_index_code` ON `poll` (`code`);
r: 인덱스를 추가하는 대신 unique를 거는건 어떤가요 ?

2022-10-31 10:13 UTC, cjlee38 commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `poll_index_team_code` ON `poll` (`team_code`);
c: team_code는 team 소속의 unique에 걸린 외래키인데 인덱스를 따로 생성해줘야 하나요?

2022-10-31 10:13 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +    void 투표_진행_후_단건_조회_시_count값이_반영된다(@Autowired EntityManager em) {
```suggestion
    void 투표_진행_후_단건_조회_시_count값이_반영된다(@Autowired EntityManager entityManager) {
```

2022-10-31 10:13 UTC, cjlee38 commented on backend/src/test/resources/data.sql
> +VALUES (1, 'https://slack.webhook.com/', now(), now());
a: 👍

2022-10-31 15:11 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +    void 투표_진행_후_단건_조회_시_count값이_반영된다(@Autowired EntityManager em) {
엄격하네요

2022-10-31 15:45 UTC, seong-wooo requested changes
일단 남기겠습니다. 보다가 졸려서.. 내일 이어서 하도록 하죠

2022-10-31 15:45 UTC, seong-wooo commented on backend/src/test/resources/schema.sql
> +    selected_count INTEGER      NOT NULL DEFAULT 0,
member_id는 BIGINT인데 selected_count는 INTEGER네요.
member_id와 일치시켜야하지 않을까요?

2022-10-31 16:55 UTC, leo0842 approved these changes
count 와 관련하여 궁금한 점은 구두로 말씀드릴게요!!

2022-10-31 16:55 UTC, leo0842 commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> -    Optional<Poll> findFetchedByCode(@Param("code") String pollCode);
결론은 2depth 로는 inner join 이 걸리지 않기때문에 그냥 findByCode 하고 batch size 로 가져오는게 더 낫다는 거죠??

2022-11-01 04:00 UTC, RIANAEH commented on backend/build.gradle
> +//    implementation 'org.projectlombok:lombok:1.18.20'
넵 기존에 compileOnly로 lombok dependency를 추가해주고 있었습니당

2022-11-01 04:11 UTC, RIANAEH commented on backend/src/test/resources/schema.sql
> +    selected_count INTEGER      NOT NULL DEFAULT 0,
INT는 4바이트, BIGINT는 8바이트입니다. 
id의 경우 서비스의 규모가 커졌을 때 INT를 BIGINT로 변경해야하는 데, 이때 다른 곳에서 외래키로 사용중이라면 모든 외래키를 해제한 후 타입 변경을 진행할 수 있는 등 제약 사항들이 있어 안전하게 BIGINT를 사용했었습니다. 
하지만 selected_count의 경우 그 크기가 21억을 넘어가는 경우가 발생하지 않을 것이라고 판단해 INT를 사용했습니다.

2022-11-01 04:15 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
> -    Optional<Poll> findFetchedByCode(@Param("code") String pollCode);
넵!
`inner join fetch + left join fetch`는 가능했지만 성능 측정 결과 오히려 성능이 안 좋아졌었습니다. (inner join * 2는 불가능!)
그래서 batch size로 `1 + N + N*M`을 `1 + 1 + 1`로 개선한 것에 만족하려고 했었는데, [one-to-many에서 fetch join 사용시 성능상 이슈가 있을 수 있다](https://kwonnam.pe.kr/wiki/java/hibernate/gotchas)고 하네요.

2022-11-01 04:26 UTC, RIANAEH commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `poll_index_code` ON `poll` (`code`);
mysql에서 unique 제약 조건을 사용하면 자동으로 non-clustered index가 생성되기 때문에 이를 사용해도 되지만, 일단 secondary index와 비교해보면 쓰기 작업 시 중복된 값이 있는지 없는지 체크하는 과정이 추가 되어 더 느리다고 합니다. 
application 단에서 random 생성을 통해 code를 생성해주고 있기 때문에 DB단에서는 중복 체크를 추가적으로 하지 않아도 될 것 같다고 생각합니다. 
따라서 index 생성으로 그대로 유지하고 싶음! 차리의 생각은??

2022-11-01 04:28 UTC, RIANAEH commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `poll_index_team_code` ON `poll` (`team_code`);
poll 테이블에는 primary key 외의 key를 설정하지 않았습니다.

2022-11-01 07:07 UTC, cjlee38 commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `poll_index_code` ON `poll` (`code`);
의도 자체가 먼저 '중복된 값이 없다' 라는 의도를 담고 여기에 수반되는 unique 인덱스 옵션이 따라오면 추가적으로 인덱스를 생성할 필요가 없다는 관점으로 보는게 더 좋을 것 같네요.

2022-11-01 07:08 UTC, cjlee38 commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `poll_index_team_code` ON `poll` (`team_code`);
team 테이블에 unique가 걸려있다면 poll 쪽에서 조회시 team의 unique 인덱스를 타지 않나요 ?

2022-11-03 01:52 UTC, RIANAEH commented on backend/src/main/resources/schema-dev.sql
> +CREATE INDEX `poll_index_team_code` ON `poll` (`team_code`);
도메인 재설계를 진행하면서 투표 관련 테이블에서는 FK가 DB 성능 저하로 이어질 수 있다고 생각해서 이를 적용하지 않았었어요. 하지만 차리랑 같이 논의를 해보니 저희 비즈니스 로직 상 lock으로 인한 데이터 동시성 문제 보다는 DB 상의 데이터 정합성을 더 고려하는게 적합하다고 판단했고, FK를 걸어주는 방향으로 변경했습니다. 

하지만 이로 인해 발생할 수 있는 dead lock 문제를 해결해야합니다.

2022-11-03 02:12 UTC, cjlee38 requested changes
안녕하세요 엘리. 갑자기 든 생각이 하나 있어서 이것만 체크해주시면 approve & merge 하면 될 것 같습니다.

조사하신 unique/foreign 과 관련한 인덱스 설정 이유에 대해서 정리 한번 부탁드릴게용

2022-11-03 02:12 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +    private int selectedCount;
c: 갑자기 든 의문인데요. selected count도 poll items과 관리하는게 맞지 않나 싶어서요. allowed count처럼요. N+1 문제도 안날 것 같은데, 어떤가요 ?

2022-11-03 02:12 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +    void 투표를_진행한다(@Autowired EntityManager entityManager) {
c: 테스트용인가요 ?

2022-11-03 02:36 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +    private int selectedCount;
저도 selected count에 대한 책임을 PollItems가 가진다는 것에 동의해서 변경했습니다. 
그런데 N+1 문제도 안날것 같다는 것은 어떤 얘기인가요?

2022-11-03 02:40 UTC, RIANAEH commented on backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
> +    void 투표를_진행한다(@Autowired EntityManager entityManager) {
넵! clear 후 실제 DB에 저장된 값을 불러오게 테스트 해야 조금 더 신뢰가 갈 것 같다고 생각했습니다.

2022-11-03 02:45 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/poll/domain/Poll.java
> +    private int selectedCount;
`findPolls` 를 호출했을 때 PollItems 안에 있는 selected count를 가져올때 N+1 문제가 날까 안날까 생각해봤거든요. 테이블상에서는 같은 테이블내에 있으니 안날거같은데, JPA 여서 poll 테이블을 두번 조회하는 문제가 발생하지 않나 라는 생각이 들었어서.. 한번 체크해주실수있나요 ?

2022-11-03 02:52 UTC, cjlee38 approved these changes
수고하셨씁니다

2022-11-03 02:54 UTC, merged