feat: 역할정하기 쿼리 성능 개선
woowacourse-teams/2022-mo-rak pull request #548
Opened 2022-10-31 05:02 UTC by cjlee38

## 상세 내용

역할정하기 쿼리 성능을 개선했습니다.
[개발일지](https://ririhan.notion.site/BE-78fb0650aa5243dd95823879d9f011af)

Close #542

2022-10-31 07:42 UTC, RIANAEH approved these changes
차리 깔끔하게 개선해주셨네요!
궁금한 부분은 코멘트로 남겨놨어요. 고생하셨습니다:)

![image](https://user-images.githubusercontent.com/45311765/198956754-1ef4ef60-8257-4de7-b153-79ef26956239.png)

2022-10-31 07:42 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/role/application/RoleService.java
>      }
A: 오 맞네요 
JPA에서 사용하는 문법 상 데이터가 조회되지 않았을 때 예외가 터지는 메서드에는 get이 어울리겠네요🙌

2022-10-31 07:42 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/role/domain/RoleHistory.java
> +    private Set<RoleMatchResult> matchResults = new LinkedHashSet<>();
C: 자료형을 Set으로 바꾼 이유가 무엇인가요?

2022-10-31 07:42 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/role/domain/RoleNames.java
> +    @ElementCollection(fetch = FetchType.LAZY)
C: ElementCollection의 경우 기본 설정이 LAZY일 텐데 명시해준 이유가 있나요?

2022-10-31 07:42 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/role/domain/RoleRepository.java
> +    Optional<Role> findByTeamCodeFetched(@Param("code") String teamCode);
A: JOIN을 사용할 경우 role 테이블이나 role_history 테이블의 데이터들이 중복되어 조회될 텐데, 이에 대해서는 어떻게 생각하시나요?

2022-10-31 14:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/role/domain/RoleHistory.java
> +    private Set<RoleMatchResult> matchResults = new LinkedHashSet<>();
Role -> Role History -> Role Match Result 로 이어지는 구조에서, 각각 OneToMany, OneToMany 의 관계를 갖고있는 상황일 때, fetch join 을 두번 연속 사용하려면 둘 중 하나의 컬렉션 타입은 Set이어야 합니다. 로직상 문제가 되지 않는 부분이 RoleMatchResult 인 것 같아서 이 쪽을 set으로 만들어두었습니다...........만 JPA에 대해서 더 깊게 학습해보니 fetch join을 지양해야 할 것 같네요. 이 부분은 좀 더 찾아보겠습니다

2022-10-31 14:29 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/role/domain/RoleNames.java
> +    @ElementCollection(fetch = FetchType.LAZY)
기존에 OneToMany, ManyToOne 의 모든 어노테이션에서 FetchType Lazy를 적어준 것과 같은 이유입니다. 명시적으로 보여주기 위함이에요.

2022-10-31 14:30 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/role/domain/RoleRepository.java
> +    Optional<Role> findByTeamCodeFetched(@Param("code") String teamCode);
https://kwonnam.pe.kr/wiki/java/hibernate/gotchas

List가 아니라 Optional<Role> 로 받고 있어서 정상 동작은 하는데, fetch를 걸었을 때 문제점이 있긴 한것 같아요. 이 부분은 좀 더 조사해보겠습니다.

2022-10-31 17:06 UTC, leo0842 approved these changes
join 과 관련한 질문은 구두로 드릴게요!! 수고하셨어용

2022-10-31 17:06 UTC, leo0842 commented on backend/src/main/java/com/morak/back/role/application/RoleService.java
> +                .orElseGet(() -> roleRepository.save(new Role(teamCode)));
EventListener 놔두고 최소한의 방어로직으로 존재하기 vs EventListener 없애고 이 로직으로 쭉 가기

2022-10-31 22:36 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/role/application/RoleService.java
> +                .orElseGet(() -> roleRepository.save(new Role(teamCode)));
로직 자체는 문제가 없는데, 동시성 이슈를 생각해보면 최대한 오류를 방지하는 쪽으로 생각해서 이벤트는 유지하는게 어떨까 싶네용

2022-11-07 07:55 UTC, seong-wooo requested changes
테스트쪽에 EntityManger를 많이 사용하셨네요. 다 필요한 것들인가요 ?

2022-11-07 07:55 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/role/domain/RoleRepository.java
> +
제거 부탁~

2022-11-07 07:55 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/role/domain/RoleEntityRepositoryImpl.java
> +                    history.getMatchResults().add(matchResult);
객체지향적이지못하네요

2022-11-07 07:55 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/role/domain/RoleEntityRepositoryImpl.java
> +        Map<Long, RoleHistory> IdsByHistory = roleHistories.stream()
변수 첫글자가 대문자네요

2022-11-07 07:55 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/role/application/RoleService.java
>      private final RoleRepository roleRepository;
RoleEntityRepositoryImpl이랑 RoleRepository랑 관계가 없다고 생각했는데, 설명 들으니까 살짝 이해가 되네요.

RoleRepository로 주입되는 것이 RollEntityRepositoryImpl인가? 생각했는데,
디버그를 돌려봤을 때 RoleRepository의 구현체가 SimpleJpaRepository가 되더라고요. 
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/79205414/200246969-a19ca8ea-24ae-4d20-bf6c-85a2cc6c1a13.png">

SImpleJpaRepository는 Repository<Role, Long>을 구현한 구현체인데,
그렇다면 RoleEntityRepository에 있는 findWithOnlyHistoriesPerDate는 어떻게 실행되는걸까 생각해봤거든요

근데 생각해보니 우리가 RoleRepository에 구현한 
```java
    @Query("SELECT r FROM Role r WHERE r.teamCode.code = :code")
    Optional<Role> findByTeamCode(@Param("code") String teamCode);
```
도 SImpleJpaRepository가 구현해서 실행하잖아요.

결론 RoleRepositoryImpl에 구현한 내용을 SimpleJpaRepository가 가져가는거같다

2022-11-07 07:55 UTC, seong-wooo commented on backend/src/main/resources/application.yml
> +        default_batch_fetch_size: 100
특별하게 100으로 설정한 이유가 있나요?

2022-11-07 07:55 UTC, seong-wooo commented on backend/src/test/resources/data.sql
> +INSERT INTO role_match_result (role_history_id, member_id, role_name) values (4, 1, '데일리 마스터');
살짝 불편하네요 ~~~

2022-11-07 07:55 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/role/application/RoleServiceTest.java
> +        entityManager.clear();
쿼리 보는 용도인가요?

2022-11-07 08:18 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/role/domain/RoleRepository.java
> +
제거했습니다 ~

2022-11-07 08:19 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/role/domain/RoleEntityRepositoryImpl.java
> +                    history.getMatchResults().add(matchResult);
기존 도메인 로직에서 history에 add 를 추가할 일이 없어서 이렇게 구현했습니다

2022-11-07 08:20 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/role/domain/RoleEntityRepositoryImpl.java
> +        Map<Long, RoleHistory> IdsByHistory = roleHistories.stream()
수정했습니다~

2022-11-07 08:21 UTC, cjlee38 commented on backend/src/main/resources/application.yml
> +        default_batch_fetch_size: 100
poll 을 기준으로 삼았는데요. poll item이 10개이고 10명의 팀원일때라고 가정했습니다.

2022-11-07 08:21 UTC, cjlee38 commented on backend/src/test/resources/data.sql
> +INSERT INTO role_match_result (role_history_id, member_id, role_name) values (4, 1, '데일리 마스터');
data.sql에 의존적이어서 그런가요?

2022-11-07 08:22 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/role/application/RoleServiceTest.java
> +        entityManager.clear();
JdbcTemplate을 이용하는 경우 영속성컨텍스트를 사용하지 않기 때문에 동기화를 위해 flush 처리를 해주어야 합니다.

2022-11-07 10:08 UTC, RIANAEH approved these changes
차리 개발일지 잘 봤습니다. 
많은 고민을 한 흔적이 느껴지네요👍

현재 RoleHistory 쪽에서 Role에 대한 ID를 갖지 않는 이상 더 개선할 수 있는 방법이 없을 것 같네요ㅜㅜ
객체 매핑해주시느라 고생하셨습니다👏

2022-11-08 02:14 UTC, seong-wooo approved these changes

2022-11-08 02:17 UTC, merged