약속잡기 쿼리를 개선한다.
woowacourse-teams/2022-mo-rak pull request #552
Opened 2022-10-31 11:46 UTC by seong-wooo

약속잡기 쿼리를 개선해보았습니다.
[개발일지](https://www.notion.so/ririhan/BE-8e87167e35b342b7a4506797c47d207f)에 더 자세하게 적혀있습니다.

아직 available_time을 entity로 변경하지는 못했어요.

entity로 변경했을 때, 테스트 코드는 다 통과했는데, 성능 테스트가 동작하지 않네요. 
데드락 걸린 듯합니다.

Close #544

2022-10-31 14:44 UTC, cjlee38 requested changes
구현하느라 고생 많으셨습니다~ 조금만 더 다듬어봅시다

2022-10-31 14:44 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +public class AvailableTimes {
```suggestion
@NoArgsConstructor
@Embeddable
public class AvailableTimes {
```

2022-10-31 14:44 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    }
r: AvailableTimes가 Embeddable 이라면 select count가 Availabletimes 안에 들어갈 수 있을 것 같은데요. 그러면 이 메소드를 AvailableTimes 안으로 옮길 수 있을 것 같아요.

2022-10-31 14:44 UTC, cjlee38 commented on backend/src/test/resources/schema.sql
> +    `selected_count`   BIGINT       NOT NULL DEFAULT 0,
r: 테스트 말고 프로덕션 쪽에도 추가해주세요~ data.sql 에도요 ~

2022-10-31 14:44 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +        final List<AvailableTime> availableTimes = localDateTimes.stream()
```suggestion
        List<AvailableTime> availableTimes = localDateTimes.stream()
```

2022-10-31 14:44 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +                .map(dateTime -> AvailableTime.builder().memberId(memberId).startDateTime(dateTime).build())
```suggestion
                .map(dateTime -> new AvailableTime(memberId, dateTime)
```

c: 이제 보니까 꼭 빌더를 고집할 필요는 없을 것 같은데, 어떤가요 ?

2022-10-31 14:44 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +        this.availableTimes.addAll(availableTimes);
r: 이렇게하면 해당하는 member를 모두 지우고 다시 삽입하는 과정이네요. "멤버는 일치하지만 신규 데이터(localDateTImes)에 속해지 않는 경우에만 삭제" 해야 delete / insert 순서 문제를 방지할 수 있을것 같아요.

2022-10-31 14:44 UTC, cjlee38 commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> +        em.clear();
c: 쿼리 테스트용인가요 ? 아니면 필요해서 넣은건가요 ?

2022-10-31 15:02 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    }
이것에 대해서 저도 생각을 했었는데요. 생각만 했네요. 내일 반영하겠습니다

2022-10-31 15:02 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +        final List<AvailableTime> availableTimes = localDateTimes.stream()
요즘 미션을 하다보니 자동완성으로 들어가버렸네요 ~

2022-10-31 15:05 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +                .map(dateTime -> AvailableTime.builder().memberId(memberId).startDateTime(dateTime).build())
저도 사실 바꾸고 싶었는데요. 수정해야할 부분이 많을 것 같아서 안바꿨답니다.
다들 바꾸는거 찬성하시나요? 

찬성 - 👍
반대 - 👎

2022-10-31 15:06 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +        this.availableTimes.addAll(availableTimes);
좋은 아이디어입니다.

2022-10-31 15:06 UTC, seong-wooo commented on backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
> +        em.clear();
쿼리 테스트용인데 급하게 push 하느라 이런 사소한 부분을 놓쳤네요

2022-10-31 15:14 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +                .map(dateTime -> AvailableTime.builder().memberId(memberId).startDateTime(dateTime).build())
기존 빌더쓰는 부분을 지울필요는 없을것같고, 생성자와 빌더를 둘다 열어두면 되지않을까요?

2022-10-31 22:18 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +                .map(dateTime -> AvailableTime.builder().memberId(memberId).startDateTime(dateTime).build())
인정

2022-11-01 04:31 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +                .map(dateTime -> AvailableTime.builder().memberId(memberId).startDateTime(dateTime).build())
둘다 유연하게 가져가도록 하죠~ 너무 불편했었슴다

2022-11-01 05:47 UTC, RIANAEH requested changes
까라 수고 많았어용
AvailableTimes 부분만 수정해보면 좋을 것 같네요. 

그리고 Performance 테스트에 선택, 재선택 다른 멤버 선택이 있는데, 
재선택 시 이전 선택과 겹치는 시간과 겸치치 않는 시간을 가진 요청으로 변경해보면 좋을 것 같요!

### Fixture 변경
```java
// 선택 시 사용
public static final List<AvailableTimeRequest> 약속잡기_가능시간_3개_선택_요청_데이터 = List.of(
        모락_회식_첫째날_4시부터_4시반_선택_요청_데이터,
        모락_회식_첫째날_4시반부터_5시_선택_요청_데이터,
        모락_회식_첫째날_5시부터_5시반_선택_요청_데이터
);

// 재선택 시 사용
public static final List<AvailableTimeRequest> 약속잡기_가능시간_4개_선택_요청_데이터 = List.of(
        모락_회식_첫째날_4시부터_4시반_선택_요청_데이터,
        모락_회식_첫째날_4시반부터_5시_선택_요청_데이터,
        모락_회식_첫째날_5시반부터_6시_선택_요청_데이터,
        모락_회식_첫째날_11시_반부터_00시_선택_요청_데이터
);
```

2022-11-01 05:47 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    private long selectedCount;
r: long을 사용한 이유가 무엇인가요?

2022-11-01 05:47 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    private void countUpIfNotExists(Long memberId) {
r: 메서드 순서👀

2022-11-01 05:47 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
c: CacadeType.ALL을 설정한 이유가 궁금해용

2022-11-01 05:47 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +        this.availableTimes.addAll(availableTimes);
`this.availableTimes.removeIf(availableTime -> availableTime.getMemberId().equals(memberId) && !localDateTimes.contains(availableTime.getStartDateTime()));`

이런식으로 remove 조건을 변경하거나 unique 제약조건을 삭제해야겠네용

2022-11-01 06:39 UTC, leo0842 approved these changes
동료들이 리뷰를 너무 잘해줬네요! 수고하셨어요~!

2022-11-01 06:39 UTC, leo0842 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        validateSelectTime(now, localDateTimes);
변수명이 `localDateTimes` 보다는 `selectedDateTimes` 같은게 더 가독성 측면에서 좋을 것 같아요!

2022-11-01 06:39 UTC, leo0842 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +                .anyMatch(dateTime -> !isDateTimeBetween(dateTime, now))) {
여기를 nonMatch() 로 바꾸면 바깥에서 `! 연산자` 가 사라질 수 있을 것같아요!

2022-11-04 12:18 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +        this.availableTimes.addAll(availableTimes);
엘리의 의견 적극 반영할게요. 좀 치네

2022-11-04 12:33 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +public class AvailableTimes {
바꿨어요

2022-11-04 12:36 UTC, seong-wooo commented on backend/src/test/resources/schema.sql
> +    `selected_count`   BIGINT       NOT NULL DEFAULT 0,
data.sql은 추가했었고, 나머지 다 추가 해놨습니다~

2022-11-04 12:45 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +        this.availableTimes.addAll(availableTimes);
엘리가 좀 똑똑하네요. 의견 반영했습니다

2022-11-04 12:50 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    private long selectedCount;
저는 member의 자료형을 따라가려고 했어요.
한 팀에 엄청나게 많은 member가 있다면? 그만큼 selectCount도 커질 것이라 생각이 들었어요.


근데 지금 생각해보니까 너무 극단적으로 생각했나? 싶기도 하네요.

그래도 혹시 모르니까 long이 낫지 않을까요?

2022-11-04 12:51 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +    private void countUpIfNotExists(Long memberId) {
availableTimes 내부로 이 메서드를 옮기면서 자연스럽게 해결했습니다

2022-11-04 13:13 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
퀴즈인가요?
엘리 덕분에 공부하나 했네요.

제가 실험해본 결과, PERSIST와 REMOVE가 필요합니다.

PERSIST는 appointment와 함께 availableTime도 영속성을 가져야해서 필요합니다.
REMOVE는 appointment가 삭제될 때 availableTime도 삭제되어야하니까 필요합니다.

틀렸으면 혼내세요

2022-11-04 13:16 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        validateSelectTime(now, localDateTimes);
투표합시다

localDateTimes -> 👍
selectedDateTimes -> 👎

2022-11-04 13:16 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +                .anyMatch(dateTime -> !isDateTimeBetween(dateTime, now))) {
이걸 왜 생각못했을까요 ~ 
바로 적극 반영해버렸습니다

2022-11-05 05:42 UTC, cjlee38 approved these changes
변경분 확인했습니다. 고생하셨어요 까라 ~

2022-11-05 05:42 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        validateSelectTime(now, localDateTimes);
`selectedDateTimes` 는 "기존에 선택된 시간"과 헷갈릴 여지가 있어서 다른 이름이 나을 것 같네요. `currentDateTimes` 같은 이름이 낫지 않을까 싶어요.

2022-11-05 06:24 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/appointment/domain/AvailableTimes.java
> +    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
orphanRemoval 이 cascade All에서 동작을 하기 때문이에요

2022-11-06 11:13 UTC, seong-wooo commented
> 까라 수고 많았어용 AvailableTimes 부분만 수정해보면 좋을 것 같네요.
> 
> 그리고 Performance 테스트에 선택, 재선택 다른 멤버 선택이 있는데, 재선택 시 이전 선택과 겹치는 시간과 겸치치 않는 시간을 가진 요청으로 변경해보면 좋을 것 같요!
> 
> ### Fixture 변경
> ```java
> // 선택 시 사용
> public static final List<AvailableTimeRequest> 약속잡기_가능시간_3개_선택_요청_데이터A = List.of(
>         모락_회식_첫째날_4시부터_4시반_선택_요청_데이터,
>         모락_회식_첫째날_4시반부터_5시_선택_요청_데이터,
>         모락_회식_첫째날_5시부터_5시반_선택_요청_데이터
> );
> 
> // 재선택 시 사용
> public static final List<AvailableTimeRequest> 약속잡기_가능시간_3개_선택_요청_데이터B = List.of(
>         모락_회식_첫째날_5시반부터_6시_선택_요청_데이터,
>         모락_회식_첫째날_6시부터_6시반_선택_요청_데이터,
>         모락_회식_첫째날_6시반부터_7시_선택_요청_데이터
> );
> ```

엘리 말 듣고 재선택 시 이전 시간과 안겹치게 테스트를 진행해보았는데요~

이 과정에서 available_time 테이블에 id가 primary key가 아니어서 성능에 문제가 생긴 것을 확인했습니다.

2022-11-06 12:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
> +        validateSelectTime(now, localDateTimes);
지금 보니까 이름이 조금 어색한 것 같네용.
`validateTimesSelectable` 은 어떤가요?

2022-11-08 02:24 UTC, RIANAEH approved these changes
까라 고생많았어요💯
머지 가시죵!

2022-11-08 02:43 UTC, merged