feat: 재사용 컴포넌트에 대한 storybook 추가 생성
woowacourse-teams/2022-mo-rak pull request #556
Opened 2022-11-01 14:19 UTC by al-bur

## 상세 내용

- Avatart 컴포넌트등 재사용 컴포넌트에 대한 storybook 추가 생성하였습니다.
- stories.tsx 파일에서 export 하는 것을 한 번에 모아서 제일 마지막에 export 해주었습니다. (가독성, 컨벤션)

Close #507

2022-11-03 02:10 UTC, rladpwl0512 requested changes
앨버 storybook 작성하시느라 수고 많으셨습니다~! 🐝👋
몇가지 커멘트 남겼으니 확인해주세요 :)

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/Avatar/Avatar.stories.tsx
> +export { Default, Named, NoImageFound };
한번에 export 하니까 더 깔끔하네요! :)

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/Box/Box.stories.tsx
>  };
```js
const DefaultTemplate: Story = (args) => (
  <Box width="84.4rem" height="40rem" borderRadius="15px" {...args} />
);
const Default = DefaultTemplate.bind({});
```

이 코드와는 무엇이 다른가요? 🤔 방식이 혼합되어있는 것 같아서, 하나로 통일해주면 좋을 것 같은데 혹시 의도가 있을까요?

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/Box/Box.stories.tsx
>    borderRadius: '15px'
이번에 작성해주신부분은 아니지만, default가 15px이니까 삭제해도 될까요?

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/FlexContainer/FlexContainer.stories.tsx
> +`;
오 FlexContainer를 테스트하고자 SampleBox를 만들었네요! 👍
여기서는 지금까지 styled 컴포넌트를 만들어줬을 때 지켜줬던 네이밍 컨벤션을 지켜주지 않으셨는데, 이유가 있을까요?
(`StyledBox`)

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/Modal/Modal.stories.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-empty-function
이 주석이 없으면 eslint 오류가 뜨나요? 🤔

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/Radio/Radio.stories.tsx
>  Default.args = {};
이번에 작성해주신 것은 아니지만, 여기는 생략해도 될 것 같네요!

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/Select/Select.stories.tsx
> +Outlined.args = {};
이 코드가 하는 역할이 있을까요?

2022-11-03 02:10 UTC, rladpwl0512 commented on frontend/src/components/Tooltip/Tooltip.stories.tsx
> +    <Tooltip placement="top" content="툴팁입니다." width="8" {...args}>
제가 실수로 Tooltip에 rem을 고정으로 넣어놔서 width가 8으로 넣어주셨네요 😅 
혹시 수정해주셨나요?

2022-11-03 02:37 UTC, al-bur commented on frontend/src/components/Box/Box.stories.tsx
>  };
이것은 차이가 있는데요~ 아래는 Box와 Button 컴포넌트에 대한 스토리입니다. 위니가 보기에는 무슨 차이가 있는 것 같아 보이나요?

```typescript
const DefaultTemplate: Story = (args) => <Box {...args} />;
const Default = DefaultTemplate.bind({});
Default.args = {
  width: '84.4rem',
  height: '40rem',
  borderRadius: '15px'
};

```


```typescript
const FilledTemplate: Story = (args) => (
  <Button {...args} colorScheme={theme.colors.PURPLE_100} variant="filled">
    투표 만들기
  </Button>
);

const Filled = FilledTemplate.bind({});
Filled.args = {
  width: '46rem',
  borderRadius: '10px',
  color: theme.colors.WHITE_100,
  fontSize: '2rem'
};

```

2022-11-03 02:40 UTC, al-bur commented on frontend/src/components/Box/Box.stories.tsx
>    borderRadius: '15px'
일단, 현재 pr에 해당 내용이 담겨있지 않기 때문에, 삭제하면 안될 것 같아요

그리고, args에 넣어주는 값들은 storybook 상에서 customize 해줄 수 있기 때문에 default 값이 있더라도 넣어주는 게 좋을 것 같아요!

2022-11-03 02:41 UTC, al-bur commented on frontend/src/components/FlexContainer/FlexContainer.stories.tsx
> +`;
그렇네요! story 파일이라서, 놓쳤던 것 같아요~

2022-11-03 02:44 UTC, al-bur commented on frontend/src/components/Modal/Modal.stories.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-empty-function
네네

```typescript
<Modal isVisible={true} close={() => {}} {...args}>
```

story에서는 현재, close에 역할을 테스트하지 않아서, 익명함수를 넣어주었습니다. 해당 부분에 lint 오류가 발생하여, 해당 부분에만 예외를 적용시켜줬어요! 프로덕션에 나가는 코드가 아니라서, 이 부분은 조금 예외로 적용해줬는데 어떤가요

2022-11-03 02:46 UTC, al-bur commented on frontend/src/components/Tooltip/Tooltip.stories.tsx
> +    <Tooltip placement="top" content="툴팁입니다." width="8" {...args}>
이 부분은 수정안했습니다!! 현재 pr이 스토리북과 관련된 내용이라, 추후에 다른 pr에서 해줘야할 것 가탕요

2022-11-03 02:46 UTC, al-bur commented on frontend/src/components/Radio/Radio.stories.tsx
>  Default.args = {};
[e555d9b](https://github.com/woowacourse-teams/2022-mo-rak/pull/556/commits/e555d9b0a0a27a24869b5cb819ea3e665fb43c69)

2022-11-03 02:46 UTC, al-bur commented on frontend/src/components/Select/Select.stories.tsx
> +Outlined.args = {};
[f1114e6](https://github.com/woowacourse-teams/2022-mo-rak/pull/556/commits/f1114e6bfc892326320575e98e09cda19dd4fc0a)

2022-11-03 02:49 UTC, al-bur commented on frontend/src/components/Radio/Radio.stories.tsx
>  Default.args = {};
삭제해주었습니다!

2022-11-03 02:49 UTC, al-bur commented on frontend/src/components/Select/Select.stories.tsx
> +Outlined.args = {};
삭제해주었습니다!

2022-11-03 02:49 UTC, al-bur commented on frontend/src/components/FlexContainer/FlexContainer.stories.tsx
> +`;
수정하였습니다! [770a52e](https://github.com/woowacourse-teams/2022-mo-rak/pull/556/commits/770a52e5f5304cfdcd6393f28c9c063a18a88a1e)

2022-11-04 04:24 UTC, rladpwl0512 approved these changes
수고하셨습니다 
approve 할게요 :)

2022-11-04 04:24 UTC, rladpwl0512 commented on frontend/src/components/Box/Box.stories.tsx
>  };
아하 꼭 들어가야 하는 props가 있는 Button같은 경우 아래와 같이 작성해야하는군요!

2022-11-04 06:25 UTC, al-bur commented on frontend/src/components/Box/Box.stories.tsx
>  };
맞습니다!

2022-11-04 06:25 UTC, merged