비동기 메소드에서 예외 발생시 로깅을 남긴다.
woowacourse-teams/2022-mo-rak pull request #574
Opened 2022-11-07 05:10 UTC by cjlee38

## 상세 내용

[개발일지](https://ririhan.notion.site/BE-300c1c979adc4854810d0fe273d4e1a3)
Close #573

2022-11-07 08:13 UTC, seong-wooo requested changes
어려운 내용이네요.

2022-11-07 08:13 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/config/AsyncConfig.java
> +    private static final int THREAD_COUNT = 4;
4에 특별한 의미가 있을까요?

2022-11-07 08:13 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/notification/application/NotificationService.java
>      private Map<Member, String> mapRoleNameByMember(RoleHistoryEvent event) {
`event.getRoleNameByMemberIds().get(member.getId())` 

객체지향적이지못하네요

2022-11-07 08:15 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/config/AsyncConfig.java
> +    private static final int THREAD_COUNT = 4;
특별한건 아닌데, 기본적으로 멀티스레딩 설정시 core 개수 * 2 로 잡는게 가장 default로 알고 있습니다.

2022-11-07 08:17 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/notification/application/NotificationService.java
>      private Map<Member, String> mapRoleNameByMember(RoleHistoryEvent event) {
이벤트에 getter에 손을 대야할까요 ?

2022-11-07 08:20 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/notification/application/NotificationService.java
>      private Map<Member, String> mapRoleNameByMember(RoleHistoryEvent event) {
`member -> event.getRoleName(member.getId())` 이런 느낌?

2022-11-07 08:26 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/notification/application/NotificationService.java
>      private Map<Member, String> mapRoleNameByMember(RoleHistoryEvent event) {
흠.. 이벤트는 뭔가 dto 역할이라 생각했는데요. 우선 바꿨을 때 어떤 문제가 발생할지 예상이 안되네요. 일단 반영하겠습니다. 하는김에 lombok도 붙이겠습니다.

2022-11-07 08:30 UTC, RIANAEH approved these changes
차리 덕분에 또 이벤트 관련해서 신기한 정보 얻어가네요~~
이벤트 더 공부하겠습니다!

2022-11-07 08:30 UTC, RIANAEH commented on backend/src/main/java/com/morak/back/core/config/AsyncConfig.java
> +    private static final int THREAD_COUNT = 4;
<img width="1205" alt="Screen Shot 2022-11-07 at 5 21 16 PM" src="https://user-images.githubusercontent.com/45311765/200260677-d5c28051-bcf6-40ce-ad2f-39fec35e491d.png">

2022-11-08 02:11 UTC, seong-wooo approved these changes

2022-11-08 02:13 UTC, leo0842 approved these changes
조금 더 공부해보겠습니다~!

2022-11-08 02:23 UTC, merged