chore: 설정파일을 정리한다.
woowacourse-teams/2022-mo-rak pull request #582
Opened 2022-11-08 05:29 UTC by cjlee38

## 상세 내용

[개발일지](https://ririhan.notion.site/80a8d71ae6be47239dded34188386de9)

Close #554

2022-11-08 05:49 UTC, RIANAEH requested changes
차리 설정파일 아주 야무지게 정리해주셨네요👍
그 동안 신경쓰지 못한 점 반성합니다🥲

2022-11-08 05:49 UTC, RIANAEH commented on backend/src/main/resources/application.yml
> +    open-in-view: false
A: open-in-view 설정까지 야무지게 꺼주셨네요👍
저희는 Service 레이어 밖에서 커넥션을 사용하는 로직이 없기 때문에 문제가 발생하지 않겠죠..?

2022-11-08 05:49 UTC, RIANAEH commented on backend/src/test/resources/application.yml
> +        default_batch_fetch_size: 1000
R: 프로덕션 설정과 같이 batch size를 100으로 주는게 좋지 않을까요?

2022-11-08 05:49 UTC, RIANAEH commented on backend/src/test/resources/application.yml
> +#    password: root
A: 도커 상황을 위해 항상 환경 변수로 DB url을 설정하도록 했던 스스로를 반성하게 되네요😉

2022-11-08 05:49 UTC, RIANAEH commented on backend/src/main/resources/application.yml
> +  shutdown: graceful
A: 제가 이해하기로 graceful 옵션은 처리하던 응답을 모두 처리한 후 종료를 하겠다는 의미인 것 같아요. kill -9와 함께 하면 의미가 없을 것 같다고 생각했는데.., 이미 15로 바꿔줬다고 들었어요. 아주 굿입니다👏

2022-11-08 05:49 UTC, RIANAEH commented on backend/src/main/resources/application.yml
> +    timeout-per-shutdown-phase: 30s
C: 기본 설정이 30초라고 하는데, 명시성을 위해 적은거겠죠?

2022-11-08 06:23 UTC, cjlee38 commented on backend/src/test/resources/application.yml
> +        default_batch_fetch_size: 1000
넵

2022-11-08 06:23 UTC, cjlee38 commented on backend/src/main/resources/application.yml
> +    open-in-view: false
넵

2022-11-08 06:23 UTC, cjlee38 commented on backend/src/main/resources/application.yml
> +    timeout-per-shutdown-phase: 30s
맞습니당

2022-11-08 07:33 UTC, seong-wooo approved these changes

2022-11-08 07:33 UTC, seong-wooo commented on backend/src/main/resources/application.yml
> +          provider_disables_autocommit: true
# hibernate.connection.provider_disables_autocommit=true 설정으로 인해 얻을 수 있는 추가 효과
기존에 동적으로 현재 커넥션의 autoCommit 설정을 확인하기 위해 determineInitialAutoCommitMode() 를 수행한다.
이때, getConnectionForTransactionManagement() 를 통해 실제 DB 커넥션을 가져오게 되는데 이를 나중으로 미루어 Throughput을 향상시킬 수 있다.
doConnectionsFromProviderHaveAutoCommitDisabled()을 통해hibernate.connection.provider_disables_autocommit 설정을 체크한다.
doConnectionsFromProviderHaveAutoCommitDisabled()가 false일 경우 determineInitialAutoCommitMode()를 수행하며 setAutoCommit을 수행한다.
이때, getConnectionForTransactionManagement()을 수행하는데 setAutoCommit을 하려고 여기서 실제 DB 커넥션을 가져온다.
따라서, hibernate.connection.provider_disables_autocommit을 true로 설정할 경우, 커넥션을 가져오는 것을 미룰 수 있어 Throughput을 향상 시킬 수 있다.

2022-11-08 07:33 UTC, seong-wooo commented on backend/src/main/resources/application.yml
> +      auto-commit: false
hibernate.connection.provider_disables_autocommit=true로 놓고 DBCP의 autoCommit을 true로 놓게되면?
DBCP가 커넥션을 생성하여 가지고 있으므로, 생성 시점부터 항상 autoCommit=true라 트랜잭션 안에 메소드가 수행하다 실패해도 롤백이 안된다.
따라서, hibernate.connection.provider_disables_autocommit=true를 사용할거면 DBCP의 autoCommit을 false로 놓아서 트랜잭션 단위로 동작할 수 있도록 해야한다.

2022-11-08 07:36 UTC, seong-wooo approved these changes

2022-11-08 07:36 UTC, seong-wooo commented on backend/src/main/resources/application.yml
> +    open-in-view: false
문제) 켰을 때와 껐을 때 어떤 성능 차이가 있을까요?

2022-11-08 07:44 UTC, leo0842 approved these changes
고생하셨습니다~!!

2022-11-09 06:47 UTC, RIANAEH approved these changes
![image](https://user-images.githubusercontent.com/45311765/200758763-4a846a61-0339-4852-b19e-119ded09e69e.png)

2022-11-09 06:47 UTC, merged