refactor: 초기 그룹 참여 페이지 컴포넌트 추상화
woowacourse-teams/2022-mo-rak pull request #603
Opened 2022-11-16 06:16 UTC by rladpwl0512

## 상세 내용
- ✅ 테스트 통과 완료 
- 초기 그룹 참여 페이지 컴포넌트 추상화 
- [개발 일지](https://ririhan.notion.site/GroupInitPage-01fdbcf415ee40d2863c9b37b1707875)를 참고해주세요 :)

Close #599

2022-11-17 08:07 UTC, al-bur commented
빠른 시일내에 리뷰할게요!

2022-11-18 13:35 UTC, al-bur requested changes
위니 고생했어요~~

컨벤션에 맞도록 컴포넌트 네이밍 변경이랑 의도를 좀 더 정확히 나타내줄 수 있도록 네이밍을 고려해볼 부분 하나 더 해서 코멘트 남겼어요!!

2022-11-18 13:35 UTC, al-bur commented on frontend/src/pages/GroupInitPage/GroupInitPage.tsx
> -  return <GroupInitContainer />;
없애고, 더 잘보이도록 해준 것 좋네요!

2022-11-18 13:35 UTC, al-bur commented on frontend/src/pages/GroupInitPage/GroupInitPage.tsx
> +      <GroupInitTitle />
Title도 좋은데, 지금 보면 title과 세부 description과 이미지도 있어서 혹시 더 넓은 범위의 네이밍은 어떨까요?
예를 들어, `Header`도 있을 수 있겠네요!

2022-11-18 13:35 UTC, al-bur commented on frontend/src/pages/GroupInitPage/components/GroupInitForms/GroupInitForms.tsx
> +    <StyledBottomContainer>
StyledContainer!!

2022-11-22 08:29 UTC, rladpwl0512 commented on frontend/src/pages/GroupInitPage/GroupInitPage.tsx
> +      <GroupInitTitle />
그러네요! 👍  
더 넓게 네이밍을 `GroupInitHeader` 로 변경했습니다 :)

---
[refactor: 컴포넌트명 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/603/commits/62e1fe6047d41f999e249ee8c9eabe7d2807a650)

2022-11-22 08:29 UTC, rladpwl0512 commented on frontend/src/pages/GroupInitPage/components/GroupInitForms/GroupInitForms.tsx
> +    <StyledBottomContainer>
놓쳤네요... 변경했습니다 :) 

---
[refactor: 컴포넌트명 변경](https://github.com/woowacourse-teams/2022-mo-rak/pull/603/commits/6092df651d0566172e29f143d9feb7a4cb255983)

2022-11-22 08:30 UTC, rladpwl0512 commented
✅ 테스트 통과 완료

앨버 꼼꼼한 리뷰 감사합니다~ 🔥🐝
리뷰 반영했으니 확인해주세요 :)

2022-11-22 11:40 UTC, al-bur approved these changes
고생했습니다~ 위니 approve할게요

2022-11-22 11:41 UTC, merged