refactor: 약속 생성, 진행 페이지 컴포넌트 추상화
woowacourse-teams/2022-mo-rak pull request #605
Opened 2022-11-16 06:19 UTC by rladpwl0512

## 상세 내용
- ✅ 테스트 통과 완료
- 약속 생성, 진행 페이지 컴포넌트 추상화
[개발 일지](https://ririhan.notion.site/8892db19ebb4451389bf0d3ac0de0ad5)를 참고해주세요 :)

Close #604

2022-11-17 08:07 UTC, al-bur commented
빠른 시일내에 리뷰할게요!

2022-11-18 13:26 UTC, al-bur commented on frontend/src/pages/AppointmentCreatePage/AppointmentCreatePage.tsx
>        <StyledContentContainer>
`StyledContentContainer`가 따로 컴포넌트로 존재하지 않고, `StyledContainer` 컴포넌트에 css 속성을 넣어주는 건 어떨까요???

2022-11-18 13:30 UTC, al-bur requested changes
위니 고생했어요!!
컴포넌트 추상화를 하니까, 훨씬 페이지 컴포넌트가 깔끔해졌네요ㅎㅎ

코멘트 2개 남겼으니 확인해주세요~


![02c443cbd30ca0dc8814786a6ee39a06](https://user-images.githubusercontent.com/64825713/202716265-848ea63a-0c3b-485f-a131-33664b799198.gif)

2022-11-18 13:30 UTC, al-bur commented on frontend/src/pages/AppointmentCreatePage/AppointmentCreatePage.tsx
> +        <AppointmentCreateInputs />
좋습니다~

2022-11-22 08:41 UTC, rladpwl0512 commented on frontend/src/pages/AppointmentCreatePage/AppointmentCreatePage.tsx
>        <StyledContentContainer>
안그래도 이 부분을 하나로 통합하려고 시도했었는데요, 현재 UI 상태로는 불가능합니다 🥲 각 컴포넌트의 역할이 있어요! 
일지에도 아래와 같이 적어놨는데요, 확인해주세요! 
(약속잡기 기능에 대한 UI가 페이지별로 뒤죽박죽인 느낌이 있어서 개선하려고 하는데, 이 때 하나로 통합할 수 있을 것 같아요!) 

>  `StyledContainer`는 컨텐츠(`StyledContentContainer`)를 가운데로 이동하기 위해 필요한 컴포넌트이고, `StyledContentContainer`는 컨텐츠의 내부를 column으로 배치하고, gap을 주기 위한 컴포넌트이다.
> 이후에 약속잡기 기능에 대한 UI/UX 개선을 통해 하나의 컴포넌트로 스타일을 줄 수 있다면 좋을 것 같다.

2022-11-22 11:45 UTC, al-bur commented on frontend/src/pages/AppointmentCreatePage/AppointmentCreatePage.tsx
>        <StyledContentContainer>
아아! 그렇네요 제가 착각했던 것 같습니다ㅎㅎ!!

2022-11-22 11:46 UTC, al-bur approved these changes
고생하셨어요~

2022-11-22 11:46 UTC, merged