분산락 key 값을 동적으로 생성한다.
woowacourse-teams/2022-mo-rak pull request #627
Opened 2023-08-05 15:24 UTC by seong-wooo

## 상세 내용
https://github.com/woowacourse-teams/2022-mo-rak/pull/613#discussion_r1160438277

위의 댓글을 보고 수정했습니다.

SPeL을 이용하여 key를 동적으로 생성할 수 있습니다. 

Close #626

2023-08-05 15:40 UTC, cjlee38 requested changes

2023-08-05 15:40 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +}
c: 혹시 `TransactionTemplate` 이라고 들어보셨나요 ?

2023-08-05 15:40 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/DistributedLockAspect.java
> +        return parser.parseExpression(key).getValue(context, Object.class);
r: spel 로 처리할 필요 없이, 어노테이션에 파라미터 이름을 달아주고, aop 쪽에서 이름으로 파라미터를 찾는게 더 단순하지 않을까요 ? spel 을 써야하는 이유가 있나요 ?

2023-08-05 15:40 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/DistributedLockAspect.java
> +            throw new InterruptedException();
r: catch 구문이 필요한 이유가 있을까요 ?
필요하다면, 단순히 throw 만 해도 괜찮을까요 ?

2023-08-05 15:45 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +}
찾아볼게요

2023-08-14 05:27 UTC, leo0842 approved these changes
기술 부채를 해결해주셔서 감사합니다,,!

2023-08-14 05:27 UTC, leo0842 commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
트랜잭션의 전파가 REQUIRES_NEW 인 이유를 알고 싶습니다!

2023-08-14 05:27 UTC, leo0842 commented on backend/build.gradle
> +        exclude group: 'org.slf4j', module: 'slf4j-simple'
springboot 3 에서부터 문제가 되는 걸로 알고있는데, 혹시 버전업을 고려해서 제외하신 건가요? 또는 잠재적인 취약점으로 인해 제외하신건가요?

2023-08-14 08:34 UTC, seong-wooo commented on backend/build.gradle
> +        exclude group: 'org.slf4j', module: 'slf4j-simple'
현재 버전에서도 제외하지 않고 테스트를 돌리면, 아래처럼 Class path contains multiple SLF4J bindings. 멘트가 뜨더라구요!
그래서 혹시모를 예외에 대비해서 제외하였습니다!

![image](https://github.com/woowacourse-teams/2022-mo-rak/assets/79205414/c583d80a-66b2-4175-9844-ce565559e14c)

2023-08-14 09:13 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
트랜잭션을 새롭게 실행해야합니다!

앞서 작성해주신 PR에 그림을 보면서 설명해볼게요!

![image](https://github.com/woowacourse-teams/2022-mo-rak/assets/79205414/5b4f3a2c-7996-46ac-8aa9-bbf39851c035)

위의 그림에서는 트랜잭션A가 커밋된 이후에 트랜잭션B가 실행됩니다. 따라서 트랜잭션 A가 `커밋한 내용`을 트랜잭션 B가 읽게 됩니다.

![image](https://github.com/woowacourse-teams/2022-mo-rak/assets/79205414/7fa833d1-8701-4099-95a9-8e61abf469eb)

위는 트랜잭션을 새롭게 시작하지 않은 상태(이전 PR)에서의 진행 방식입니다.
조금 오류가 있는 것 같아요. 
요청 B는 트랜잭션A가 커밋되기 이전에 락을 획득하므로, 트랜잭션A의 내용이 반영되기 이전의 값을 조회합니다.
따라서 트랜잭션A와 트랜잭션B는 결국 같은 count 값을 저장하게 됩니다. 따라서 트랜잭션A가 끝난 이후에 트랜잭션B가 실행되어야 트랜잭션B는 트랜잭션A에서 커밋한 내용을 반영할 수 있습니다.

<img width="635" alt="image" src="https://github.com/woowacourse-teams/2022-mo-rak/assets/79205414/f0672e5f-3509-4ba1-8371-16dc63cbebc3">


혹은 다른 관점으로도 생각해보았는데요. 요청A가 락을 해제했지만 트랜잭션B가 트랜잭션A보다 먼저 끝난다면? 문제가 발생할 것 같습니다!

<img width="588" alt="image" src="https://github.com/woowacourse-teams/2022-mo-rak/assets/79205414/9219b193-79b5-47c0-9c1a-7404d3c060ff">

2023-08-14 09:17 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/support/DistributedLockAspect.java
> +            throw new InterruptedException();
제가 좀 감을 잃었네요. 
에러 코드랑 메시지도 추가했어요

2023-08-14 11:27 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +}
`TransactionTemplate` 활용해주세요 ㅋㅋ

2023-08-14 11:38 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
이 문제는 트랜잭션 AOP 와 분산락 AOP 의 순서를 정확하게 알고 있어야 해결이 가능할 것 같은데요. 분산락 AOP 에 `@Order` 어노테이션이 `1` 로 달려있긴 한데 트랜잭션 AOP 의 Order 가 몇인지 몰라서 뭐가 맞다고 이야기하지는 못하겠네요.

다만, 가정을 해보면

1. 분산락 AOP 가 트랜잭션 AOP 보다 바깥인 경우 -> 분산락 AOP 에서 분산락을 얻는 시점에 트랜잭션이 시작되지 않았으므로 위 설명은 틀린 설명이 됩니다. A 요청에서 분산락을 먼저 취득해버렸기 때문에 B 요청에서 분산락을 취득하려고하는 시점에서는 트랜잭션이 시작되기 이전이기 때문입니다. 마찬가지로, 분산락을 놓을떄에도 A 요청에서 먼저 놓아줘야 B 요청에서 취득이 가능하기 때문에 문제가 발생하지 않습니다.
2. 분산락 AOP 가 트랜잭션 AOP 보다 안쪽인 경우 -> 이 경우에는 위에서 설명한 문제가 발생할 수 있습니다. A, B 요청 둘다 트랜잭션을 물고 있는 상태에서 분산락에 대한 경합을 진행하기 때문입니다. 분산락을 놓을때도 마찬가지로 위에서 언급해주셨듯이 A 요청에 대해 분산락을 놓고, A 요청에 대한 커밋을 진행하기 전의 순간에  B 요청에 대한 락취득 -> 로직 수행 -> 락해제 -> 커밋 이 한번에 일어난다면 발생할 수 있겠네요.

2023-08-14 12:16 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
오호 1번처럼 생각은 못해봤는데, 찾아보니 Order를 통해 Aspect가 실행되는 순서를 보장할 수 있네요.
DistributedLockAspect에 `@Order(value=1)` 이 존재하는 것을 지금 알게 되었어요. 이미 잘 짜놓으셨군요 !
새로운 트랜잭션을 여는 부분 제거하겠습니다.

2023-08-14 12:17 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/support/AopForTransaction.java
> +}
지웟어요~

2023-08-14 12:27 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/support/DistributedLockAspect.java
> +        return parser.parseExpression(key).getValue(context, Object.class);
파라미터 하나로만 key 값을 만들지 않을수도 있기 때문에 조금 어려워 보일지라도 이렇게 하는게 맞는 것 같아요~

예를 들어서 teamCode + memberId + appointmentCode 3개의 조합으로 key를 만든다고하면
`@DistributedLock(key = "teamCode,appointmentCode,appointmentCode")` 이런 식이 될 것 같은데
또 파싱하는 과정이 필요하고.. 
key를 만드는 형식을 @DistributedLock을 사용하는 곳에서 알아야하는 단점도 있고 .. 

근데  `@DistributedLock(key = "#teamCode.concat(#appointmentCode).concat(#appointmentCode"))`
이런식으로 spel 만 알면 key를 만드는건 자유롭게 할 수 있으니까  

spel이 나은듯 하네요

2023-08-14 13:25 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/DistributedLockAspect.java
> +        return parser.parseExpression(key).getValue(context, Object.class);
여러개로 조합하는 경우에는 문자열 어레이로 받으면 되지 않을까요? 새로운 팀원이 합류했다고 가정했을때, 키값을 생성하는 로직을 코드를 보지 않고도 직관적으로 이해하려면 단순하게 문자열을 사용하는게 낫지 않을까요?

복잡한 로직을 심어줘야 하는 케이스가 아니라면 여전히 spel 을 써야하는 이유를 모르겠네요 ㅎㅎ

2023-08-14 13:52 UTC, seong-wooo commented on backend/src/main/java/com/morak/back/core/support/DistributedLockAspect.java
> +        return parser.parseExpression(key).getValue(context, Object.class);
파라미터로 받는 방식은 딱 파라미터에 관해서만 키 값을 만들 수 있고 spel을 사용하면 더 다양하게 키 값을 만들 수 있는데 
더 사용성이 좋지 않을까요 ,.

2023-08-14 14:49 UTC, cjlee38 commented on backend/src/main/java/com/morak/back/core/support/DistributedLockAspect.java
> +        return parser.parseExpression(key).getValue(context, Object.class);
ㅋㅋㅋ 넵 알겠습니다

2023-08-28 11:52 UTC, cjlee38 approved these changes

2023-09-05 08:02 UTC, merged